package com.mfangsoft.zhuangjialong.system.model;

import java.io.Serializable;

/**
 * table t_sys_constant
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class sysConstantEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   key
     * column key
     *
     * @MLTH_generated
     */
    private String key;

    /**
     *   值
     * column value
     *
     * @MLTH_generated
     */
    private String value;

    /**
     *   类别
     * column type
     *
     * @MLTH_generated
     */
    private String type;

    /**
     *   描述
     * column description
     *
     * @MLTH_generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_constant
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   key
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getKey() {
        return key;
    }

    /**
     *   key
     * @param key the value for 
     *
     * @MLTH_generated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     *   值
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getValue() {
        return value;
    }

    /**
     *   值
     * @param value the value for 
     *
     * @MLTH_generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     *   类别
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getType() {
        return type;
    }

    /**
     *   类别
     * @param type the value for 
     *
     * @MLTH_generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     *   描述
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getDescription() {
        return description;
    }

    /**
     *   描述
     * @param description the value for 
     *
     * @MLTH_generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", key=").append(key);
        sb.append(", value=").append(value);
        sb.append(", type=").append(type);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}