package com.mfangsoft.zhuangjialong.app.helpfeedback.model;

import java.io.Serializable;
import java.util.Date;

/**
 *   反馈表
 * table t_biz_help_feedback
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class HelpFeedBackEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   反馈者ID
     * column feedbacker_id
     *
     * @MLTH_generated
     */
    private Long feedbacker_id;

    /**
     *   联系电话
     * column phone_num
     *
     * @MLTH_generated
     */
    private String phone_num;

    /**
     *   反馈日期
     * column create_date
     *
     * @MLTH_generated
     */
    private Date create_date;

    /**
     *   买家/卖家
     * column feedbacker_type
     *
     * @MLTH_generated
     */
    private Integer feedbacker_type;
    
    /**
     *   买家/卖家
     * column feedbacker_type
     *
     * @MLTH_generated
     */
    private Integer state;


    /**
     *   反馈内容
     * column content
     *
     * @MLTH_generated
     */
    private String content;

    private String img_url;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_help_feedback
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   反馈者ID
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Long getFeedbacker_id() {
        return feedbacker_id;
    }

    /**
     *   反馈者ID
     * @param feedbacker_id the value for 
     *
     * @MLTH_generated
     */
    public void setFeedbacker_id(Long feedbacker_id) {
        this.feedbacker_id = feedbacker_id;
    }

    /**
     *   联系电话
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    
    
    public String getPhone_num() {
        return phone_num;
    }

    /**
	 * @return the state
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * @param state the state to set
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
     *   联系电话
     * @param phone_num the value for 
     *
     * @MLTH_generated
     */
    public void setPhone_num(String phone_num) {
        this.phone_num = phone_num == null ? null : phone_num.trim();
    }

    /**
     *   反馈日期
     * @return the value of DATE
     *
     * @MLTH_generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     *   反馈日期
     * @param create_date the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     *   买家/卖家
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getFeedbacker_type() {
        return feedbacker_type;
    }

    /**
     *   买家/卖家
     * @param feedbacker_type the value for 
     *
     * @MLTH_generated
     */
    public void setFeedbacker_type(Integer feedbacker_type) {
        this.feedbacker_type = feedbacker_type;
    }

    /**
     *   反馈内容
     * @return the value of LONGVARCHAR
     *
     * @MLTH_generated
     */
    public String getContent() {
        return content;
    }

    /**
     *   反馈内容
     * @param content the value for 
     *
     * @MLTH_generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String getImg_url() {
		return img_url;
	}

	public void setImg_url(String img_url) {
		this.img_url = img_url;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", feedbacker_id=").append(feedbacker_id);
        sb.append(", phone_num=").append(phone_num);
        sb.append(", create_date=").append(create_date);
        sb.append(", feedbacker_type=").append(feedbacker_type);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}