package com.mfangsoft.zhuangjialong.app.applogin.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_app_seller_log
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class BaseSellerLogEntity implements Serializable {
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   卖家id
     * column seller_id
     *
     * @MLTH_generated
     */
    private Long seller_id;

    /**
     *   设备号
     * column device_no
     *
     * @MLTH_generated
     */
    private String device_no;

    /**
     *   设备类型
     * column device_type
     *
     * @MLTH_generated
     */
    private String device_type;

    /**
     *   区域编码
     * column region_code
     *
     * @MLTH_generated
     */
    private String region_code;

    /**
     *   执行动作（0:退出 1:登陆）
     * column action
     *
     * @MLTH_generated
     */
    private Integer action;

    /**
     *   执行时间
     * column stamptime
     *
     * @MLTH_generated
     */
    private Date stamptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_app_seller_log
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   卖家id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSeller_id() {
        return seller_id;
    }

    /**
     *   卖家id
     * @param seller_id the value for 
     *
     * @MLTH_generated
     */
    public void setSeller_id(Long seller_id) {
        this.seller_id = seller_id;
    }

    /**
     *   设备号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getDevice_no() {
        return device_no;
    }

    /**
     *   设备号
     * @param device_no the value for 
     *
     * @MLTH_generated
     */
    public void setDevice_no(String device_no) {
        this.device_no = device_no == null ? null : device_no.trim();
    }

    /**
     *   设备类型
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getDevice_type() {
        return device_type;
    }

    /**
     *   设备类型
     * @param device_type the value for 
     *
     * @MLTH_generated
     */
    public void setDevice_type(String device_type) {
        this.device_type = device_type == null ? null : device_type.trim();
    }

    /**
     *   区域编码
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getRegion_code() {
        return region_code;
    }

    /**
     *   区域编码
     * @param region_code the value for 
     *
     * @MLTH_generated
     */
    public void setRegion_code(String region_code) {
        this.region_code = region_code == null ? null : region_code.trim();
    }

    /**
     *   执行动作（0:退出 1:登陆）
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getAction() {
        return action;
    }

    /**
     *   执行动作（0:退出 1:登陆）
     * @param action the value for 
     *
     * @MLTH_generated
     */
    public void setAction(Integer action) {
        this.action = action;
    }

    /**
     *   执行时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getStamptime() {
        return stamptime;
    }

    /**
     *   执行时间
     * @param stamptime the value for 
     *
     * @MLTH_generated
     */
    public void setStamptime(Date stamptime) {
        this.stamptime = stamptime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", seller_id=").append(seller_id);
        sb.append(", device_no=").append(device_no);
        sb.append(", device_type=").append(device_type);
        sb.append(", region_code=").append(region_code);
        sb.append(", action=").append(action);
        sb.append(", stamptime=").append(stamptime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}