package com.mfangsoft.zhuangjialong.app.applogin.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_biz_userequipment
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class UserEquipmentEntity implements Serializable {
    /**
     *   设备号
     * column pushstr
     *
     * @MLTH_generated
     */
    private String pushstr;

    /**
     *   设备类型
     * column platform
     *
     * @MLTH_generated
     */
    private String platform;

    /**
     *   用户名字
     * column customer_id
     *
     * @MLTH_generated
     */
    private String customer_name;
    /**
     *   用户id
     * column customer_id
     *
     * @MLTH_generated
     */
    private Long customer_id;

    /**
     *   区域代码
     * column region_code
     *
     * @MLTH_generated
     */
    private String region_code;

    /**
     *   喜好品类
     * column class_id
     *
     * @MLTH_generated
     */
    private String class_id;

    /**
     *   喜好空间
     * column space
     *
     * @MLTH_generated
     */
    private String space;

    /**
     *   喜好风格
     * column style
     *
     * @MLTH_generated
     */
    private String style;

    /**
     *   时间
     * column time
     *
     * @MLTH_generated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_userequipment
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   设备号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPushstr() {
        return pushstr;
    }

    /**
     *   设备号
     * @param pushstr the value for 
     *
     * @MLTH_generated
     */
    public void setPushstr(String pushstr) {
        this.pushstr = pushstr == null ? null : pushstr.trim();
    }

    /**
     *   设备类型
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     *   设备类型
     * @param platform the value for 
     *
     * @MLTH_generated
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     *   用户id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCustomer_id() {
        return customer_id;
    }

    /**
     *   用户id
     * @param customer_id the value for 
     *
     * @MLTH_generated
     */
    public void setCustomer_id(Long customer_id) {
        this.customer_id = customer_id;
    }

    /**
     *   区域代码
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getRegion_code() {
        return region_code;
    }

    /**
     *   区域代码
     * @param region_code the value for 
     *
     * @MLTH_generated
     */
    public void setRegion_code(String region_code) {
        this.region_code = region_code == null ? null : region_code.trim();
    }

    /**
     *   喜好品类
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public String getClass_id() {
        return class_id;
    }

    /**
     *   喜好品类
     * @param class_id the value for 
     *
     * @MLTH_generated
     */
    public void setClass_id(String class_id) {
        this.class_id = class_id;
    }

    /**
     *   喜好空间
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public String getSpace() {
        return space;
    }

    /**
     *   喜好空间
     * @param space the value for 
     *
     * @MLTH_generated
     */
    public void setSpace(String space) {
        this.space = space;
    }

    /**
     *   喜好风格
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public String getStyle() {
        return style;
    }

    /**
     *   喜好风格
     * @param style the value for 
     *
     * @MLTH_generated
     */
    public void setStyle(String style) {
        this.style = style;
    }

    /**
     *   时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getTime() {
        return time;
    }

    /**
     *   时间
     * @param time the value for 
     *
     * @MLTH_generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

	public String getCustomer_name() {
		return customer_name;
	}

	public void setCustomer_name(String customer_name) {
		this.customer_name = customer_name;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pushstr=").append(pushstr);
        sb.append(", platform=").append(platform);
        sb.append(", customer_id=").append(customer_id);
        sb.append(", region_code=").append(region_code);
        sb.append(", class_id=").append(class_id);
        sb.append(", space=").append(space);
        sb.append(", style=").append(style);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}