package com.mfangsoft.zhuangjialong.app.weixin.model;

import java.io.Serializable;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   微信门店表
 * table t_wx_store
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class WeiXinStore implements Serializable {
    /**
     * column sid
     *
     * @MLTH_generated
     */
    private Integer sid;

    /**
     *   店名
     * column business_name
     *
     * @MLTH_generated
     */
    private String business_name;

    /**
     *   门店名称
     * column branch_name
     *
     * @MLTH_generated
     */
    private String branch_name;

    /**
     *   归属省
     * column province
     *
     * @MLTH_generated
     */
    private String province;

    /**
     *   归属市
     * column city
     *
     * @MLTH_generated
     */
    private String city;

    /**
     *   门店详细地址
     * column address
     *
     * @MLTH_generated
     */
    private String address;

    /**
     *   联系电话
     * column telephone
     *
     * @MLTH_generated
     */
    private String telephone;

    /**
     *   门店类别
     * column categories
     *
     * @MLTH_generated
     */
    private String categories;

    /**
     *   补偿类别
     * column offset_type
     *
     * @MLTH_generated
     */
    private Integer offset_type;

    /**
     *   经度
     * column longitude
     *
     * @MLTH_generated
     */
    private BigDecimal longitude;

    /**
     *   纬度
     * column latitude
     *
     * @MLTH_generated
     */
    private BigDecimal latitude;

    /**
     *   图片列表
     * column photo_list
     *
     * @MLTH_generated
     */
    private String photo_list;

    /**
     *   产品推荐
     * column recommend
     *
     * @MLTH_generated
     */
    private String recommend;

    /**
     *   门店特色
     * column special
     *
     * @MLTH_generated
     */
    private String special;

    /**
     *   门店介绍
     * column introduction
     *
     * @MLTH_generated
     */
    private String introduction;

    /**
     *   营业时间
     * column open_time
     *
     * @MLTH_generated
     */
    private String open_time;

    /**
     *   平均消费价格
     * column avg_price
     *
     * @MLTH_generated
     */
    private Integer avg_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wx_store
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * @param sid the value for 
     *
     * @MLTH_generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     *   店名
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getBusiness_name() {
        return business_name;
    }

    /**
     *   店名
     * @param business_name the value for 
     *
     * @MLTH_generated
     */
    public void setBusiness_name(String business_name) {
        this.business_name = business_name == null ? null : business_name.trim();
    }

    /**
     *   门店名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getBranch_name() {
        return branch_name;
    }

    /**
     *   门店名称
     * @param branch_name the value for 
     *
     * @MLTH_generated
     */
    public void setBranch_name(String branch_name) {
        this.branch_name = branch_name == null ? null : branch_name.trim();
    }

    /**
     *   归属省
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getProvince() {
        return province;
    }

    /**
     *   归属省
     * @param province the value for 
     *
     * @MLTH_generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     *   归属市
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getCity() {
        return city;
    }

    /**
     *   归属市
     * @param city the value for 
     *
     * @MLTH_generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     *   门店详细地址
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getAddress() {
        return address;
    }

    /**
     *   门店详细地址
     * @param address the value for 
     *
     * @MLTH_generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     *   联系电话
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     *   联系电话
     * @param telephone the value for 
     *
     * @MLTH_generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     *   门店类别
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getCategories() {
        return categories;
    }

    /**
     *   门店类别
     * @param categories the value for 
     *
     * @MLTH_generated
     */
    public void setCategories(String categories) {
        this.categories = categories == null ? null : categories.trim();
    }

    /**
     *   补偿类别
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getOffset_type() {
        return offset_type;
    }

    /**
     *   补偿类别
     * @param offset_type the value for 
     *
     * @MLTH_generated
     */
    public void setOffset_type(Integer offset_type) {
        this.offset_type = offset_type;
    }

    /**
     *   经度
     * @return the value of DECIMAL
     *
     * @MLTH_generated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     *   经度
     * @param longitude the value for 
     *
     * @MLTH_generated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     *   纬度
     * @return the value of DECIMAL
     *
     * @MLTH_generated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     *   纬度
     * @param latitude the value for 
     *
     * @MLTH_generated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     *   图片列表
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPhoto_list() {
        return photo_list;
    }

    /**
     *   图片列表
     * @param photo_list the value for 
     *
     * @MLTH_generated
     */
    public void setPhoto_list(String photo_list) {
        this.photo_list = photo_list == null ? null : photo_list.trim();
    }

    /**
     *   产品推荐
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getRecommend() {
        return recommend;
    }

    /**
     *   产品推荐
     * @param recommend the value for 
     *
     * @MLTH_generated
     */
    public void setRecommend(String recommend) {
        this.recommend = recommend == null ? null : recommend.trim();
    }

    /**
     *   门店特色
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getSpecial() {
        return special;
    }

    /**
     *   门店特色
     * @param special the value for 
     *
     * @MLTH_generated
     */
    public void setSpecial(String special) {
        this.special = special == null ? null : special.trim();
    }

    /**
     *   门店介绍
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     *   门店介绍
     * @param introduction the value for 
     *
     * @MLTH_generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     *   营业时间
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getOpen_time() {
        return open_time;
    }

    /**
     *   营业时间
     * @param open_time the value for 
     *
     * @MLTH_generated
     */
    public void setOpen_time(String open_time) {
        this.open_time = open_time == null ? null : open_time.trim();
    }

    /**
     *   平均消费价格
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getAvg_price() {
        return avg_price;
    }

    /**
     *   平均消费价格
     * @param avg_price the value for 
     *
     * @MLTH_generated
     */
    public void setAvg_price(Integer avg_price) {
        this.avg_price = avg_price;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid=").append(sid);
        sb.append(", business_name=").append(business_name);
        sb.append(", branch_name=").append(branch_name);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", address=").append(address);
        sb.append(", telephone=").append(telephone);
        sb.append(", categories=").append(categories);
        sb.append(", offset_type=").append(offset_type);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", photo_list=").append(photo_list);
        sb.append(", recommend=").append(recommend);
        sb.append(", special=").append(special);
        sb.append(", introduction=").append(introduction);
        sb.append(", open_time=").append(open_time);
        sb.append(", avg_price=").append(avg_price);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}