package com.mfangsoft.zhuangjialong.app.constructAppointment.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   施工预约状态关系表
 * table t_biz_construct_state_relation
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class ConstructStateRelation implements Serializable {
    /**
     *   主键id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   预约id
     * column construct_appointment_id
     *
     * @MLTH_generated
     */
    private Long construct_appointment_id;

    /**
     *   状态编码
     * column state_code
     *
     * @MLTH_generated
     */
    private String state_code;
    
    /**
     *   状态
     * column state_code
     *
     * @MLTH_generated
     */
    private String state;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_construct_state_relation
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   预约id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getConstruct_appointment_id() {
        return construct_appointment_id;
    }

    /**
     *   预约id
     * @param construct_appointment_id the value for 
     *
     * @MLTH_generated
     */
    public void setConstruct_appointment_id(Long construct_appointment_id) {
        this.construct_appointment_id = construct_appointment_id;
    }

    /**
     *   状态编码
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getState_code() {
        return state_code;
    }

    /**
     *   状态编码
     * @param state_code the value for 
     *
     * @MLTH_generated
     */
    public void setState_code(String state_code) {
        this.state_code = state_code == null ? null : state_code.trim();
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", construct_appointment_id=").append(construct_appointment_id);
        sb.append(", state_code=").append(state_code);
        sb.append(", create_time=").append(create_time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}