package com.mfangsoft.zhuangjialong.app.constructAppointment.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * 施工预约 table t_biz_construct_appointment
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class ConstructAppointment implements Serializable {

	private String spbill_create_ip;
	private String openid;
	/**
	 * 主键id column id
	 *
	 * @MLTH_generated
	 */
	private Long id;

	/**
	 * 消费者id column customer_id
	 *
	 * @MLTH_generated
	 */
	private Long customer_id;

	/**
	 * 预约需求 column needs
	 *
	 * @MLTH_generated
	 */
	private String needs;

	/**
	 * 预约时间 column create_time
	 *
	 * @MLTH_generated
	 */
	private Date create_time;

	/**
	 * 施工员id column construct_id
	 *
	 * @MLTH_generated
	 */
	private Long construct_id;

	/**
	 * 施工地址 column address_id
	 *
	 * @MLTH_generated
	 */
	private Long address_id;

	/**
	 * 施工数据 column construct_data
	 *
	 * @MLTH_generated
	 */
	private Double construct_data;

	/**
	 * 评分 column score
	 *
	 * @MLTH_generated
	 */
	private Integer score;

	/**
	 * 预约时间 column start_time
	 *
	 * @MLTH_generated
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm", timezone = "GMT+8")
	private Date start_time;

	/**
	 * 评价时间 column start_time
	 *
	 * @MLTH_generated
	 */

	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	private Date evaluate_time;

	/**
	 * 评价内容 column construct_data
	 *
	 * @MLTH_generated
	 */

	private String evaluate_content;

	private String region_code;

	private String address_details;

	private String receiver_name;

	private String phone_num;

	public String getRegion_code() {
		return region_code;
	}

	public void setRegion_code(String region_code) {
		this.region_code = region_code;
	}

	public String getAddress_details() {
		return address_details;
	}

	public void setAddress_details(String address_details) {
		this.address_details = address_details;
	}

	public String getReceiver_name() {
		return receiver_name;
	}

	public void setReceiver_name(String receiver_name) {
		this.receiver_name = receiver_name;
	}

	public String getPhone_num() {
		return phone_num;
	}

	public void setPhone_num(String phone_num) {
		this.phone_num = phone_num;
	}

	/**
	 * @return the evaluate_time
	 */
	public Date getEvaluate_time() {
		return evaluate_time;
	}

	/**
	 * @param evaluate_time
	 *            the evaluate_time to set
	 */
	public void setEvaluate_time(Date evaluate_time) {
		this.evaluate_time = evaluate_time;
	}

	/**
	 * @return the evaluate_content
	 */
	public String getEvaluate_content() {
		return evaluate_content;
	}

	/**
	 * @param evaluate_content
	 *            the evaluate_content to set
	 */
	public void setEvaluate_content(String evaluate_content) {
		this.evaluate_content = evaluate_content;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_biz_construct_appointment
	 *
	 * @MLTH_generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 主键id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * 主键id
	 * 
	 * @param id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * 消费者id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getCustomer_id() {
		return customer_id;
	}

	/**
	 * 消费者id
	 * 
	 * @param customer_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setCustomer_id(Long customer_id) {
		this.customer_id = customer_id;
	}

	/**
	 * 预约需求
	 * 
	 * @return the value of VARCHAR
	 *
	 * @MLTH_generated
	 */
	public String getNeeds() {
		return needs;
	}

	/**
	 * 预约需求
	 * 
	 * @param needs
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setNeeds(String needs) {
		this.needs = needs == null ? null : needs.trim();
	}

	/**
	 * 预约时间
	 * 
	 * @return the value of TIMESTAMP
	 *
	 * @MLTH_generated
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * 预约时间
	 * 
	 * @param create_time
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Long getConstruct_id() {
		return construct_id;
	}

	public void setConstruct_id(Long construct_id) {
		this.construct_id = construct_id;
	}

	/**
	 * 施工地址
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getAddress_id() {
		return address_id;
	}

	/**
	 * 施工地址
	 * 
	 * @param address_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setAddress_id(Long address_id) {
		this.address_id = address_id;
	}

	public Double getConstruct_data() {
		return construct_data;
	}

	public void setConstruct_data(Double construct_data) {
		this.construct_data = construct_data;
	}

	/**
	 * 评分
	 * 
	 * @return the value of INTEGER
	 *
	 * @MLTH_generated
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * 评分
	 * 
	 * @param score
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * 预约时间
	 * 
	 * @return the value of TIMESTAMP
	 *
	 * @MLTH_generated
	 */
	public Date getStart_time() {
		return start_time;
	}

	/**
	 * 预约时间
	 * 
	 * @param start_time
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setStart_time(Date start_time) {
		this.start_time = start_time;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", customer_id=").append(customer_id);
		sb.append(", needs=").append(needs);
		sb.append(", create_time=").append(create_time);
		sb.append(", construct_id=").append(construct_id);
		sb.append(", address_id=").append(address_id);
		sb.append(", construct_data=").append(construct_data);
		sb.append(", score=").append(score);
		sb.append(", start_time=").append(start_time);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	private List<String> evaluate_imgs;

	/**
	 * @return the evaluate_imgs
	 */
	public List<String> getEvaluate_imgs() {
		return evaluate_imgs;
	}

	/**
	 * @param evaluate_imgs
	 *            the evaluate_imgs to set
	 */
	public void setEvaluate_imgs(List<String> evaluate_imgs) {
		this.evaluate_imgs = evaluate_imgs;
	}

	private String customer_name;

	/**
	 * @return the customer_name
	 */
	public String getCustomer_name() {
		return customer_name;
	}

	/**
	 * @param customer_name
	 *            the customer_name to set
	 */
	public void setCustomer_name(String customer_name) {
		this.customer_name = customer_name;
	}

	private Double total_price;

	/**
	 * @return the total_price
	 */
	public Double getTotal_price() {
		return total_price;
	}

	/**
	 * @param total_price
	 *            the total_price to set
	 */
	public void setTotal_price(Double total_price) {
		this.total_price = total_price;
	}

	public String getOpenid() {
		return openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	public String getSpbill_create_ip() {
		return spbill_create_ip;
	}

	public void setSpbill_create_ip(String spbill_create_ip) {
		this.spbill_create_ip = spbill_create_ip;
	}

}