package com.mfangsoft.zhuangjialong.app.charge.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   话费批次表
 * table t_biz_charge_batch
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class ChargeBatchEntity implements Serializable {
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   任务号
     * column task_id
     *
     * @MLTH_generated
     */
    private String task_id;

    /**
     *   订单号
     * column order_id
     *
     * @MLTH_generated
     */
    private String order_id;

    /**
     *   手机号
     * column mobile
     *
     * @MLTH_generated
     */
    private String mobile;

    /**
     *   套餐数额(签名)
     * column charge_package
     *
     * @MLTH_generated
     */
    private Integer charge_package;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date create_time;

    /**
     *   提交状态
     * column code
     *
     * @MLTH_generated
     */
    private Integer code;

    /**
     *   状态描述
     * column message
     *
     * @MLTH_generated
     */
    private String message;

    /**
     *   签名
     * column sign
     *
     * @MLTH_generated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_charge_batch
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   任务号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getTask_id() {
        return task_id;
    }

    /**
     *   任务号
     * @param task_id the value for 
     *
     * @MLTH_generated
     */
    public void setTask_id(String task_id) {
        this.task_id = task_id == null ? null : task_id.trim();
    }

    /**
     *   订单号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     *   订单号
     * @param order_id the value for 
     *
     * @MLTH_generated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     *   手机号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     *   手机号
     * @param mobile the value for 
     *
     * @MLTH_generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     *   套餐数额(签名)
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getCharge_package() {
        return charge_package;
    }

    /**
     *   套餐数额(签名)
     * @param charge_package the value for 
     *
     * @MLTH_generated
     */
    public void setCharge_package(Integer charge_package) {
        this.charge_package = charge_package;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   提交状态
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getCode() {
        return code;
    }

    /**
     *   提交状态
     * @param code the value for 
     *
     * @MLTH_generated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     *   状态描述
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getMessage() {
        return message;
    }

    /**
     *   状态描述
     * @param message the value for 
     *
     * @MLTH_generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     *   签名
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getSign() {
        return sign;
    }

    /**
     *   签名
     * @param sign the value for 
     *
     * @MLTH_generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", task_id=").append(task_id);
        sb.append(", order_id=").append(order_id);
        sb.append(", mobile=").append(mobile);
        sb.append(", charge_package=").append(charge_package);
        sb.append(", create_time=").append(create_time);
        sb.append(", code=").append(code);
        sb.append(", message=").append(message);
        sb.append(", sign=").append(sign);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
    
    
    
    private String taskid;

	/**
	 * @return the taskid
	 */
	public String getTaskid() {
		return taskid;
	}

	/**
	 * @param taskid the taskid to set
	 */
	public void setTaskid(String taskid) {
		this.taskid = taskid;
	}
    
    
    
}