package com.mfangsoft.zhuangjialong.integration.pointmall.model;

import java.io.Serializable;
import java.util.Date;

/**
 *   积分商城兑换表
 * table t_biz_point_convert
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BasePointConvertEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   消费者id
     * column customer_id
     *
     * @MLTH_generated
     */
    private Long customer_id;

    /**
     *   产品Id
     * column product_id
     *
     * @MLTH_generated
     */
    private Long product_id;

    /**
     *   店铺id
     * column shop_id
     *
     * @MLTH_generated
     */
    private Long shop_id;

    /**
     *   合伙人id
     * column partner_id
     *
     * @MLTH_generated
     */
    private Long partner_id;

    /**
     *   品牌id
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     *   创建日期
     * column crater_time
     *
     * @MLTH_generated
     */
    private Date crater_time;

    /**
     *   兑换状态(1:兑换未使用2：兑换已使用使用，)
     * column convert_state
     *
     * @MLTH_generated
     */
    private Integer convert_state;

    /**
     *   兑换码（流量：运营商编码+套餐组合id）
     * column convert_code
     *
     * @MLTH_generated
     */
    private String convert_code;

    /**
     *   兑换方式
     * column convert_type
     *
     * @MLTH_generated
     */
    private Integer convert_type;

    /**
     *   兑换日期
     * column convert_time
     *
     * @MLTH_generated
     */
    private Date convert_time;

    /**
     *   修改日期
     * column update_time
     *
     * @MLTH_generated
     */
    private Date update_time;

    /**
     *   兑换人
     * column user_id
     *
     * @MLTH_generated
     */
    private Long user_id;

    /**
     *   兑换积分数
     * column conver_point
     *
     * @MLTH_generated
     */
    private Integer convert_point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_point_convert
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   消费者id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCustomer_id() {
        return customer_id;
    }

    /**
     *   消费者id
     * @param customer_id the value for 
     *
     * @MLTH_generated
     */
    public void setCustomer_id(Long customer_id) {
        this.customer_id = customer_id;
    }

    /**
     *   产品Id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getProduct_id() {
        return product_id;
    }

    /**
     *   产品Id
     * @param product_id the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    /**
     *   店铺id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getShop_id() {
        return shop_id;
    }

    /**
     *   店铺id
     * @param shop_id the value for 
     *
     * @MLTH_generated
     */
    public void setShop_id(Long shop_id) {
        this.shop_id = shop_id;
    }

    /**
     *   合伙人id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getPartner_id() {
        return partner_id;
    }

    /**
     *   合伙人id
     * @param partner_id the value for 
     *
     * @MLTH_generated
     */
    public void setPartner_id(Long partner_id) {
        this.partner_id = partner_id;
    }

    /**
     *   品牌id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌id
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     *   创建日期
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCrater_time() {
        return crater_time;
    }

    /**
     *   创建日期
     * @param crater_time the value for 
     *
     * @MLTH_generated
     */
    public void setCrater_time(Date crater_time) {
        this.crater_time = crater_time;
    }

    /**
     *   兑换状态(1:兑换未使用2：兑换已使用使用，)
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getConvert_state() {
        return convert_state;
    }

    /**
     *   兑换状态(1:兑换未使用2：兑换已使用使用，)
     * @param convert_state the value for 
     *
     * @MLTH_generated
     */
    public void setConvert_state(Integer convert_state) {
        this.convert_state = convert_state;
    }

    /**
     *   兑换码（流量：运营商编码+套餐组合id）
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getConvert_code() {
        return convert_code;
    }

    /**
     *   兑换码（流量：运营商编码+套餐组合id）
     * @param convert_code the value for 
     *
     * @MLTH_generated
     */
    public void setConvert_code(String convert_code) {
        this.convert_code = convert_code == null ? null : convert_code.trim();
    }

    /**
     *   兑换方式
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getConvert_type() {
        return convert_type;
    }

    /**
     *   兑换方式
     * @param convert_type the value for 
     *
     * @MLTH_generated
     */
    public void setConvert_type(Integer convert_type) {
        this.convert_type = convert_type;
    }

    /**
     *   兑换日期
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getConvert_time() {
        return convert_time;
    }

    /**
     *   兑换日期
     * @param convert_time the value for 
     *
     * @MLTH_generated
     */
    public void setConvert_time(Date convert_time) {
        this.convert_time = convert_time;
    }

    /**
     *   修改日期
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     *   修改日期
     * @param update_time the value for 
     *
     * @MLTH_generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     *   兑换人
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     *   兑换人
     * @param user_id the value for 
     *
     * @MLTH_generated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     *   兑换积分数
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getConvert_point() {
        return convert_point;
    }

    /**
     *   兑换积分数
     * @param conver_point the value for 
     *
     * @MLTH_generated
     */
    public void setConvert_point(Integer convert_point) {
        this.convert_point = convert_point;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", customer_id=").append(customer_id);
        sb.append(", product_id=").append(product_id);
        sb.append(", shop_id=").append(shop_id);
        sb.append(", partner_id=").append(partner_id);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", crater_time=").append(crater_time);
        sb.append(", convert_state=").append(convert_state);
        sb.append(", convert_code=").append(convert_code);
        sb.append(", convert_type=").append(convert_type);
        sb.append(", convert_time=").append(convert_time);
        sb.append(", update_time=").append(update_time);
        sb.append(", user_id=").append(user_id);
        sb.append(", convert_point=").append(convert_point);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}