package com.mfangsoft.zhuangjialong.integration.pointmall.model;

import java.io.Serializable;
import java.util.List;

/**
 *   流量组合表
 * table t_biz_mall_flow
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseMallFlowEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   产品id
     * column product_id
     *
     * @MLTH_generated
     */
    private Long product_id;

    /**
     *   流量套餐组合id
     * column flow_group_id
     *
     * @MLTH_generated
     */
    private String flow_group_id;
    
    
    private List<BaseFlowPackageEntity> flowPackageEntities;

   

	public List<BaseFlowPackageEntity> getFlowPackageEntities() {
		return flowPackageEntities;
	}

	public void setFlowPackageEntities(List<BaseFlowPackageEntity> flowPackageEntities) {
		this.flowPackageEntities = flowPackageEntities;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_mall_flow
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   产品id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getProduct_id() {
        return product_id;
    }

    /**
     *   产品id
     * @param product_id the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    /**
     *   流量套餐组合id
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getFlow_group_id() {
        return flow_group_id;
    }

    /**
     *   流量套餐组合id
     * @param flow_group_id the value for 
     *
     * @MLTH_generated
     */
    public void setFlow_group_id(String flow_group_id) {
        this.flow_group_id = flow_group_id == null ? null : flow_group_id.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", product_id=").append(product_id);
        sb.append(", flow_group_id=").append(flow_group_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}