package com.mfangsoft.zhuangjialong.integration.shop.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   店面导购信息表
 * table t_app_shop_guider
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class BaseShopGuiderEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   身份证正面URL
     * column idcard_front
     *
     * @MLTH_generated
     */
    private String idcard_front;

    /**
     *   身份证反面URL
     * column idcard_back
     *
     * @MLTH_generated
     */
    private String idcard_back;

    /**
     *   用户手持身份证正面URL
     * column idcard_hold
     *
     * @MLTH_generated
     */
    private String idcard_hold;

    /**
     *   品牌id
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     *   店铺id
     * column shop_id
     *
     * @MLTH_generated
     */
    private Long shop_id;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date create_time;

    /**
     *   更新时间
     * column timestamp
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date timestamp;

    /**
     *   卖家信息id
     * column seller_info_id
     *
     * @MLTH_generated
     */
    private Long seller_info_id;

    /**
     *   创建者id
     * column user_id
     *
     * @MLTH_generated
     */
    private Long user_id;

    /**
     *   认证状态(0:未提交1:审核中2:已认证3:未通过)
     * column certification_state
     *
     * @MLTH_generated
     */
    private Integer certification_state;

    /**
     *   不通过理由
     * column no_pass_reason
     *
     * @MLTH_generated
     */
    private String no_pass_reason;

    /**
     *   是否后台生成的（0:否 1:是）
     * column isgenerate
     *
     * @MLTH_generated
     */
    private Integer isgenerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_app_shop_guider
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   身份证正面URL
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getIdcard_front() {
        return idcard_front;
    }

    /**
     *   身份证正面URL
     * @param idcard_front the value for 
     *
     * @MLTH_generated
     */
    public void setIdcard_front(String idcard_front) {
        this.idcard_front = idcard_front == null ? null : idcard_front.trim();
    }

    /**
     *   身份证反面URL
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getIdcard_back() {
        return idcard_back;
    }

    /**
     *   身份证反面URL
     * @param idcard_back the value for 
     *
     * @MLTH_generated
     */
    public void setIdcard_back(String idcard_back) {
        this.idcard_back = idcard_back == null ? null : idcard_back.trim();
    }

    /**
     *   用户手持身份证正面URL
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getIdcard_hold() {
        return idcard_hold;
    }

    /**
     *   用户手持身份证正面URL
     * @param idcard_hold the value for 
     *
     * @MLTH_generated
     */
    public void setIdcard_hold(String idcard_hold) {
        this.idcard_hold = idcard_hold == null ? null : idcard_hold.trim();
    }

    /**
     *   品牌id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌id
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     *   店铺id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getShop_id() {
        return shop_id;
    }

    /**
     *   店铺id
     * @param shop_id the value for 
     *
     * @MLTH_generated
     */
    public void setShop_id(Long shop_id) {
        this.shop_id = shop_id;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   更新时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     *   更新时间
     * @param timestamp the value for 
     *
     * @MLTH_generated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     *   卖家信息id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSeller_info_id() {
        return seller_info_id;
    }

    /**
     *   卖家信息id
     * @param seller_info_id the value for 
     *
     * @MLTH_generated
     */
    public void setSeller_info_id(Long seller_info_id) {
        this.seller_info_id = seller_info_id;
    }

    /**
     *   创建者id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     *   创建者id
     * @param user_id the value for 
     *
     * @MLTH_generated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     *   认证状态(0:未提交1:审核中2:已认证3:未通过)
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getCertification_state() {
        return certification_state;
    }

    /**
     *   认证状态(0:未提交1:审核中2:已认证3:未通过)
     * @param certification_state the value for 
     *
     * @MLTH_generated
     */
    public void setCertification_state(Integer certification_state) {
        this.certification_state = certification_state;
    }

    /**
     *   不通过理由
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getNo_pass_reason() {
        return no_pass_reason;
    }

    /**
     *   不通过理由
     * @param no_pass_reason the value for 
     *
     * @MLTH_generated
     */
    public void setNo_pass_reason(String no_pass_reason) {
        this.no_pass_reason = no_pass_reason == null ? null : no_pass_reason.trim();
    }

    /**
     *   是否后台生成的（0:否 1:是）
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getIsgenerate() {
        return isgenerate;
    }

    /**
     *   是否后台生成的（0:否 1:是）
     * @param isgenerate the value for 
     *
     * @MLTH_generated
     */
    public void setIsgenerate(Integer isgenerate) {
        this.isgenerate = isgenerate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", idcard_front=").append(idcard_front);
        sb.append(", idcard_back=").append(idcard_back);
        sb.append(", idcard_hold=").append(idcard_hold);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", shop_id=").append(shop_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", timestamp=").append(timestamp);
        sb.append(", seller_info_id=").append(seller_info_id);
        sb.append(", user_id=").append(user_id);
        sb.append(", certification_state=").append(certification_state);
        sb.append(", no_pass_reason=").append(no_pass_reason);
        sb.append(", isgenerate=").append(isgenerate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}