package com.mfangsoft.zhuangjialong.integration.shop.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * table t_biz_employee
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class EmployeeEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   性别
     * column sex
     *
     * @MLTH_generated
     */
    private Integer sex;

    /**
     *   姓名
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     *   联系电话
     * column phone_num
     *
     * @MLTH_generated
     */
    private String phone_num;

    /**
     *   住址
     * column addr
     *
     * @MLTH_generated
     */
    private String addr;

    /**
     *   年龄
     * column age
     *
     * @MLTH_generated
     */
    private Integer age;

    /**
     *   所属店铺Id
     * column shop_id
     *
     * @MLTH_generated
     */
    private Long shop_id;
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date update_time;
    
    public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_employee
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   性别
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     *   性别
     * @param sex the value for 
     *
     * @MLTH_generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     *   姓名
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   姓名
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *   联系电话
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPhone_num() {
        return phone_num;
    }

    /**
     *   联系电话
     * @param phone_num the value for 
     *
     * @MLTH_generated
     */
    public void setPhone_num(String phone_num) {
        this.phone_num = phone_num == null ? null : phone_num.trim();
    }

    /**
     *   住址
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     *   住址
     * @param addr the value for 
     *
     * @MLTH_generated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     *   年龄
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     *   年龄
     * @param age the value for 
     *
     * @MLTH_generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     *   所属店铺Id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getShop_id() {
        return shop_id;
    }

    /**
     *   所属店铺Id
     * @param shop_id the value for 
     *
     * @MLTH_generated
     */
    public void setShop_id(Long shop_id) {
        this.shop_id = shop_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sex=").append(sex);
        sb.append(", name=").append(name);
        sb.append(", phone_num=").append(phone_num);
        sb.append(", addr=").append(addr);
        sb.append(", age=").append(age);
        sb.append(", shop_id=").append(shop_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}