package com.mfangsoft.zhuangjialong.integration.shop.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.mfangsoft.zhuangjialong.integration.bank.model.BankEntity;
import com.mfangsoft.zhuangjialong.integration.brand.model.BrandEntity;
import com.mfangsoft.zhuangjialong.integration.commerce.model.CommerceEntity;
import com.mfangsoft.zhuangjialong.integration.partner.model.PartnerEntity;
import com.mfangsoft.zhuangjialong.integration.user.model.UserEntity;

/**
 * table t_biz_shop
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class ShopEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   店铺名称
     * column shop_name
     *
     * @MLTH_generated
     */
    private String shop_name;

    /**
     *   负责人
     * column principal
     *
     * @MLTH_generated
     */
    private String principal;

    /**
     *   联系电话
     * column phone_num
     *
     * @MLTH_generated
     */
    private String phone_num;

    /**
     *   店铺图片
     * column imgurl
     *
     * @MLTH_generated
     */
    private String imgurl;

    /**
     *   店铺地址
     * column address
     *
     * @MLTH_generated
     */
    private String address;

    /**
     *   经纬度
     * column lbs
     *
     * @MLTH_generated
     */
    private String lbs;

    /**
     *   系统用户id
     * column sys_user_id
     *
     * @MLTH_generated
     */
    private Long sys_user_id;

    /**
     *   品牌id
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;
    
    
     private Map<String,Object>  map= new HashMap<>();
     
     
     private BrandEntity brandEntity;
     
     

     
    
    public BrandEntity getBrandEntity() {
		return brandEntity;
	}

	public void setBrandEntity(BrandEntity brandEntity) {
		this.brandEntity = brandEntity;
	}
	
	
	

	public Map<String, Object> getMap() {
		return map;
	}

	public void setMap(Map<String, Object> map) {
		this.map = map;
	}

	private String enterprise_name;
    
    
    public String getEnterprise_name() {
		return enterprise_name;
	}

	public void setEnterprise_name(String enterprise_name) {
		this.enterprise_name = enterprise_name;
	}

	private String brand_name;

    public String getBrand_name() {
		return brand_name;
	}

	public void setBrand_name(String brand_name) {
		this.brand_name = brand_name;
	}

	/**
     *   工商信息id
     * column commerce_id
     *
     * @MLTH_generated
     */
    private Long commerce_id;

    /**
     *   诚实合伙人id
     * column citypartner_id
     *
     * @MLTH_generated
     */
    private Long citypartner_id;

    /**
     *   区域编码
     * column region_code
     *
     * @MLTH_generated
     */
    private String region_code;

    /**
     *   银行信息id
     * column bank_info_id
     *
     * @MLTH_generated
     */
    private Long bank_info_id;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:MM:ss", timezone="GMT+8")
    private Date create_time;

    /**
     *   修改时间
     * column modify_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:MM:ss", timezone="GMT+8")
    private Date modify_time;

    /**
     *   1：审核中，0：审核通过
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     *   排序号
     * column sort
     *
     * @MLTH_generated
     */
    private Long sort;
    
    
    public UserEntity getUserEntity() {
		return userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	public BankEntity getBankEntity() {
		return bankEntity;
	}

	public void setBankEntity(BankEntity bankEntity) {
		this.bankEntity = bankEntity;
	}

	public CommerceEntity getCommerceEntity() {
		return commerceEntity;
	}

	public void setCommerceEntity(CommerceEntity commerceEntity) {
		this.commerceEntity = commerceEntity;
	}

	private UserEntity userEntity;
    
    
    private BankEntity bankEntity;
    
    
    private CommerceEntity commerceEntity;
    
    
    private PartnerEntity partnerEntity;

    public PartnerEntity getPartnerEntity() {
		return partnerEntity;
	}

	public void setPartnerEntity(PartnerEntity partnerEntity) {
		this.partnerEntity = partnerEntity;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_shop
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   店铺名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getShop_name() {
        return shop_name;
    }

    /**
     *   店铺名称
     * @param shop_name the value for 
     *
     * @MLTH_generated
     */
    public void setShop_name(String shop_name) {
        this.shop_name = shop_name == null ? null : shop_name.trim();
    }

    /**
     *   负责人
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     *   负责人
     * @param principal the value for 
     *
     * @MLTH_generated
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     *   联系电话
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPhone_num() {
        return phone_num;
    }

    /**
     *   联系电话
     * @param phone_num the value for 
     *
     * @MLTH_generated
     */
    public void setPhone_num(String phone_num) {
        this.phone_num = phone_num == null ? null : phone_num.trim();
    }

    /**
     *   店铺图片
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     *   店铺图片
     * @param imgurl the value for 
     *
     * @MLTH_generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     *   店铺地址
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getAddress() {
        return address;
    }

    /**
     *   店铺地址
     * @param address the value for 
     *
     * @MLTH_generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    

    /**
	 * @return the lbs
	 */
	public String getLbs() {
		return lbs;
	}


    /**
	 * @param lbs the lbs to set
	 */
	public void setLbs(String lbs) {
		   this.lbs = lbs == null ? null : lbs.trim();
	}

	/**
     *   系统用户id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSys_user_id() {
        return sys_user_id;
    }

    /**
     *   系统用户id
     * @param sys_user_id the value for 
     *
     * @MLTH_generated
     */
    public void setSys_user_id(Long sys_user_id) {
        this.sys_user_id = sys_user_id;
    }

    /**
     *   品牌id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌id
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     *   工商信息id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCommerce_id() {
        return commerce_id;
    }

    /**
     *   工商信息id
     * @param commerce_id the value for 
     *
     * @MLTH_generated
     */
    public void setCommerce_id(Long commerce_id) {
        this.commerce_id = commerce_id;
    }

    /**
     *   诚实合伙人id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCitypartner_id() {
        return citypartner_id;
    }

    /**
     *   诚实合伙人id
     * @param citypartner_id the value for 
     *
     * @MLTH_generated
     */
    public void setCitypartner_id(Long citypartner_id) {
        this.citypartner_id = citypartner_id;
    }

    /**
     *   区域编码
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getRegion_code() {
        return region_code;
    }

    /**
     *   区域编码
     * @param region_code the value for 
     *
     * @MLTH_generated
     */
    public void setRegion_code(String region_code) {
        this.region_code = region_code == null ? null : region_code.trim();
    }

    /**
     *   银行信息id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBank_info_id() {
        return bank_info_id;
    }

    /**
     *   银行信息id
     * @param bank_info_id the value for 
     *
     * @MLTH_generated
     */
    public void setBank_info_id(Long bank_info_id) {
        this.bank_info_id = bank_info_id;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   修改时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getModify_time() {
        return modify_time;
    }

    /**
     *   修改时间
     * @param modify_time the value for 
     *
     * @MLTH_generated
     */
    public void setModify_time(Date modify_time) {
        this.modify_time = modify_time;
    }

    /**
     *   1：审核中，0：审核通过
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   1：审核中，0：审核通过
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *   排序号
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSort() {
        return sort;
    }

    /**
     *   排序号
     * @param sort the value for 
     *
     * @MLTH_generated
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", shop_name=").append(shop_name);
        sb.append(", principal=").append(principal);
        sb.append(", phone_num=").append(phone_num);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", address=").append(address);
        sb.append(", lbs=").append(lbs);
        sb.append(", sys_user_id=").append(sys_user_id);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", commerce_id=").append(commerce_id);
        sb.append(", citypartner_id=").append(citypartner_id);
        sb.append(", region_code=").append(region_code);
        sb.append(", bank_info_id=").append(bank_info_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", modify_time=").append(modify_time);
        sb.append(", state=").append(state);
        sb.append(", sort=").append(sort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
    
    private double distance;





	/**
	 * @return the distance
	 */
	public double getDistance() {
		return distance;
	}

	/**
	 * @param distance the distance to set
	 */
	public void setDistance(double distance) {
		this.distance = distance;
	}
    
    
}