package com.mfangsoft.zhuangjialong.integration.introduce.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_biz_introduce_class
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class IntroduceClassEntity implements Serializable {
    /**
     *   id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   合伙人
     * column partner_id
     *
     * @MLTH_generated
     */
    private Long partner_id;

    /**
     *   推荐品类
     * column class_id
     *
     * @MLTH_generated
     */
    private Long class_id;
    
    private String class_name;

    /**
     *   推荐产品个数
     * column product_num
     *
     * @MLTH_generated
     */
    private Integer product_num;

    /**
     *   排序
     * column sort
     *
     * @MLTH_generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_introduce_class
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   合伙人
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getPartner_id() {
        return partner_id;
    }

    /**
     *   合伙人
     * @param partner_id the value for 
     *
     * @MLTH_generated
     */
    public void setPartner_id(Long partner_id) {
        this.partner_id = partner_id;
    }

    /**
     *   推荐品类
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getClass_id() {
        return class_id;
    }

    /**
     *   推荐品类
     * @param class_id the value for 
     *
     * @MLTH_generated
     */
    public void setClass_id(Long class_id) {
        this.class_id = class_id;
    }

    /**
     *   推荐产品个数
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getProduct_num() {
        return product_num;
    }

    /**
     *   推荐产品个数
     * @param product_num the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_num(Integer product_num) {
        this.product_num = product_num;
    }

    /**
     *   排序
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     *   排序
     * @param sort the value for 
     *
     * @MLTH_generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public String getClass_name() {
		return class_name;
	}

	public void setClass_name(String class_name) {
		this.class_name = class_name;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", partner_id=").append(partner_id);
        sb.append(", class_id=").append(class_id);
        sb.append(", product_num=").append(product_num);
        sb.append(", sort=").append(sort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}