package com.mfangsoft.zhuangjialong.integration.partner.model;

import java.io.Serializable;

/**
 * table t_biz_open_city
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class OpenCityEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     * column region_code
     *
     * @MLTH_generated
     */
    private String region_code;

    /**
     * column region_name
     *
     * @MLTH_generated
     */
    private String region_name;

    /**
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;
    
    
    private Long partner_id;

    public Long getPartner_id() {
		return partner_id;
	}

	public void setPartner_id(Long partner_id) {
		this.partner_id = partner_id;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_open_city
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getRegion_code() {
        return region_code;
    }

    /**
     * @param region_code the value for 
     *
     * @MLTH_generated
     */
    public void setRegion_code(String region_code) {
        this.region_code = region_code == null ? null : region_code.trim();
    }

    /**
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getRegion_name() {
        return region_name;
    }

    /**
     * @param region_name the value for 
     *
     * @MLTH_generated
     */
    public void setRegion_name(String region_name) {
        this.region_name = region_name == null ? null : region_name.trim();
    }

    /**
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", region_code=").append(region_code);
        sb.append(", region_name=").append(region_name);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}