package com.mfangsoft.zhuangjialong.integration.partner.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.mfangsoft.zhuangjialong.integration.bank.model.BankEntity;
import com.mfangsoft.zhuangjialong.integration.commerce.model.CommerceEntity;
import com.mfangsoft.zhuangjialong.integration.enterprise.model.EnterpriseEntity;
import com.mfangsoft.zhuangjialong.integration.user.model.UserEntity;

/**
 * table t_biz_partner
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class PartnerEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   负责人
     * column principal
     *
     * @MLTH_generated
     */
    private String principal;

    /**
     *   联系方式
     * column phone_num
     *
     * @MLTH_generated
     */
    private String phone_num;

    /**
     *   企业ID
     * column enterprise_id
     *
     * @MLTH_generated
     */
    private Long enterprise_id;
    
    
    private Integer  isglobal;

    public Integer getIsglobal() {
		return isglobal;
	}

	public void setIsglobal(Integer isglobal) {
		this.isglobal = isglobal;
	}

	/**
     *   ID 数组
     * column region_id
     *
     * @MLTH_generated
     */
    private String region_id;

    /**
     *   账号ID
     * column sys_user_id
     *
     * @MLTH_generated
     */
    private Long sys_user_id;

    /**
     *   工商信息表ID
     * column commerce_id
     *
     * @MLTH_generated
     */
    private Long commerce_id;

    /**
     *   银行信息ID
     * column bank_id
     *
     * @MLTH_generated
     */
    private Long bank_id;
    
    
    private CommerceEntity commerceInfo;
    
    private BankEntity bankInfo;

    public CommerceEntity getCommerceInfo() {
		return commerceInfo;
	}

	public void setCommerceInfo(CommerceEntity commerceInfo) {
		this.commerceInfo = commerceInfo;
	}

	public BankEntity getBankInfo() {
		return bankInfo;
	}

	public void setBankInfo(BankEntity bankInfo) {
		this.bankInfo = bankInfo;
	}

	/**
     *   录入人
     * column creater
     *
     * @MLTH_generated
     */
    private Long creater;

    /**
     *   录入时间
     * column create_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date create_time;

    /**
     *   修改时间
     * column update_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date update_time;

    /**
     *   修改人
     * column updater
     *
     * @MLTH_generated
     */
    private Long updater;
    
    
    private String close_time;
    
    
    public String getClose_time() {
		return close_time;
	}

	public void setClose_time(String close_time) {
		this.close_time = close_time;
	}

	private String region_name;
    
    public String getRegion_name() {
		return region_name;
	}

	public void setRegion_name(String region_name) {
		this.region_name = region_name;
	}
	
	private Integer state;
	
	
	private Integer check_state;


	


	public Integer getCheck_state() {
		return check_state;
	}

	public void setCheck_state(Integer check_state) {
		this.check_state = check_state;
	}

	public Integer getState() {
		
		if(userEntity!=null){
			
			this.state = userEntity.getState();
		}
		return state;
	}
	
	private String enterprise_name;
	
	public String getEnterprise_name() {
		
		if(enterpriseEntity!=null){
			this.enterprise_name =enterpriseEntity.getEnterprise_name();
		}
		return enterprise_name;
	}

	private EnterpriseEntity enterpriseEntity;

	public EnterpriseEntity getEnterpriseEntity() {
		return enterpriseEntity;
	}

	public void setEnterpriseEntity(EnterpriseEntity enterpriseEntity) {
		this.enterpriseEntity = enterpriseEntity;
	}

	private String account;
    
    
    public String getAccount() {
    	
    	if(userEntity!=null){
    		
    		this.account = userEntity.getAccount();
    	}
		return account;
	}

	

	private UserEntity userEntity;

    public UserEntity getUserEntity() {
		return userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_partner
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   负责人
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     *   负责人
     * @param principal the value for 
     *
     * @MLTH_generated
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     *   联系方式
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPhone_num() {
        return phone_num;
    }

    /**
     *   联系方式
     * @param phone_num the value for 
     *
     * @MLTH_generated
     */
    public void setPhone_num(String phone_num) {
        this.phone_num = phone_num == null ? null : phone_num.trim();
    }

    /**
     *   企业ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getEnterprise_id() {
        return enterprise_id;
    }

    /**
     *   企业ID
     * @param enterprise_id the value for 
     *
     * @MLTH_generated
     */
    public void setEnterprise_id(Long enterprise_id) {
        this.enterprise_id = enterprise_id;
    }

    /**
     *   ID 数组
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public String getRegion_id() {
        return region_id;
    }

    /**
     *   ID 数组
     * @param region_id the value for 
     *
     * @MLTH_generated
     */
    public void setRegion_id(String region_id) {
        this.region_id = region_id;
    }

    /**
     *   账号ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSys_user_id() {
        return sys_user_id;
    }

    /**
     *   账号ID
     * @param sys_user_id the value for 
     *
     * @MLTH_generated
     */
    public void setSys_user_id(Long sys_user_id) {
        this.sys_user_id = sys_user_id;
    }

    /**
     *   工商信息表ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCommerce_id() {
        return commerce_id;
    }

    /**
     *   工商信息表ID
     * @param commerce_id the value for 
     *
     * @MLTH_generated
     */
    public void setCommerce_id(Long commerce_id) {
        this.commerce_id = commerce_id;
    }

    /**
     *   银行信息ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBank_id() {
        return bank_id;
    }

    /**
     *   银行信息ID
     * @param bank_id the value for 
     *
     * @MLTH_generated
     */
    public void setBank_id(Long bank_id) {
        this.bank_id = bank_id;
    }

    /**
     *   录入人
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public Long getCreater() {
        return creater;
    }

    /**
     *   录入人
     * @param creater the value for 
     *
     * @MLTH_generated
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     *   录入时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   录入时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   修改时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     *   修改时间
     * @param update_time the value for 
     *
     * @MLTH_generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     *   修改人
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     *   修改人
     * @param updater the value for 
     *
     * @MLTH_generated
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", principal=").append(principal);
        sb.append(", phone_num=").append(phone_num);
        sb.append(", enterprise_id=").append(enterprise_id);
        sb.append(", region_id=").append(region_id);
        sb.append(", sys_user_id=").append(sys_user_id);
        sb.append(", commerce_id=").append(commerce_id);
        sb.append(", bank_id=").append(bank_id);
        sb.append(", creater=").append(creater);
        sb.append(", create_time=").append(create_time);
        sb.append(", update_time=").append(update_time);
        sb.append(", updater=").append(updater);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}