package com.mfangsoft.zhuangjialong.integration.series.model;

import java.io.Serializable;

/**
 *   品牌系列表
 * table t_biz_brand_series
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BrandSeriesEntity implements Serializable {
    /**
     *   系列id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   分类id
     * column classify_id
     *
     * @MLTH_generated
     */
    private Long classify_id;

    /**
     *   系列名称
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     *   创建人id
     * column creater
     *
     * @MLTH_generated
     */
    private Long creater;

    /**
     *   排序号
     * column sort
     *
     * @MLTH_generated
     */
    private Integer sort;

    /**
     * column impFlag
     *
     * @MLTH_generated
     */
    private String impFlag;

    /**
     *   是否被推荐（0:否 1:是）
     * column recommended
     *
     * @MLTH_generated
     */
    private Integer recommended;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_brand_series
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   系列id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   系列id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   分类id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getClassify_id() {
        return classify_id;
    }

    /**
     *   分类id
     * @param classify_id the value for 
     *
     * @MLTH_generated
     */
    public void setClassify_id(Long classify_id) {
        this.classify_id = classify_id;
    }

    /**
     *   系列名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   系列名称
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *   创建人id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCreater() {
        return creater;
    }

    /**
     *   创建人id
     * @param creater the value for 
     *
     * @MLTH_generated
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     *   排序号
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     *   排序号
     * @param sort the value for 
     *
     * @MLTH_generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImpFlag() {
        return impFlag;
    }

    /**
     * @param impFlag the value for 
     *
     * @MLTH_generated
     */
    public void setImpFlag(String impFlag) {
        this.impFlag = impFlag == null ? null : impFlag.trim();
    }

    /**
     *   是否被推荐（0:否 1:是）
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getRecommended() {
        return recommended;
    }

    /**
     *   是否被推荐（0:否 1:是）
     * @param recommended the value for 
     *
     * @MLTH_generated
     */
    public void setRecommended(Integer recommended) {
        this.recommended = recommended;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", classify_id=").append(classify_id);
        sb.append(", name=").append(name);
        sb.append(", creater=").append(creater);
        sb.append(", sort=").append(sort);
        sb.append(", impFlag=").append(impFlag);
        sb.append(", recommended=").append(recommended);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}