package com.mfangsoft.zhuangjialong.integration.series.model;

import java.io.Serializable;

/**
 *   企业分类系列表
 * table t_biz_ent_series
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class EntSeriesEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     * column classify_id
     *
     * @MLTH_generated
     */
    private Long classify_id;

    /**
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     * column sort
     *
     * @MLTH_generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_ent_series
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getClassify_id() {
        return classify_id;
    }

    /**
     * @param classify_id the value for 
     *
     * @MLTH_generated
     */
    public void setClassify_id(Long classify_id) {
        this.classify_id = classify_id;
    }

    /**
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * @param sort the value for 
     *
     * @MLTH_generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", classify_id=").append(classify_id);
        sb.append(", name=").append(name);
        sb.append(", sort=").append(sort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}