package com.mfangsoft.zhuangjialong.app.order.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * 订单产品表 table t_biz_order_product
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class OrderProductEntity implements Serializable {
	/**
	 * column id
	 *
	 * @MLTH_generated
	 */
	private Long id;

	/**
	 * 订单id column order_id
	 *
	 * @MLTH_generated
	 */
	private Long order_id;

	/**
	 * 产品id column product_id
	 *
	 * @MLTH_generated
	 */
	private Long product_id;

	/**
	 * 销售属性id column sales_property_id
	 *
	 * @MLTH_generated
	 */
	private Long sales_property_id;

	/**
	 * 购买产品数量 column product_num
	 *
	 * @MLTH_generated
	 */
	private Integer product_num;

	private Integer buy_type;
	
	private String type_value;
	
	private String info;
	
	private String code;
	
	private Double price;
	
	private Double sale_price;
	
	private String coupon_status;
	
	private Integer promotion_type;
	
	private Long promotion_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_biz_order_product
	 *
	 * @MLTH_generated
	 */
	private static final long serialVersionUID = 1L;

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Double getSale_price() {
		return sale_price;
	}

	public void setSale_price(Double sale_price) {
		this.sale_price = sale_price;
	}

	public String getCoupon_status() {
		return coupon_status;
	}

	public void setCoupon_status(String coupon_status) {
		this.coupon_status = coupon_status;
	}

	public Integer getPromotion_type() {
		return promotion_type;
	}

	public void setPromotion_type(Integer promotion_type) {
		this.promotion_type = promotion_type;
	}

	public Long getPromotion_id() {
		return promotion_id;
	}

	public void setPromotion_id(Long promotion_id) {
		this.promotion_id = promotion_id;
	}

	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Integer getBuy_type() {
		return buy_type;
	}

	public void setBuy_type(Integer buy_type) {
		this.buy_type = buy_type;
	}

	public String getType_value() {
		return type_value;
	}

	public void setType_value(String type_value) {
		this.type_value = type_value;
	}

	/**
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * 订单id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getOrder_id() {
		return order_id;
	}

	/**
	 * 订单id
	 * 
	 * @param order_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setOrder_id(Long order_id) {
		this.order_id = order_id;
	}

	/**
	 * 产品id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getProduct_id() {
		return product_id;
	}

	/**
	 * 产品id
	 * 
	 * @param product_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setProduct_id(Long product_id) {
		this.product_id = product_id;
	}

	/**
	 * 销售属性id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getSales_property_id() {
		return sales_property_id;
	}

	/**
	 * 销售属性id
	 * 
	 * @param sales_property_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setSales_property_id(Long sales_property_id) {
		this.sales_property_id = sales_property_id;
	}

	/**
	 * 购买产品数量
	 * 
	 * @return the value of INTEGER
	 *
	 * @MLTH_generated
	 */
	public Integer getProduct_num() {
		return product_num;
	}

	/**
	 * 购买产品数量
	 * 
	 * @param product_num
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setProduct_num(Integer product_num) {
		this.product_num = product_num;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", order_id=").append(order_id);
		sb.append(", product_id=").append(product_id);
		sb.append(", sales_property_id=").append(sales_property_id);
		sb.append(", product_num=").append(product_num);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}