package com.mfangsoft.zhuangjialong.app.order.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * 订单支付表 table t_biz_order_pay
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class OrderPayEntity implements Serializable {
	/**
	 * 订单支付id column id
	 *
	 * @MLTH_generated
	 */
	private Long id;
	
	private String order_code;

	/**
	 * 订单id column order_id
	 *
	 * @MLTH_generated
	 */
	private Long order_id;

	/**
	 * 支付时间 column pay_time
	 *
	 * @MLTH_generated
	 */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	private Date pay_time;

	/**
	 * 1:已支付，2:未支付 column pay_state
	 *
	 * @MLTH_generated
	 */
	private Integer pay_state;

	/**
	 * 交易流水号 column trade_data
	 *
	 * @MLTH_generated
	 */
	private String trade_data;

	/**
	 * 消费者支付id column customer_pay_id
	 *
	 * @MLTH_generated
	 */
	private Integer customer_pay_id;

	private String grouppay_id;

	private boolean isdeposit;
	
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	private Date deposit_time;
	
	private String trade_data_deposit;
	
	private Double deposit_price;
	
	public String getOrder_code() {
		return order_code;
	}

	public void setOrder_code(String order_code) {
		this.order_code = order_code;
	}

	public boolean isIsdeposit() {
		return isdeposit;
	}

	public void setIsdeposit(boolean isdeposit) {
		this.isdeposit = isdeposit;
	}

	public Date getDeposit_time() {
		return deposit_time;
	}

	public void setDeposit_time(Date deposit_time) {
		this.deposit_time = deposit_time;
	}

	public String getTrade_data_deposit() {
		return trade_data_deposit;
	}

	public void setTrade_data_deposit(String trade_data_deposit) {
		this.trade_data_deposit = trade_data_deposit;
	}

	public Double getDeposit_price() {
		return deposit_price;
	}

	public void setDeposit_price(Double deposit_price) {
		this.deposit_price = deposit_price;
	}

	public String getGrouppay_id() {
		return grouppay_id;
	}

	public void setGrouppay_id(String grouppay_id) {
		this.grouppay_id = grouppay_id;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_biz_order_pay
	 *
	 * @MLTH_generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 订单支付id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * 订单支付id
	 * 
	 * @param id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * 订单id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getOrder_id() {
		return order_id;
	}

	/**
	 * 订单id
	 * 
	 * @param order_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setOrder_id(Long order_id) {
		this.order_id = order_id;
	}

	/**
	 * 支付时间
	 * 
	 * @return the value of TIMESTAMP
	 *
	 * @MLTH_generated
	 */
	public Date getPay_time() {
		return pay_time;
	}

	/**
	 * 支付时间
	 * 
	 * @param pay_time
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setPay_time(Date pay_time) {
		this.pay_time = pay_time;
	}

	/**
	 * 1:已支付，2:未支付
	 * 
	 * @return the value of INTEGER
	 *
	 * @MLTH_generated
	 */
	public Integer getPay_state() {
		return pay_state;
	}

	/**
	 * 1:已支付，2:未支付
	 * 
	 * @param pay_state
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setPay_state(Integer pay_state) {
		this.pay_state = pay_state;
	}

	/**
	 * 交易流水号
	 * 
	 * @return the value of VARCHAR
	 *
	 * @MLTH_generated
	 */
	public String getTrade_data() {
		return trade_data;
	}

	/**
	 * 交易流水号
	 * 
	 * @param trade_data
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setTrade_data(String trade_data) {
		this.trade_data = trade_data == null ? null : trade_data.trim();
	}

	/**
	 * 消费者支付id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Integer getCustomer_pay_id() {
		return customer_pay_id;
	}

	/**
	 * 消费者支付id
	 * 
	 * @param customer_pay_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setCustomer_pay_id(Integer customer_pay_id) {
		this.customer_pay_id = customer_pay_id;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", order_id=").append(order_id);
		sb.append(", pay_time=").append(pay_time);
		sb.append(", pay_state=").append(pay_state);
		sb.append(", trade_data=").append(trade_data);
		sb.append(", customer_pay_id=").append(customer_pay_id);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}