package com.mfangsoft.zhuangjialong.app.order.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   虚拟货币订单表
 * table t_biz_order_cash
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class OrderCashEntity implements Serializable {
	
	private String spbill_create_ip;
	private String openid;
    /**
     *   订单id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   订单编码
     * column code
     *
     * @MLTH_generated
     */
    private String code;

    /**
     *   消费者id
     * column customer_id
     *
     * @MLTH_generated
     */
    private Long customer_id;

    /**
     *   联盟活动id
     * column promotion_id
     *
     * @MLTH_generated
     */
    private Long promotion_id;

    /**
     *   订单价格
     * column order_price
     *
     * @MLTH_generated
     */
    private Double order_price;

    /**
     *   推广导购id
     * column exshopper_id
     *
     * @MLTH_generated
     */
    private Long exshopper_id;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date create_time;

    /**
     *   支付时间
     * column pay_time
     *
     * @MLTH_generated
     */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date pay_time;

    /**
     *   1:已支付，2:未支付
     * column pay_state
     *
     * @MLTH_generated
     */
    private Integer pay_state;

    /**
     *   交易流水号
     * column trade_data
     *
     * @MLTH_generated
     */
    private String trade_data;

    /**
     *   1支付宝 2 微信
     * column customer_pay_id
     *
     * @MLTH_generated
     */
    private Integer customer_pay_id;

    private Integer type;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_order_cash
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    public String getSpbill_create_ip() {
		return spbill_create_ip;
	}

	public void setSpbill_create_ip(String spbill_create_ip) {
		this.spbill_create_ip = spbill_create_ip;
	}

	/**
     *   订单id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   订单id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   订单编码
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getCode() {
        return code;
    }

    /**
     *   订单编码
     * @param code the value for 
     *
     * @MLTH_generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     *   消费者id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCustomer_id() {
        return customer_id;
    }

    /**
     *   消费者id
     * @param customer_id the value for 
     *
     * @MLTH_generated
     */
    public void setCustomer_id(Long customer_id) {
        this.customer_id = customer_id;
    }

    /**
     *   联盟活动id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getPromotion_id() {
        return promotion_id;
    }

    /**
     *   联盟活动id
     * @param promotion_id the value for 
     *
     * @MLTH_generated
     */
    public void setPromotion_id(Long promotion_id) {
        this.promotion_id = promotion_id;
    }

    /**
     *   订单价格
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getOrder_price() {
        return order_price;
    }

    /**
     *   订单价格
     * @param order_price the value for 
     *
     * @MLTH_generated
     */
    public void setOrder_price(Double order_price) {
        this.order_price = order_price;
    }

    /**
     *   推广导购id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getExshopper_id() {
        return exshopper_id;
    }

    /**
     *   推广导购id
     * @param exshopper_id the value for 
     *
     * @MLTH_generated
     */
    public void setExshopper_id(Long exshopper_id) {
        this.exshopper_id = exshopper_id;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   支付时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getPay_time() {
        return pay_time;
    }

    /**
     *   支付时间
     * @param pay_time the value for 
     *
     * @MLTH_generated
     */
    public void setPay_time(Date pay_time) {
        this.pay_time = pay_time;
    }

    /**
     *   1:已支付，2:未支付
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getPay_state() {
        return pay_state;
    }

    /**
     *   1:已支付，2:未支付
     * @param pay_state the value for 
     *
     * @MLTH_generated
     */
    public void setPay_state(Integer pay_state) {
        this.pay_state = pay_state;
    }

    /**
     *   交易流水号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getTrade_data() {
        return trade_data;
    }

    /**
     *   交易流水号
     * @param trade_data the value for 
     *
     * @MLTH_generated
     */
    public void setTrade_data(String trade_data) {
        this.trade_data = trade_data == null ? null : trade_data.trim();
    }

    /**
     *   1支付宝 2 微信
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getCustomer_pay_id() {
        return customer_pay_id;
    }

    /**
     *   1支付宝 2 微信
     * @param customer_pay_id the value for 
     *
     * @MLTH_generated
     */
    public void setCustomer_pay_id(Integer customer_pay_id) {
        this.customer_pay_id = customer_pay_id;
    }

    public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
	
    public String getOpenid() {
		return openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", customer_id=").append(customer_id);
        sb.append(", promotion_id=").append(promotion_id);
        sb.append(", order_price=").append(order_price);
        sb.append(", exshopper_id=").append(exshopper_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", pay_time=").append(pay_time);
        sb.append(", pay_state=").append(pay_state);
        sb.append(", trade_data=").append(trade_data);
        sb.append(", customer_pay_id=").append(customer_pay_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}