package com.mfangsoft.zhuangjialong.app.order.model;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.mfangsoft.zhuangjialong.app.applogin.model.CustomerAddress;
import com.mfangsoft.zhuangjialong.app.prepay.model.ShopPrepayEntity;
import com.mfangsoft.zhuangjialong.integration.coupons.model.BrandCouponsEntity;
import com.mfangsoft.zhuangjialong.integration.promotion.model.UnionPromotion;

/**
 * 订单表 table t_biz_order
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class OrderEntity implements Serializable {
	/**
	 * 订单id column id
	 *
	 * @MLTH_generated
	 */
	private Long id;

	/**
	 * 订单编码 column code
	 *
	 * @MLTH_generated
	 */
	private String order_code;

	private String code;

	/**
	 * 消费者id column customer_id
	 *
	 * @MLTH_generated
	 */
	private Long customer_id;

	/**
	 * 店铺id column shop_id
	 *
	 * @MLTH_generated
	 */
	private Long shop_id;
	private String shop_phone_num;
	private String shop_name;
	private Long customer_pay_id;
	private Long[] promotion_id;
	private Long coupons_id;
	private Long redbag_id;
	private Long zhekou_id;
	
	private Integer redbag_type;
	private List<OrderProduct> products;
	private Integer pay_state;
	private Integer order_state_code;
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	private Date pay_time;
	private String trade_data;
	private Integer carriage;
	private List<BrandCouponsEntity> couponsinfo;
	private ShopPrepayEntity shopPrepayEntity;
	private CustomerAddress address;
	// 支付宝 1 还是 微信支付 2
	private Integer paytype;
	private String grouppay_id;
	private OrderTracing tracing;

	private Boolean isdeposit;
	private Double deposit_price;

	// 订单消息需要任意一件商品的第一张图
	private String imgurl;
	private String pushstr;

	private List<BrandCouponsEntity> couponsList;
	private List<BrandCouponsEntity> redbagList;
	private List<BrandCouponsEntity> zhekouList;
	private List<UnionPromotion> unionpropmotionList;
	private String preOrderStr;// 提交订单前奏代号
	
	private Long shell_id;

	/**
	 * 品牌id column brand_id
	 *
	 * @MLTH_generated
	 */
	private Long brand_id;

	/**
	 * 城市合伙人id column citypartner_id
	 *
	 * @MLTH_generated
	 */
	private Long citypartner_id;

	/**
	 * 订单价格 column order_price
	 *
	 * @MLTH_generated
	 */
	private Double order_price;
	
	private Double cut_price;

	/**
	 * 推广导购id column exshopper_id
	 *
	 * @MLTH_generated
	 */
	private Long exshopper_id;

	/**
	 * 区域代码 column region_code
	 *
	 * @MLTH_generated
	 */
	private String region_code;

	/**
	 * 创建时间 column create_time
	 *
	 * @MLTH_generated
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	private Date create_time;

	/**
	 * 消费者地址id column customer_address_id
	 *
	 * @MLTH_generated
	 */
	private String address_details;

	/**
	 * 订单备注 column memo
	 *
	 * @MLTH_generated
	 */
	private String memo;

	private String receiver_name;

	private String phone_num;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_biz_order
	 *
	 * @MLTH_generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 订单id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * 订单id
	 * 
	 * @param id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * 订单编码
	 * 
	 * @return the value of VARCHAR
	 *
	 * @MLTH_generated
	 */
	public String getOrder_code() {
		return order_code;
	}

	public Long[] getPromotion_id() {
		return promotion_id;
	}

	public void setPromotion_id(Long[] promotion_id) {
		this.promotion_id = promotion_id;
	}

	/**
	 * 订单编码
	 * 
	 * @param code
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setOrder_code(String order_code) {
		this.order_code = order_code == null ? null : order_code.trim();
	}

	/**
	 * 消费者id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getCustomer_id() {
		return customer_id;
	}

	/**
	 * 消费者id
	 * 
	 * @param customer_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setCustomer_id(Long customer_id) {
		this.customer_id = customer_id;
	}

	/**
	 * 店铺id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getShop_id() {
		return shop_id;
	}

	/**
	 * 店铺id
	 * 
	 * @param shop_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setShop_id(Long shop_id) {
		this.shop_id = shop_id;
	}

	/**
	 * 品牌id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getBrand_id() {
		return brand_id;
	}

	/**
	 * 品牌id
	 * 
	 * @param brand_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setBrand_id(Long brand_id) {
		this.brand_id = brand_id;
	}

	/**
	 * 城市合伙人id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getCitypartner_id() {
		return citypartner_id;
	}

	/**
	 * 城市合伙人id
	 * 
	 * @param citypartner_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setCitypartner_id(Long citypartner_id) {
		this.citypartner_id = citypartner_id;
	}

	/**
	 * 订单价格
	 * 
	 * @return the value of DOUBLE
	 *
	 * @MLTH_generated
	 */
	public Double getOrder_price() {
		return order_price;
	}

	/**
	 * 订单价格
	 * 
	 * @param order_price
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setOrder_price(Double order_price) {
		this.order_price = order_price;
	}

	/**
	 * 推广导购id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getExshopper_id() {
		return exshopper_id;
	}

	/**
	 * 推广导购id
	 * 
	 * @param exshopper_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setExshopper_id(Long exshopper_id) {
		this.exshopper_id = exshopper_id;
	}

	/**
	 * 区域代码
	 * 
	 * @return the value of VARCHAR
	 *
	 * @MLTH_generated
	 */
	public String getRegion_code() {
		return region_code;
	}

	/**
	 * 区域代码
	 * 
	 * @param region_code
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setRegion_code(String region_code) {
		this.region_code = region_code == null ? null : region_code.trim();
	}

	/**
	 * 创建时间
	 * 
	 * @return the value of TIMESTAMP
	 *
	 * @MLTH_generated
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * 创建时间
	 * 
	 * @param create_time
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public String getAddress_details() {
		return address_details;
	}

	public void setAddress_details(String address_details) {
		this.address_details = address_details;
	}

	public String getReceiver_name() {
		return receiver_name;
	}

	public void setReceiver_name(String receiver_name) {
		this.receiver_name = receiver_name;
	}

	public String getPhone_num() {
		return phone_num;
	}

	public void setPhone_num(String phone_num) {
		this.phone_num = phone_num;
	}

	/**
	 * 订单备注
	 * 
	 * @return the value of LONGVARCHAR
	 *
	 * @MLTH_generated
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * 订单备注
	 * 
	 * @param memo
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}

	public String getShop_name() {
		return shop_name;
	}

	public void setShop_name(String shop_name) {
		this.shop_name = shop_name;
	}

	public Long getCustomer_pay_id() {
		return customer_pay_id;
	}

	public void setCustomer_pay_id(Long customer_pay_id) {
		this.customer_pay_id = customer_pay_id;
	}

	public Long getCoupons_id() {
		return coupons_id;
	}

	public void setCoupons_id(Long coupons_id) {
		this.coupons_id = coupons_id;
	}

	public Long getRedbag_id() {
		return redbag_id;
	}

	public void setRedbag_id(Long redbag_id) {
		this.redbag_id = redbag_id;
	}

	public List<OrderProduct> getProducts() {
		return products;
	}

	public void setProducts(List<OrderProduct> products) {
		this.products = products;
	}

	public Integer getPay_state() {
		return pay_state;
	}

	public void setPay_state(Integer pay_state) {
		this.pay_state = pay_state;
	}

	public Integer getOrder_state_code() {
		return order_state_code;
	}

	public void setOrder_state_code(Integer order_state_code) {
		this.order_state_code = order_state_code;
	}

	public Date getPay_time() {
		return pay_time;
	}

	public void setPay_time(Date pay_time) {
		this.pay_time = pay_time;
	}

	public String getTrade_data() {
		return trade_data;
	}

	public void setTrade_data(String trade_data) {
		this.trade_data = trade_data;
	}

	public List<BrandCouponsEntity> getCouponsinfo() {
		return couponsinfo;
	}

	public void setCouponsinfo(List<BrandCouponsEntity> couponsinfo) {
		this.couponsinfo = couponsinfo;
	}

	public CustomerAddress getAddress() {
		return address;
	}

	public void setAddress(CustomerAddress address) {
		this.address = address;
	}

	public Integer getCarriage() {
		return carriage;
	}

	public void setCarriage(Integer carriage) {
		this.carriage = carriage;
	}

	public List<BrandCouponsEntity> getCouponsList() {
		return couponsList;
	}

	public void setCouponsList(List<BrandCouponsEntity> couponsList) {
		this.couponsList = couponsList;
	}

	public List<BrandCouponsEntity> getRedbagList() {
		return redbagList;
	}

	public void setRedbagList(List<BrandCouponsEntity> redbagList) {
		this.redbagList = redbagList;
	}

	public String getPushstr() {
		return pushstr;
	}

	public void setPushstr(String pushstr) {
		this.pushstr = pushstr;
	}

	public String getImgurl() {
		return imgurl;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	public OrderTracing getTracing() {
		return tracing;
	}

	public void setTracing(OrderTracing tracing) {
		this.tracing = tracing;
	}

	public String getShop_phone_num() {
		return shop_phone_num;
	}

	public void setShop_phone_num(String shop_phone_num) {
		this.shop_phone_num = shop_phone_num;
	}

	public Integer getPaytype() {
		return paytype;
	}

	public void setPaytype(Integer paytype) {
		this.paytype = paytype;
	}

	public String getGrouppay_id() {
		return grouppay_id;
	}

	public void setGrouppay_id(String grouppay_id) {
		this.grouppay_id = grouppay_id;
	}

	public Boolean getIsdeposit() {
		return isdeposit;
	}

	public void setIsdeposit(Boolean isdeposit) {
		this.isdeposit = isdeposit;
	}

	public Double getDeposit_price() {
		return deposit_price;
	}

	public void setDeposit_price(Double deposit_price) {
		this.deposit_price = deposit_price;
	}

	public Integer getRedbag_type() {
		return redbag_type;
	}

	public void setRedbag_type(Integer redbag_type) {
		this.redbag_type = redbag_type;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getPreOrderStr() {
		return preOrderStr;
	}

	public void setPreOrderStr(String preOrderStr) {
		this.preOrderStr = preOrderStr;
	}

	public Long getShell_id() {
		return shell_id;
	}

	public void setShell_id(Long shell_id) {
		this.shell_id = shell_id;
	}

	public Long getZhekou_id() {
		return zhekou_id;
	}

	public void setZhekou_id(Long zhekou_id) {
		this.zhekou_id = zhekou_id;
	}

	public Double getCut_price() {
		return cut_price;
	}

	public void setCut_price(Double cut_price) {
		this.cut_price = cut_price;
	}

	public List<UnionPromotion> getUnionpropmotionList() {
		return unionpropmotionList;
	}

	public void setUnionpropmotionList(List<UnionPromotion> unionpropmotionList) {
		this.unionpropmotionList = unionpropmotionList;
	}

	public List<BrandCouponsEntity> getZhekouList() {
		return zhekouList;
	}

	public void setZhekouList(List<BrandCouponsEntity> zhekouList) {
		this.zhekouList = zhekouList;
	}

	public ShopPrepayEntity getShopPrepayEntity() {
		return shopPrepayEntity;
	}

	public void setShopPrepayEntity(ShopPrepayEntity shopPrepayEntity) {
		this.shopPrepayEntity = shopPrepayEntity;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", code=").append(order_code);
		sb.append(", customer_id=").append(customer_id);
		sb.append(", shop_id=").append(shop_id);
		sb.append(", brand_id=").append(brand_id);
		sb.append(", citypartner_id=").append(citypartner_id);
		sb.append(", order_price=").append(order_price);
		sb.append(", exshopper_id=").append(exshopper_id);
		sb.append(", region_code=").append(region_code);
		sb.append(", create_time=").append(create_time);
		sb.append(", memo=").append(memo);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}