package com.mfangsoft.zhuangjialong.app.order.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * 订单状态关系表 table t_biz_order_state_relation
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class OrderStateRelationEntity implements Serializable {
	/**
	 * 主键 column id
	 *
	 * @MLTH_generated
	 */
	private Long id;
	
	private String order_code;

	/**
	 * 订单id column order_id
	 *
	 * @MLTH_generated
	 */
	private Long order_id;

	/**
	 * 订单状态编码 column order_state_code
	 *
	 * @MLTH_generated
	 */
	private Integer order_state_code;

	/**
	 * 状态时间 column time
	 *
	 * @MLTH_generated
	 */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	private Date time;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_biz_order_state_relation
	 *
	 * @MLTH_generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 主键
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * 主键
	 * 
	 * @param id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	public String getOrder_code() {
		return order_code;
	}

	public void setOrder_code(String order_code) {
		this.order_code = order_code;
	}

	/**
	 * 订单id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getOrder_id() {
		return order_id;
	}

	/**
	 * 订单id
	 * 
	 * @param order_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setOrder_id(Long order_id) {
		this.order_id = order_id;
	}

	/**
	 * 订单状态编码
	 * 
	 * @return the value of INTEGER
	 *
	 * @MLTH_generated
	 */
	public Integer getOrder_state_code() {
		return order_state_code;
	}

	/**
	 * 订单状态编码
	 * 
	 * @param order_state_code
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setOrder_state_code(Integer order_state_code) {
		this.order_state_code = order_state_code;
	}

	/**
	 * 状态时间
	 * 
	 * @return the value of TIMESTAMP
	 *
	 * @MLTH_generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * 状态时间
	 * 
	 * @param time
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", order_id=").append(order_id);
		sb.append(", order_state_code=").append(order_state_code);
		sb.append(", time=").append(time);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}