package com.mfangsoft.zhuangjialong.app.order.model;

import java.io.Serializable;

/**
 * 订单优惠表 table t_biz_order_coupons
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class OrderCouponsEntity implements Serializable {
	/**
	 * column id
	 *
	 * @MLTH_generated
	 */
	private Long id;

	/**
	 * 订单id column order_id
	 *
	 * @MLTH_generated
	 */
	private Long order_id;

	/**
	 * 优惠券id column coupons_id
	 *
	 * @MLTH_generated
	 */
	private Long coupons_id;

	/**
	 * 红包id column redbag_id
	 *
	 * @MLTH_generated
	 */
	private Long redbag_id;

	/**
	 * 红包id column redbag_id
	 *
	 * @MLTH_generated
	 */
	private String promotion_id;
	
	private Long zhekou_id;
	
	private Long pershop_id;

	private Integer shop_cash_id;
	
	private Long customer_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_biz_order_coupons
	 *
	 * @MLTH_generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * 订单id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getOrder_id() {
		return order_id;
	}

	/**
	 * 订单id
	 * 
	 * @param order_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setOrder_id(Long order_id) {
		this.order_id = order_id;
	}

	/**
	 * 优惠券id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getCoupons_id() {
		return coupons_id;
	}

	/**
	 * 优惠券id
	 * 
	 * @param coupons_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setCoupons_id(Long coupons_id) {
		this.coupons_id = coupons_id;
	}

	/**
	 * 红包id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getRedbag_id() {
		return redbag_id;
	}

	/**
	 * 红包id
	 * 
	 * @param redbag_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setRedbag_id(Long redbag_id) {
		this.redbag_id = redbag_id;
	}

	public String getPromotion_id() {
		return promotion_id;
	}

	public void setPromotion_id(String promotion_id) {
		this.promotion_id = promotion_id;
	}

	public Integer getShop_cash_id() {
		return shop_cash_id;
	}

	public void setShop_cash_id(Integer shop_cash_id) {
		this.shop_cash_id = shop_cash_id;
	}

	public Long getCustomer_id() {
		return customer_id;
	}

	public void setCustomer_id(Long customer_id) {
		this.customer_id = customer_id;
	}

	public Long getZhekou_id() {
		return zhekou_id;
	}

	public void setZhekou_id(Long zhekou_id) {
		this.zhekou_id = zhekou_id;
	}

	public Long getPershop_id() {
		return pershop_id;
	}

	public void setPershop_id(Long pershop_id) {
		this.pershop_id = pershop_id;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", order_id=").append(order_id);
		sb.append(", coupons_id=").append(coupons_id);
		sb.append(", redbag_id=").append(redbag_id);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}