package com.mfangsoft.zhuangjialong.app.order.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   卖家端收支明细表
 * table t_biz_seller_balance_detail
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class SellerBalanceDetailEntity implements Serializable {
    /**
     *   主键id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   收支方式(1收；2支）
     * column type
     *
     * @MLTH_generated
     */
    private Integer type;

    /**
     *   收支资金
     * column amount
     *
     * @MLTH_generated
     */
    private Double amount;

    /**
     *   导购/施工人员id
     * column seller_id
     *
     * @MLTH_generated
     */
    private Long seller_id;

    /**
     *   日期
     * column create_time
     *
     * @MLTH_generated
     */
    private Date create_time;

    /**
     *   订单id
     * column order_id
     *
     * @MLTH_generated
     */
    private Long order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_seller_balance_detail
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   收支方式(1收；2支）
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getType() {
        return type;
    }

    /**
     *   收支方式(1收；2支）
     * @param type the value for 
     *
     * @MLTH_generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     *   收支资金
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     *   收支资金
     * @param amount the value for 
     *
     * @MLTH_generated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     *   导购/施工人员id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSeller_id() {
        return seller_id;
    }

    /**
     *   导购/施工人员id
     * @param seller_id the value for 
     *
     * @MLTH_generated
     */
    public void setSeller_id(Long seller_id) {
        this.seller_id = seller_id;
    }

    /**
     *   日期
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   日期
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   订单id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getOrder_id() {
        return order_id;
    }

    /**
     *   订单id
     * @param order_id the value for 
     *
     * @MLTH_generated
     */
    public void setOrder_id(Long order_id) {
        this.order_id = order_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", amount=").append(amount);
        sb.append(", seller_id=").append(seller_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", order_id=").append(order_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}