package com.mfangsoft.zhuangjialong.integration.bank.model;

import java.io.Serializable;

/**
 *    银行信息
 * table t_biz_bank
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BankEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   银行账户
     * column account
     *
     * @MLTH_generated
     */
    private String account;

    /**
     *   开户行
     * column addr
     *
     * @MLTH_generated
     */
    private String addr;

    /**
     *   账户名称
     * column name
     *
     * @MLTH_generated
     */
    private String name;
    
    
    private String pay_account;
    
    private String webkit_account;

    public String getWebkit_account() {
		return webkit_account;
	}

	public void setWebkit_account(String webkit_account) {
		this.webkit_account = webkit_account;
	}

	public String getPay_account() {
		return pay_account;
	}

	public void setPay_account(String pay_account) {
		this.pay_account = pay_account;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_bank
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   银行账户
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getAccount() {
        return account;
    }

    /**
     *   银行账户
     * @param account the value for 
     *
     * @MLTH_generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     *   开户行
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     *   开户行
     * @param addr the value for 
     *
     * @MLTH_generated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     *   账户名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   账户名称
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", addr=").append(addr);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}