package com.mfangsoft.zhuangjialong.app.cart.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * 购物车表 table t_biz_cart
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class CartEntity implements Serializable {
	
	private String region_code;
	/**
	 * 购物车id column id
	 *
	 * @MLTH_generated
	 */
	private Long id;

	/**
	 * 消费者id column customer_id
	 *
	 * @MLTH_generated
	 */
	private Long customer_id;

	/**
	 * 产品id column product_id
	 *
	 * @MLTH_generated
	 */
	private Long product_id;

	/**
	 * 店铺id column shop_id
	 *
	 * @MLTH_generated
	 */
	private Long shop_id;

	/**
	 * 购买数量 column num
	 *
	 * @MLTH_generated
	 */
	private Integer num;

	/**
	 * 销售属性id column sales_property_id
	 *
	 * @MLTH_generated
	 */
	private Long sales_property_id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_biz_cart
	 *
	 * @MLTH_generated
	 */
	private static final long serialVersionUID = 1L;

	public String getRegion_code() {
		return region_code;
	}

	public void setRegion_code(String region_code) {
		this.region_code = region_code;
	}

	/**
	 * 购物车id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * 购物车id
	 * 
	 * @param id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * 消费者id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getCustomer_id() {
		return customer_id;
	}

	/**
	 * 消费者id
	 * 
	 * @param customer_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setCustomer_id(Long customer_id) {
		this.customer_id = customer_id;
	}

	/**
	 * 产品id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getProduct_id() {
		return product_id;
	}

	/**
	 * 产品id
	 * 
	 * @param product_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setProduct_id(Long product_id) {
		this.product_id = product_id;
	}

	/**
	 * 店铺id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getShop_id() {
		return shop_id;
	}

	/**
	 * 店铺id
	 * 
	 * @param shop_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setShop_id(Long shop_id) {
		this.shop_id = shop_id;
	}

	/**
	 * 购买数量
	 * 
	 * @return the value of INTEGER
	 *
	 * @MLTH_generated
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * 购买数量
	 * 
	 * @param num
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * 销售属性id
	 * 
	 * @return the value of BIGINT
	 *
	 * @MLTH_generated
	 */
	public Long getSales_property_id() {
		return sales_property_id;
	}

	/**
	 * 销售属性id
	 * 
	 * @param sales_property_id
	 *            the value for
	 *
	 * @MLTH_generated
	 */
	public void setSales_property_id(Long sales_property_id) {
		this.sales_property_id = sales_property_id;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", customer_id=").append(customer_id);
		sb.append(", product_id=").append(product_id);
		sb.append(", shop_id=").append(shop_id);
		sb.append(", num=").append(num);
		sb.append(", sales_property_id=").append(sales_property_id);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}