package com.mfangsoft.zhuangjialong.app.headline.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   头条列表
 * table t_biz_head_line
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class HeadLineEntity implements Serializable {
    /**
     *   头条id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   编辑时间
     * column edit_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GTM+8")
    private Date edit_time;

    /**
     *   发布时间
     * column release_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GTM+8")
    private Date release_time;

    /**
     *   头条标题
     * column title
     *
     * @MLTH_generated
     */
    private String title;

    /**
     *   1：已发布；2：已过期
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     *   结束时间
     * column end_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GTM+8")
    private Date end_time;

    /**
     *   创建人
     * column creater
     *
     * @MLTH_generated
     */
    private String creater;

    /**
     *   链接地址
     * column link
     *
     * @MLTH_generated
     */
    private String link;

    /**
     *   图片URL
     * column imgurl
     *
     * @MLTH_generated
     */
    private String imgurl;

    /**
     *   1、最新，2、推荐
     * column tag
     *
     * @MLTH_generated
     */
    private Integer tag;

    /**
     *   0、链接
     * column link_type
     *
     * @MLTH_generated
     */
    private Integer link_type;

    /**
     *   参数
     * column title
     *
     * @MLTH_generated
     */
    private String data_param;
    
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_head_line
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   头条id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   头条id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   编辑时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getEdit_time() {
        return edit_time;
    }

    /**
     *   编辑时间
     * @param edit_time the value for 
     *
     * @MLTH_generated
     */
    public void setEdit_time(Date edit_time) {
        this.edit_time = edit_time;
    }

    /**
     *   发布时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getRelease_time() {
        return release_time;
    }

    /**
     *   发布时间
     * @param release_time the value for 
     *
     * @MLTH_generated
     */
    public void setRelease_time(Date release_time) {
        this.release_time = release_time;
    }

    /**
     *   头条标题
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getTitle() {
        return title;
    }

    /**
     *   头条标题
     * @param title the value for 
     *
     * @MLTH_generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     *   1：已发布；2：已过期
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   1：已发布；2：已过期
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *   结束时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     *   结束时间
     * @param end_time the value for 
     *
     * @MLTH_generated
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     *   创建人
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getCreater() {
        return creater;
    }

    /**
     *   创建人
     * @param creater the value for 
     *
     * @MLTH_generated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     *   链接地址
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getLink() {
        return link;
    }

    /**
     *   链接地址
     * @param link the value for 
     *
     * @MLTH_generated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }
   
    /**
	 * @return the data_param
	 */
	public String getData_param() {
		return data_param;
	}

	/**
	 * @param data_param the data_param to set
	 */
	public void setData_param(String data_param) {
		this.data_param = data_param== null ? null : data_param.trim();
	}

	/**
     *   图片URL
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     *   图片URL
     * @param imgurl the value for 
     *
     * @MLTH_generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     *   1、最新，2、推荐
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getTag() {
        return tag;
    }

    /**
     *   1、最新，2、推荐
     * @param tag the value for 
     *
     * @MLTH_generated
     */
    public void setTag(Integer tag) {
        this.tag = tag;
    }

    /**
     *   0、链接
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getLink_type() {
        return link_type;
    }

    /**
     *   0、链接
     * @param link_type the value for 
     *
     * @MLTH_generated
     */
    public void setLink_type(Integer link_type) {
        this.link_type = link_type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", edit_time=").append(edit_time);
        sb.append(", release_time=").append(release_time);
        sb.append(", title=").append(title);
        sb.append(", state=").append(state);
        sb.append(", end_time=").append(end_time);
        sb.append(", creater=").append(creater);
        sb.append(", link=").append(link);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", tag=").append(tag);
        sb.append(", link_type=").append(link_type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}