package com.mfangsoft.zhuangjialong.app.seller.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   卖家端用户
 * table t_app_seller
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class SellerEntity implements Serializable {
    /**
     *   主键id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   账号
     * column account
     *
     * @MLTH_generated
     */
    private String account;

    /**
     *   密码
     * column password
     *
     * @MLTH_generated
     */
    private String password;

    /**
     *   1：推广员2：推广导购员 3：施工人员4：店面导购
     * column seller_type
     *
     * @MLTH_generated
     */
    private Integer seller_type;

    /**
     *   联系方式
     * column phone
     *
     * @MLTH_generated
     */
    private String phone;

    /**
     *   头像
     * column head_img
     *
     * @MLTH_generated
     */
    private String head_img;

    /**
     *   0：禁用 1：可用
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date create_time;

    /**
     *   姓名
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     *   邀请码
     * column invite_code
     *
     * @MLTH_generated
     */
    private String invite_code;

    /**
     *   城市合伙人
     * column partner_id
     *
     * @MLTH_generated
     */
    private Long partner_id;
/**
 * 上次打开推广订单时间
 */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date view_orders_time;
/**
 * 上次打开推广用户列表时间
 */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date view_tuiguang_time;
    
    /**
     * 上次打开施工列表时间
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
        private Date view_shigong_time;
        /**
         * 手机验证码
         */
        private String vCode;
        private Long expand_id;
        
    	private Integer byExpandCustomerCount;

	public Integer getByExpandCustomerCount() {
			return byExpandCustomerCount;
		}

		public void setByExpandCustomerCount(Integer byExpandCustomerCount) {
			this.byExpandCustomerCount = byExpandCustomerCount;
		}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_app_seller
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    public Date getView_shigong_time() {
		return view_shigong_time;
	}

	public void setView_shigong_time(Date view_shigong_time) {
		this.view_shigong_time = view_shigong_time;
	}

	/**
     *   主键id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   账号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getAccount() {
        return account;
    }

    /**
     *   账号
     * @param account the value for 
     *
     * @MLTH_generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     *   密码
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPassword() {
        return password;
    }

    /**
     *   密码
     * @param password the value for 
     *
     * @MLTH_generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     *   1：推广员2：推广导购员 3：施工人员4：店面导购
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSeller_type() {
        return seller_type;
    }

    /**
     *   1：推广员2：推广导购员 3：施工人员4：店面导购
     * @param seller_type the value for 
     *
     * @MLTH_generated
     */
    public void setSeller_type(Integer seller_type) {
        this.seller_type = seller_type;
    }

    /**
     *   联系方式
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     *   联系方式
     * @param phone the value for 
     *
     * @MLTH_generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     *   头像
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getHead_img() {
        return head_img;
    }

    /**
     *   头像
     * @param head_img the value for 
     *
     * @MLTH_generated
     */
    public void setHead_img(String head_img) {
        this.head_img = head_img == null ? null : head_img.trim();
    }

    /**
     *   0：禁用 1：可用
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   0：禁用 1：可用
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   姓名
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   姓名
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *   邀请码
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getInvite_code() {
        return invite_code;
    }

    /**
     *   邀请码
     * @param invite_code the value for 
     *
     * @MLTH_generated
     */
    public void setInvite_code(String invite_code) {
        this.invite_code = invite_code == null ? null : invite_code.trim();
    }

    /**
     *   城市合伙人
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getPartner_id() {
        return partner_id;
    }

    /**
     *   城市合伙人
     * @param partner_id the value for 
     *
     * @MLTH_generated
     */
    public void setPartner_id(Long partner_id) {
        this.partner_id = partner_id;
    }

    public Date getView_orders_time() {
		return view_orders_time;
	}

	public void setView_orders_time(Date view_orders_time) {
		this.view_orders_time = view_orders_time;
	}

	public Date getView_tuiguang_time() {
		return view_tuiguang_time;
	}

	public void setView_tuiguang_time(Date view_tuiguang_time) {
		this.view_tuiguang_time = view_tuiguang_time;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", password=").append(password);
        sb.append(", seller_type=").append(seller_type);
        sb.append(", phone=").append(phone);
        sb.append(", head_img=").append(head_img);
        sb.append(", state=").append(state);
        sb.append(", create_time=").append(create_time);
        sb.append(", name=").append(name);
        sb.append(", invite_code=").append(invite_code);
        sb.append(", partner_id=").append(partner_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

	public String getvCode() {
		return vCode;
	}

	public void setvCode(String vCode) {
		this.vCode = vCode;
	}

	public Long getExpand_id() {
		return expand_id;
	}

	public void setExpand_id(Long expand_id) {
		this.expand_id = expand_id;
	}
}