package com.mfangsoft.zhuangjialong.app.seller.model;

import java.io.Serializable;
import java.util.Date;

/**
 * table t_biz_seller_balance_apply
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class SellerBalanceApplyEntity implements Serializable {
	
	private String phone;
	private String vcode;
	
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   施工 导购id
     * column seller_id
     *
     * @MLTH_generated
     */
    private Long seller_id;

    /**
     *   提取钱数
     * column amount
     *
     * @MLTH_generated
     */
    private Double amount;

    /**
     *   申请状态 0待处理 1已处理
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     *   处理人id
     * column user_id
     *
     * @MLTH_generated
     */
    private Long user_id;

    /**
     *   申请时间
     * column create_time
     *
     * @MLTH_generated
     */
    private Date create_time;

    /**
     *   注解
     * column comment
     *
     * @MLTH_generated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_seller_balance_apply
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    public String getVcode() {
		return vcode;
	}

	public void setVcode(String vcode) {
		this.vcode = vcode;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
     *   主键
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   施工 导购id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSeller_id() {
        return seller_id;
    }

    /**
     *   施工 导购id
     * @param seller_id the value for 
     *
     * @MLTH_generated
     */
    public void setSeller_id(Long seller_id) {
        this.seller_id = seller_id;
    }

    /**
     *   提取钱数
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     *   提取钱数
     * @param amount the value for 
     *
     * @MLTH_generated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     *   申请状态 0待处理 1已处理
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   申请状态 0待处理 1已处理
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *   处理人id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     *   处理人id
     * @param user_id the value for 
     *
     * @MLTH_generated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     *   申请时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   申请时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   注解
     * @return the value of LONGVARCHAR
     *
     * @MLTH_generated
     */
    public String getComment() {
        return comment;
    }

    /**
     *   注解
     * @param comment the value for 
     *
     * @MLTH_generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", seller_id=").append(seller_id);
        sb.append(", amount=").append(amount);
        sb.append(", state=").append(state);
        sb.append(", user_id=").append(user_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", comment=").append(comment);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}