package com.mfangsoft.zhuangjialong.app.seller.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   施工信息表
 * table t_app_sell_construct_info
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class SellerConstructInfoEntity implements Serializable {
	
	private Long seller_id;
    /**
     *   主键id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   身份证正面URL
     * column idcard_front
     *
     * @MLTH_generated
     */
    private String idcard_front;

    /**
     *   身份证反面URL
     * column idcard_back
     *
     * @MLTH_generated
     */
    private String idcard_back;

    /**
     *   资质URL1
     * column qualification_one
     *
     * @MLTH_generated
     */
    private String qualification_one;

    /**
     *   资质URL2
     * column qualification_two
     *
     * @MLTH_generated
     */
    private String qualification_two;

    /**
     *   资质URL3
     * column qualification_three
     *
     * @MLTH_generated
     */
    private String qualification_three;

    /**
     *   用户手持身份证正面URL
     * column idcard_hold
     *
     * @MLTH_generated
     */
    private String idcard_hold;

    /**
     *   服务范围
     * column service_region
     *
     * @MLTH_generated
     */
    private String service_region;

    /**
     *   施工简介
     * column construct_about
     *
     * @MLTH_generated
     */
    private String construct_about;

    /**
     *   服务类型
     * column service_code
     *
     * @MLTH_generated
     */
    private String service_code;

    /**
     *   施工单价
     * column unit_price
     *
     * @MLTH_generated
     */
    private Double unit_price;
    
    private String unit_name;

    /**
     *   区域编码
     * column region_code
     *
     * @MLTH_generated
     */
    private String region_code;

    /**
     *   详细地址
     * column address_details
     *
     * @MLTH_generated
     */
    private String address_details;

    /**
     *   是否认证（0否，1是）
     * column certification_state
     *
     * @MLTH_generated
     */
    private Integer certification_state;

    /**
     *   施工队名称
     * column team_name
     *
     * @MLTH_generated
     */
    private String team_name;

    private Integer break_off_state;
    
    private String info;
    
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date updatetime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_app_sell_construct_info
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   身份证正面URL
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getIdcard_front() {
        return idcard_front;
    }

    /**
     *   身份证正面URL
     * @param idcard_front the value for 
     *
     * @MLTH_generated
     */
    public void setIdcard_front(String idcard_front) {
        this.idcard_front = idcard_front == null ? null : idcard_front.trim();
    }

    /**
     *   身份证反面URL
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getIdcard_back() {
        return idcard_back;
    }

    /**
     *   身份证反面URL
     * @param idcard_back the value for 
     *
     * @MLTH_generated
     */
    public void setIdcard_back(String idcard_back) {
        this.idcard_back = idcard_back == null ? null : idcard_back.trim();
    }

    /**
     *   资质URL1
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getQualification_one() {
        return qualification_one;
    }

    /**
     *   资质URL1
     * @param qualification_one the value for 
     *
     * @MLTH_generated
     */
    public void setQualification_one(String qualification_one) {
        this.qualification_one = qualification_one == null ? null : qualification_one.trim();
    }

    /**
     *   资质URL2
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getQualification_two() {
        return qualification_two;
    }

    /**
     *   资质URL2
     * @param qualification_two the value for 
     *
     * @MLTH_generated
     */
    public void setQualification_two(String qualification_two) {
        this.qualification_two = qualification_two == null ? null : qualification_two.trim();
    }

    /**
     *   资质URL3
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getQualification_three() {
        return qualification_three;
    }

    /**
     *   资质URL3
     * @param qualification_three the value for 
     *
     * @MLTH_generated
     */
    public void setQualification_three(String qualification_three) {
        this.qualification_three = qualification_three == null ? null : qualification_three.trim();
    }

    /**
     *   用户手持身份证正面URL
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getIdcard_hold() {
        return idcard_hold;
    }

    /**
     *   用户手持身份证正面URL
     * @param idcard_hold the value for 
     *
     * @MLTH_generated
     */
    public void setIdcard_hold(String idcard_hold) {
        this.idcard_hold = idcard_hold == null ? null : idcard_hold.trim();
    }

    /**
     *   服务范围
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getService_region() {
        return service_region;
    }

    /**
     *   服务范围
     * @param service_region the value for 
     *
     * @MLTH_generated
     */
    public void setService_region(String service_region) {
        this.service_region = service_region == null ? null : service_region.trim();
    }

    /**
     *   施工简介
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getConstruct_about() {
        return construct_about;
    }

    /**
     *   施工简介
     * @param construct_about the value for 
     *
     * @MLTH_generated
     */
    public void setConstruct_about(String construct_about) {
        this.construct_about = construct_about == null ? null : construct_about.trim();
    }

    /**
     *   服务类型
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getService_code() {
        return service_code;
    }

    /**
     *   服务类型
     * @param service_code the value for 
     *
     * @MLTH_generated
     */
    public void setService_code(String service_code) {
        this.service_code = service_code == null ? null : service_code.trim();
    }

    /**
     *   施工单价
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getUnit_price() {
        return unit_price;
    }

    /**
     *   施工单价
     * @param unit_price the value for 
     *
     * @MLTH_generated
     */
    public void setUnit_price(Double unit_price) {
        this.unit_price = unit_price;
    }

    /**
     *   区域编码
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getRegion_code() {
        return region_code;
    }

    /**
     *   区域编码
     * @param region_code the value for 
     *
     * @MLTH_generated
     */
    public void setRegion_code(String region_code) {
        this.region_code = region_code == null ? null : region_code.trim();
    }

    /**
     *   详细地址
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getAddress_details() {
        return address_details;
    }

    /**
     *   详细地址
     * @param address_details the value for 
     *
     * @MLTH_generated
     */
    public void setAddress_details(String address_details) {
        this.address_details = address_details == null ? null : address_details.trim();
    }

    /**
     *   是否认证（0否，1是）
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getCertification_state() {
        return certification_state;
    }

    /**
     *   是否认证（0否，1是）
     * @param certification_state the value for 
     *
     * @MLTH_generated
     */
    public void setCertification_state(Integer certification_state) {
        this.certification_state = certification_state;
    }

    /**
     *   施工队名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getTeam_name() {
        return team_name;
    }

    /**
     *   施工队名称
     * @param team_name the value for 
     *
     * @MLTH_generated
     */
    public void setTeam_name(String team_name) {
        this.team_name = team_name == null ? null : team_name.trim();
    }

    public Long getSeller_id() {
		return seller_id;
	}

	public void setSeller_id(Long seller_id) {
		this.seller_id = seller_id;
	}

	public String getUnit_name() {
		return unit_name;
	}

	public void setUnit_name(String unit_name) {
		this.unit_name = unit_name;
	}

	public Integer getBreak_off_state() {
		return break_off_state;
	}

	public void setBreak_off_state(Integer break_off_state) {
		this.break_off_state = break_off_state;
	}

	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Date getUpdatetime() {
		return updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", idcard_front=").append(idcard_front);
        sb.append(", idcard_back=").append(idcard_back);
        sb.append(", qualification_one=").append(qualification_one);
        sb.append(", qualification_two=").append(qualification_two);
        sb.append(", qualification_three=").append(qualification_three);
        sb.append(", idcard_hold=").append(idcard_hold);
        sb.append(", service_region=").append(service_region);
        sb.append(", construct_about=").append(construct_about);
        sb.append(", service_code=").append(service_code);
        sb.append(", unit_price=").append(unit_price);
        sb.append(", region_code=").append(region_code);
        sb.append(", address_details=").append(address_details);
        sb.append(", certification_state=").append(certification_state);
        sb.append(", team_name=").append(team_name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}