package com.mfangsoft.zhuangjialong.app.personalCenter.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   消费者积分表
 * table t_app_customer_point
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class CustomerPointEntity implements Serializable {
    /**
     *   消费者积分id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   消费者id
     * column customer_id
     *
     * @MLTH_generated
     */
    private Long customer_id;

    /**
     *   积分类型 1邀请 2预约店铺 3分享 4订单 5施工预约 6评价商品 7反馈
     * column type
     *
     * @MLTH_generated
     */
    private Integer type;

    /**
     *   积分
     * column point
     *
     * @MLTH_generated
     */
    private Integer point;

    /**
     *   名字
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     *   店铺id
     * column shop_id
     *
     * @MLTH_generated
     */
    private Long shop_id;

    /**
     *   时间
     * column time
     *
     * @MLTH_generated
     */
    
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date time;

    /**
     *   参数1
     * column param1
     *
     * @MLTH_generated
     */
    private String param1;

    /**
     *   参数2
     * column param2
     *
     * @MLTH_generated
     */
    private String param2;

    /**
     *   参数3
     * column param3
     *
     * @MLTH_generated
     */
    private Long param3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_app_customer_point
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   消费者积分id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   消费者积分id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   消费者id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCustomer_id() {
        return customer_id;
    }

    /**
     *   消费者id
     * @param customer_id the value for 
     *
     * @MLTH_generated
     */
    public void setCustomer_id(Long customer_id) {
        this.customer_id = customer_id;
    }

    /**
     *   积分类型 1邀请 2预约店铺 3分享 4订单 5施工预约 6评价商品 7反馈
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getType() {
        return type;
    }

    /**
     *   积分类型 1邀请 2预约店铺 3分享 4订单 5施工预约 6评价商品 7反馈
     * @param type the value for 
     *
     * @MLTH_generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     *   积分
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getPoint() {
        return point;
    }

    /**
     *   积分
     * @param point the value for 
     *
     * @MLTH_generated
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     *   名字
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   名字
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *   店铺id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getShop_id() {
        return shop_id;
    }

    /**
     *   店铺id
     * @param shop_id the value for 
     *
     * @MLTH_generated
     */
    public void setShop_id(Long shop_id) {
        this.shop_id = shop_id;
    }

    /**
     *   时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getTime() {
        return time;
    }

    /**
     *   时间
     * @param time the value for 
     *
     * @MLTH_generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     *   参数1
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getParam1() {
        return param1;
    }

    /**
     *   参数1
     * @param param1 the value for 
     *
     * @MLTH_generated
     */
    public void setParam1(String param1) {
        this.param1 = param1 == null ? null : param1.trim();
    }

    /**
     *   参数2
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getParam2() {
        return param2;
    }

    /**
     *   参数2
     * @param param2 the value for 
     *
     * @MLTH_generated
     */
    public void setParam2(String param2) {
        this.param2 = param2 == null ? null : param2.trim();
    }

    /**
     *   参数3
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getParam3() {
        return param3;
    }

    /**
     *   参数3
     * @param param3 the value for 
     *
     * @MLTH_generated
     */
    public void setParam3(Long param3) {
        this.param3 = param3;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", customer_id=").append(customer_id);
        sb.append(", type=").append(type);
        sb.append(", point=").append(point);
        sb.append(", name=").append(name);
        sb.append(", shop_id=").append(shop_id);
        sb.append(", time=").append(time);
        sb.append(", param1=").append(param1);
        sb.append(", param2=").append(param2);
        sb.append(", param3=").append(param3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}