package com.mfangsoft.zhuangjialong.app.personalCenter.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_app_customer_message
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class MessageEntity implements Serializable {
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    private Long[] id_array;
    private String name;
    /**
     *   消费者id
     * column customer_id
     *
     * @MLTH_generated
     */
    private Long customer_id;

    /**
     *   消息类型id
     * column type_id
     *
     * @MLTH_generated
     */
    private Integer type_id;

    /**
     *   消息参数,逗号分开
     * column params
     *
     * @MLTH_generated
     */
    private String params;

    /**
     *   0 未读， 1 已读
     * column isread
     *
     * @MLTH_generated
     */
    private Boolean isread;

    private String title;
    /**
     *   消息内容模板
     * column content
     *
     * @MLTH_generated
     */
    private String content;

    /**
     *   消息分组 1订单消息 2活动消息 3通知消息
     * column group
     *
     * @MLTH_generated
     */
    private Integer group;
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date time;
    
    //订单相关参数
    private String message_order_id;
    private String imgurl;
    //活动参数
    private String message_brand_id;
    
    //是否接受订单消息
    private Boolean isreceive_message_order;
    //是否接受活动消息
    private Boolean isreceive_message_appointment;
    //是否接受通知消息
    private Boolean isreceive_message_note;
    
    private Boolean isreceive_message_smart;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_app_customer_message
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    public String getImgurl() {
		return imgurl;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	public Boolean getIsreceive_message_order() {
		return isreceive_message_order;
	}

	public void setIsreceive_message_order(Boolean isreceive_message_order) {
		this.isreceive_message_order = isreceive_message_order;
	}

	public Boolean getIsreceive_message_appointment() {
		return isreceive_message_appointment;
	}

	public void setIsreceive_message_appointment(Boolean isreceive_message_appointment) {
		this.isreceive_message_appointment = isreceive_message_appointment;
	}

	public Boolean getIsreceive_message_note() {
		return isreceive_message_note;
	}

	public void setIsreceive_message_note(Boolean isreceive_message_note) {
		this.isreceive_message_note = isreceive_message_note;
	}

	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getMessage_order_id() {
		return message_order_id;
	}

	public void setMessage_order_id(String message_order_id) {
		this.message_order_id = message_order_id;
	}

	public String getMessage_brand_id() {
		return message_brand_id;
	}

	public void setMessage_brand_id(String message_brand_id) {
		this.message_brand_id = message_brand_id;
	}

	/**
     *   主键
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   消费者id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCustomer_id() {
        return customer_id;
    }

    /**
     *   消费者id
     * @param customer_id the value for 
     *
     * @MLTH_generated
     */
    public void setCustomer_id(Long customer_id) {
        this.customer_id = customer_id;
    }

    /**
     *   消息类型id
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getType_id() {
        return type_id;
    }

    /**
     *   消息类型id
     * @param type_id the value for 
     *
     * @MLTH_generated
     */
    public void setType_id(Integer type_id) {
        this.type_id = type_id;
    }

    /**
     *   消息参数,逗号分开
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getParams() {
        return params;
    }

    /**
     *   消息参数,逗号分开
     * @param params the value for 
     *
     * @MLTH_generated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     *   0 未读， 1 已读
     * @return the value of TINYINT
     *
     * @MLTH_generated
     */
    public Boolean getIsread() {
        return isread;
    }

    /**
     *   0 未读， 1 已读
     * @param isread the value for 
     *
     * @MLTH_generated
     */
    public void setIsread(Boolean isread) {
        this.isread = isread;
    }

    public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getGroup() {
		return group;
	}

	public void setGroup(Integer group) {
		this.group = group;
	}

	public Long[] getId_array() {
		return id_array;
	}

	public void setId_array(Long[] id_array) {
		this.id_array = id_array;
	}

	public Boolean getIsreceive_message_smart() {
		return isreceive_message_smart;
	}

	public void setIsreceive_message_smart(Boolean isreceive_message_smart) {
		this.isreceive_message_smart = isreceive_message_smart;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", customer_id=").append(customer_id);
        sb.append(", type_id=").append(type_id);
        sb.append(", params=").append(params);
        sb.append(", isread=").append(isread);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}