package com.mfangsoft.zhuangjialong.app.personalCenter.model;

import java.io.Serializable;

/**
 *   预付定金表
 * table t_biz_prepayment
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class PrepaymentEntity implements Serializable {
    /**
     *   主键id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   店铺id
     * column shop_id
     *
     * @MLTH_generated
     */
    private Long shop_id;


    /**
     *   红包id
     * column redbag_id
     *
     * @MLTH_generated
     */
    private Long redbag_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_prepayment
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   店铺id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getShop_id() {
        return shop_id;
    }

    /**
     *   店铺id
     * @param shop_id the value for 
     *
     * @MLTH_generated
     */
    public void setShop_id(Long shop_id) {
        this.shop_id = shop_id;
    }


    /**
     *   红包id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getRedbag_id() {
        return redbag_id;
    }

    /**
     *   红包id
     * @param redbag_id the value for 
     *
     * @MLTH_generated
     */
    public void setRedbag_id(Long redbag_id) {
        this.redbag_id = redbag_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", shop_id=").append(shop_id);
        sb.append(", redbag_id=").append(redbag_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}