package com.mfangsoft.zhuangjialong.integration.order.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_biz_order_shell_state_relation
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class OrderShellStateRelationEntity implements Serializable {
    /**
     *   id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   结算单号
     * column shell_id
     *
     * @MLTH_generated
     */
    private Long shell_id;

    /**
     *   结算单状态号
     * column shell_state
     *
     * @MLTH_generated
     */
    private Integer shell_state;

    /**
     *   状态时间
     * column state_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date state_time;

    /**
     *   参数
     * column param
     *
     * @MLTH_generated
     */
    private String param;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_order_shell_state_relation
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   结算单号
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getShell_id() {
        return shell_id;
    }

    /**
     *   结算单号
     * @param shell_id the value for 
     *
     * @MLTH_generated
     */
    public void setShell_id(Long shell_id) {
        this.shell_id = shell_id;
    }

    /**
     *   结算单状态号
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getShell_state() {
        return shell_state;
    }

    /**
     *   结算单状态号
     * @param shell_state the value for 
     *
     * @MLTH_generated
     */
    public void setShell_state(Integer shell_state) {
        this.shell_state = shell_state;
    }

    /**
     *   状态时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getState_time() {
        return state_time;
    }

    /**
     *   状态时间
     * @param state_time the value for 
     *
     * @MLTH_generated
     */
    public void setState_time(Date state_time) {
        this.state_time = state_time;
    }

    /**
     *   参数
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getParam() {
        return param;
    }

    /**
     *   参数
     * @param param the value for 
     *
     * @MLTH_generated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", shell_id=").append(shell_id);
        sb.append(", shell_state=").append(shell_state);
        sb.append(", state_time=").append(state_time);
        sb.append(", param=").append(param);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}