package com.mfangsoft.zhuangjialong.integration.order.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_biz_order_shell_info
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class OrderShellInfoEntity implements Serializable {
    /**
     *   ID
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   设置的每次统计的天数
     * column days
     *
     * @MLTH_generated
     */
    private Integer days;

    /**
     *   每次开始时间
     * column start_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date start_time;

    /**
     *   每次结束时间
     * column end_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date end_time;

    /**
     *   修改时间
     * column update_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date update_time;

    /**
     *   修改之前的统计天数
     * column old_days
     *
     * @MLTH_generated
     */
    private Integer old_days;

    /**
     *   执行状态 1就绪 2执行中
     * column exu_state
     *
     * @MLTH_generated
     */
    private Integer exu_state;

    /**
     *   平台佣金
     * column rate
     *
     * @MLTH_generated
     */
    private Float rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_order_shell_info
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   ID
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     *   ID
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   设置的每次统计的天数
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getDays() {
        return days;
    }

    /**
     *   设置的每次统计的天数
     * @param days the value for 
     *
     * @MLTH_generated
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     *   每次开始时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getStart_time() {
        return start_time;
    }

    /**
     *   每次开始时间
     * @param start_time the value for 
     *
     * @MLTH_generated
     */
    public void setStart_time(Date start_time) {
        this.start_time = start_time;
    }

    /**
     *   每次结束时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     *   每次结束时间
     * @param end_time the value for 
     *
     * @MLTH_generated
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     *   修改时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     *   修改时间
     * @param update_time the value for 
     *
     * @MLTH_generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     *   修改之前的统计天数
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getOld_days() {
        return old_days;
    }

    /**
     *   修改之前的统计天数
     * @param old_days the value for 
     *
     * @MLTH_generated
     */
    public void setOld_days(Integer old_days) {
        this.old_days = old_days;
    }

    /**
     *   执行状态 1就绪 2执行中
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getExu_state() {
        return exu_state;
    }

    /**
     *   执行状态 1就绪 2执行中
     * @param exu_state the value for 
     *
     * @MLTH_generated
     */
    public void setExu_state(Integer exu_state) {
        this.exu_state = exu_state;
    }

    /**
     *   平台佣金
     * @return the value of REAL
     *
     * @MLTH_generated
     */
    public Float getRate() {
        return rate;
    }

    /**
     *   平台佣金
     * @param rate the value for 
     *
     * @MLTH_generated
     */
    public void setRate(Float rate) {
        this.rate = rate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", days=").append(days);
        sb.append(", start_time=").append(start_time);
        sb.append(", end_time=").append(end_time);
        sb.append(", update_time=").append(update_time);
        sb.append(", old_days=").append(old_days);
        sb.append(", exu_state=").append(exu_state);
        sb.append(", rate=").append(rate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}