package com.mfangsoft.zhuangjialong.integration.order.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_biz_order_shell_list
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value = Include.NON_NULL)
public class OrderShellListEntity implements Serializable {
    /**
     *   ID
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   结算单号
     * column shell_code
     *
     * @MLTH_generated
     */
    private String shell_code;

    /**
     *   店铺id
     * column shop_id
     *
     * @MLTH_generated
     */
    private Long shop_id;

    /**
     *   结算总额
     * column money_pre
     *
     * @MLTH_generated
     */
    private Double money_pre;

    /**
     *   平台分成
     * column money_platform
     *
     * @MLTH_generated
     */
    private Double money_platform;

    /**
     *   执行时间
     * column create_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date create_time;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date start_time;
    
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date end_time;
    
    /**
     *   店铺结算渠道
     * column trade_type
     *
     * @MLTH_generated
     */
    private Integer trade_type;

    /**
     *   结算实际执行者
     * column trader_id
     *
     * @MLTH_generated
     */
    private Long trader_id;

    /**
     *   结算金额
     * column money_trade
     *
     * @MLTH_generated
     */
    private Double money_trade;

    /**
     *   结算时间
     * column trade_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date trade_time;

    /**
     *   备注
     * column memo
     *
     * @MLTH_generated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_order_shell_list
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   ID
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   结算单号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getShell_code() {
        return shell_code;
    }

    /**
     *   结算单号
     * @param shell_code the value for 
     *
     * @MLTH_generated
     */
    public void setShell_code(String shell_code) {
        this.shell_code = shell_code == null ? null : shell_code.trim();
    }

    /**
     *   店铺id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getShop_id() {
        return shop_id;
    }

    /**
     *   店铺id
     * @param shop_id the value for 
     *
     * @MLTH_generated
     */
    public void setShop_id(Long shop_id) {
        this.shop_id = shop_id;
    }

    /**
     *   结算总额
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getMoney_pre() {
        return money_pre;
    }

    /**
     *   结算总额
     * @param money_pre the value for 
     *
     * @MLTH_generated
     */
    public void setMoney_pre(Double money_pre) {
        this.money_pre = money_pre;
    }

    /**
     *   平台分成
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getMoney_platform() {
        return money_platform;
    }

    /**
     *   平台分成
     * @param money_platform the value for 
     *
     * @MLTH_generated
     */
    public void setMoney_platform(Double money_platform) {
        this.money_platform = money_platform;
    }

    /**
     *   执行时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   执行时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   店铺结算渠道
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getTrade_type() {
        return trade_type;
    }

    /**
     *   店铺结算渠道
     * @param trade_type the value for 
     *
     * @MLTH_generated
     */
    public void setTrade_type(Integer trade_type) {
        this.trade_type = trade_type;
    }

    /**
     *   结算实际执行者
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getTrader_id() {
        return trader_id;
    }

    /**
     *   结算实际执行者
     * @param trader_id the value for 
     *
     * @MLTH_generated
     */
    public void setTrader_id(Long trader_id) {
        this.trader_id = trader_id;
    }

    /**
     *   结算金额
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getMoney_trade() {
        return money_trade;
    }

    /**
     *   结算金额
     * @param money_trade the value for 
     *
     * @MLTH_generated
     */
    public void setMoney_trade(Double money_trade) {
        this.money_trade = money_trade;
    }

    /**
     *   结算时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getTrade_time() {
        return trade_time;
    }

    /**
     *   结算时间
     * @param trade_time the value for 
     *
     * @MLTH_generated
     */
    public void setTrade_time(Date trade_time) {
        this.trade_time = trade_time;
    }

    /**
     *   备注
     * @return the value of LONGVARCHAR
     *
     * @MLTH_generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     *   备注
     * @param memo the value for 
     *
     * @MLTH_generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    public Date getStart_time() {
		return start_time;
	}

	public void setStart_time(Date start_time) {
		this.start_time = start_time;
	}


	public Date getEnd_time() {
		return end_time;
	}

	public void setEnd_time(Date end_time) {
		this.end_time = end_time;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", shell_code=").append(shell_code);
        sb.append(", shop_id=").append(shop_id);
        sb.append(", money_pre=").append(money_pre);
        sb.append(", money_platform=").append(money_platform);
        sb.append(", create_time=").append(create_time);
        sb.append(", trade_type=").append(trade_type);
        sb.append(", trader_id=").append(trader_id);
        sb.append(", money_trade=").append(money_trade);
        sb.append(", trade_time=").append(trade_time);
        sb.append(", memo=").append(memo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}