package com.mfangsoft.zhuangjialong.app.inviteconvert.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   消费者兑换邀请人表
 * table t_biz_invite_product
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class InviteProductEntity implements Serializable {
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   产品面额
     * column package_value
     *
     * @MLTH_generated
     */
    private Integer package_value;

    /**
     *   消耗邀请人
     * column invite_no
     *
     * @MLTH_generated
     */
    private Integer invite_no;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    private Date create_time;

    /**
     *   状态(上下架)
     * column state
     *
     * @MLTH_generated
     */
    private Byte state;

    /**
     *   产品类型（暂时不用）
     * column type
     *
     * @MLTH_generated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_invite_product
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   产品面额
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getPackage_value() {
        return package_value;
    }

    /**
     *   产品面额
     * @param package_value the value for 
     *
     * @MLTH_generated
     */
    public void setPackage_value(Integer package_value) {
        this.package_value = package_value;
    }

    /**
     *   消耗邀请人
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getInvite_no() {
        return invite_no;
    }

    /**
     *   消耗邀请人
     * @param invite_no the value for 
     *
     * @MLTH_generated
     */
    public void setInvite_no(Integer invite_no) {
        this.invite_no = invite_no;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   状态(上下架)
     * @return the value of TINYINT
     *
     * @MLTH_generated
     */
    public Byte getState() {
        return state;
    }

    /**
     *   状态(上下架)
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     *   产品类型（暂时不用）
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getType() {
        return type;
    }

    /**
     *   产品类型（暂时不用）
     * @param type the value for 
     *
     * @MLTH_generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", package_value=").append(package_value);
        sb.append(", invite_no=").append(invite_no);
        sb.append(", create_time=").append(create_time);
        sb.append(", state=").append(state);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}