package com.mfangsoft.zhuangjialong.app.inviteconvert.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   消费者消耗邀请人兑换表
 * table t_biz_invite_convert
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class InviteConvertEntity implements Serializable {
    /**
     *   兑换码(订单号)
     * column convert_no
     *
     * @MLTH_generated
     */
    private String convert_no;

    /**
     *   消费者id
     * column customer_id
     *
     * @MLTH_generated
     */
    private Long customer_id;

    /**
     *   兑换产品id
     * column product_id
     *
     * @MLTH_generated
     */
    private Integer product_id;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    private Date create_time;

    /**
     *   回调时间
     * column back_time
     *
     * @MLTH_generated
     */
    private Date back_time;

    /**
     *   兑换状态(1:充值中2:已使用3:兑换失败)
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_invite_convert
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   兑换码(订单号)
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getConvert_no() {
        return convert_no;
    }

    /**
     *   兑换码(订单号)
     * @param convert_no the value for 
     *
     * @MLTH_generated
     */
    public void setConvert_no(String convert_no) {
        this.convert_no = convert_no == null ? null : convert_no.trim();
    }

    /**
     *   消费者id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCustomer_id() {
        return customer_id;
    }

    /**
     *   消费者id
     * @param customer_id the value for 
     *
     * @MLTH_generated
     */
    public void setCustomer_id(Long customer_id) {
        this.customer_id = customer_id;
    }

    /**
     *   兑换产品id
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getProduct_id() {
        return product_id;
    }

    /**
     *   兑换产品id
     * @param product_id the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_id(Integer product_id) {
        this.product_id = product_id;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   回调时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getBack_time() {
        return back_time;
    }

    /**
     *   回调时间
     * @param back_time the value for 
     *
     * @MLTH_generated
     */
    public void setBack_time(Date back_time) {
        this.back_time = back_time;
    }

    /**
     *   兑换状态(1:充值中2:已使用3:兑换失败)
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   兑换状态(1:充值中2:已使用3:兑换失败)
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", convert_no=").append(convert_no);
        sb.append(", customer_id=").append(customer_id);
        sb.append(", product_id=").append(product_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", back_time=").append(back_time);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}