package com.mfangsoft.zhuangjialong.integration.role.model;

import java.io.Serializable;

/**
 *   角色表
 * table t_sys_role
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class RoleEntity implements Serializable {
    /**
     *   id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   角色名称
     * column role_name
     *
     * @MLTH_generated
     */
    private String role_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_role
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   角色名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getRole_name() {
        return role_name;
    }

    /**
     *   角色名称
     * @param role_name the value for 
     *
     * @MLTH_generated
     */
    public void setRole_name(String role_name) {
        this.role_name = role_name == null ? null : role_name.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", role_name=").append(role_name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}