package com.mfangsoft.zhuangjialong.integration.role.model;

import java.io.Serializable;

/**
 *   用户岗位关系表
 * table t_sys_user_position
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class UserPositionEntity implements Serializable {
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   岗位ID
     * column position_id
     *
     * @MLTH_generated
     */
    private Long position_id;

    /**
     *   用户ID
     * column user_id
     *
     * @MLTH_generated
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_user_position
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   岗位ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getPosition_id() {
        return position_id;
    }

    /**
     *   岗位ID
     * @param position_id the value for 
     *
     * @MLTH_generated
     */
    public void setPosition_id(Long position_id) {
        this.position_id = position_id;
    }

    /**
     *   用户ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     *   用户ID
     * @param user_id the value for 
     *
     * @MLTH_generated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", position_id=").append(position_id);
        sb.append(", user_id=").append(user_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}