package com.mfangsoft.zhuangjialong.integration.entnewproduct.model;

import java.io.Serializable;

/**
 *   品牌产品属性值表
 * table t_biz_ent_prod_attrvalue
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseEntProdAttrValueEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   属性Id
     * column attr_id
     *
     * @MLTH_generated
     */
    private Long attr_id;

    /**
     *   属性值
     * column attr_value
     *
     * @MLTH_generated
     */
    private String attr_value;

    /**
     *   产品Id
     * column product_id
     *
     * @MLTH_generated
     */
    private Long product_id;

    /**
     *   是否关联
     * column isrelation
     *
     * @MLTH_generated
     */
    private Integer isrelation;

    /**
     *   品类Id
     * column class_id
     *
     * @MLTH_generated
     */
    private Long class_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_ent_prod_attrvalue
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   属性Id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getAttr_id() {
        return attr_id;
    }

    /**
     *   属性Id
     * @param attr_id the value for 
     *
     * @MLTH_generated
     */
    public void setAttr_id(Long attr_id) {
        this.attr_id = attr_id;
    }

    /**
     *   属性值
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getAttr_value() {
        return attr_value;
    }

    /**
     *   属性值
     * @param attr_value the value for 
     *
     * @MLTH_generated
     */
    public void setAttr_value(String attr_value) {
        this.attr_value = attr_value == null ? null : attr_value.trim();
    }

    /**
     *   产品Id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getProduct_id() {
        return product_id;
    }

    /**
     *   产品Id
     * @param product_id the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    /**
     *   是否关联
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getIsrelation() {
        return isrelation;
    }

    /**
     *   是否关联
     * @param isrelation the value for 
     *
     * @MLTH_generated
     */
    public void setIsrelation(Integer isrelation) {
        this.isrelation = isrelation;
    }

    /**
     *   品类Id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getClass_id() {
        return class_id;
    }

    /**
     *   品类Id
     * @param class_id the value for 
     *
     * @MLTH_generated
     */
    public void setClass_id(Long class_id) {
        this.class_id = class_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", attr_id=").append(attr_id);
        sb.append(", attr_value=").append(attr_value);
        sb.append(", product_id=").append(product_id);
        sb.append(", isrelation=").append(isrelation);
        sb.append(", class_id=").append(class_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}