package com.mfangsoft.zhuangjialong.integration.entnewproduct.model;

import java.io.Serializable;

import com.mfangsoft.zhuangjialong.integration.series.model.EntSeriesEntity;

/**
 *   企业产品系列关系表
 * table t_biz_ent_prod_series
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseEntProdSeriesEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     * column series_id
     *
     * @MLTH_generated
     */
    private Long series_id;

    /**
     * column product_id
     *
     * @MLTH_generated
     */
    private Long product_id;

    
    private EntSeriesEntity entSeriesEntity;
    public EntSeriesEntity getEntSeriesEntity() {
		return entSeriesEntity;
	}

	public void setEntSeriesEntity(EntSeriesEntity entSeriesEntity) {
		this.entSeriesEntity = entSeriesEntity;
	}

	/**
     * column impFlag
     *
     * @MLTH_generated
     */
    private String impFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_ent_prod_series
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSeries_id() {
        return series_id;
    }

    /**
     * @param series_id the value for 
     *
     * @MLTH_generated
     */
    public void setSeries_id(Long series_id) {
        this.series_id = series_id;
    }

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getProduct_id() {
        return product_id;
    }

    /**
     * @param product_id the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    /**
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImpFlag() {
        return impFlag;
    }

    /**
     * @param impFlag the value for 
     *
     * @MLTH_generated
     */
    public void setImpFlag(String impFlag) {
        this.impFlag = impFlag == null ? null : impFlag.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", series_id=").append(series_id);
        sb.append(", product_id=").append(product_id);
        sb.append(", impFlag=").append(impFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}