package com.mfangsoft.zhuangjialong.integration.brandclassify.model;

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.mfangsoft.zhuangjialong.integration.series.model.BrandSeriesEntity;

/**
 *   品牌分类表
 * table t_biz_brand_classify
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class BrandClassifyEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   品牌id
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     *   分类名称
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     *   创建者
     * column creater
     *
     * @MLTH_generated
     */
    private Long creater;

    /**
     *   排序号
     * column sort
     *
     * @MLTH_generated
     */
    private Integer sort;
    
    /**
     *   品牌系列
     * column sort
     *
     * @MLTH_generated
     */
    private List<BrandSeriesEntity> brandSeries;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_brand_classify
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   品牌id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌id
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     *   分类名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   分类名称
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *   创建者
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCreater() {
        return creater;
    }

    /**
     *   创建者
     * @param creater the value for 
     *
     * @MLTH_generated
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     *   排序号
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     *   排序号
     * @param sort the value for 
     *
     * @MLTH_generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
   
     
    /**
	 * @return the brandSeries
	 */
	public List<BrandSeriesEntity> getBrandSeries() {
		return brandSeries;
	}

	/**
	 * @param brandSeries the brandSeries to set
	 */
	public void setBrandSeries(List<BrandSeriesEntity> brandSeries) {
		this.brandSeries = brandSeries;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", name=").append(name);
        sb.append(", creater=").append(creater);
        sb.append(", sort=").append(sort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}