package com.mfangsoft.zhuangjialong.integration.newproduct.model;

import java.io.Serializable;

/**
 * table t_biz_class_attr_value
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseClassAttrValueEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private String id;

    /**
     *   值
     * column value
     *
     * @MLTH_generated
     */
    private String value;

    /**
     *   属性Id
     * column attr_id
     *
     * @MLTH_generated
     */
    private Long attr_id;

    /**
     *   父属性Id
     * column parent_attr_id
     *
     * @MLTH_generated
     */
    private Long parent_attr_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_class_attr_value
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public String getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     *   值
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getValue() {
        return value;
    }

    /**
     *   值
     * @param value the value for 
     *
     * @MLTH_generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     *   属性Id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getAttr_id() {
        return attr_id;
    }

    /**
     *   属性Id
     * @param attr_id the value for 
     *
     * @MLTH_generated
     */
    public void setAttr_id(Long attr_id) {
        this.attr_id = attr_id;
    }

    /**
     *   父属性Id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getParent_attr_id() {
        return parent_attr_id;
    }

    /**
     *   父属性Id
     * @param parent_attr_id the value for 
     *
     * @MLTH_generated
     */
    public void setParent_attr_id(Long parent_attr_id) {
        this.parent_attr_id = parent_attr_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", value=").append(value);
        sb.append(", attr_id=").append(attr_id);
        sb.append(", parent_attr_id=").append(parent_attr_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}