package com.mfangsoft.zhuangjialong.integration.newproduct.model;

import java.io.Serializable;

/**
 * table t_biz_brand_prod_salesattr
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseBrandProdSalesAttrEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   颜色
     * column color
     *
     * @MLTH_generated
     */
    private String color;

    /**
     *   颜色url
     * column color_url
     *
     * @MLTH_generated
     */
    private String color_url;

    /**
     *   规格
     * column standard
     *
     * @MLTH_generated
     */
    private String standard;

    /**
     *   更新 upd  新增 ins  删除del
     * column data_flag
     *
     * @MLTH_generated
     */
    private String data_flag;

    /**
     *   型号
     * column model
     *
     * @MLTH_generated
     */
    private String model;

    /**
     *   产品id
     * column product_id
     *
     * @MLTH_generated
     */
    private Long product_id;

    /**
     *   套餐
     * column set_meal
     *
     * @MLTH_generated
     */
    private String set_meal;

    /**
     *   价格
     * column price
     *
     * @MLTH_generated
     */
    private Double price;

    /**
     *   库存
     * column stock
     *
     * @MLTH_generated
     */
    private Long stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_brand_prod_salesattr
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   颜色
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getColor() {
        return color;
    }

    /**
     *   颜色
     * @param color the value for 
     *
     * @MLTH_generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     *   颜色url
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getColor_url() {
        return color_url;
    }

    /**
     *   颜色url
     * @param color_url the value for 
     *
     * @MLTH_generated
     */
    public void setColor_url(String color_url) {
        this.color_url = color_url == null ? null : color_url.trim();
    }

    /**
     *   规格
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getStandard() {
        return standard;
    }

    /**
     *   规格
     * @param standard the value for 
     *
     * @MLTH_generated
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     *   更新 upd  新增 ins  删除del
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getData_flag() {
        return data_flag;
    }

    /**
     *   更新 upd  新增 ins  删除del
     * @param data_flag the value for 
     *
     * @MLTH_generated
     */
    public void setData_flag(String data_flag) {
        this.data_flag = data_flag == null ? null : data_flag.trim();
    }

    /**
     *   型号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getModel() {
        return model;
    }

    /**
     *   型号
     * @param model the value for 
     *
     * @MLTH_generated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     *   产品id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getProduct_id() {
        return product_id;
    }

    /**
     *   产品id
     * @param product_id the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    /**
     *   套餐
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getSet_meal() {
        return set_meal;
    }

    /**
     *   套餐
     * @param set_meal the value for 
     *
     * @MLTH_generated
     */
    public void setSet_meal(String set_meal) {
        this.set_meal = set_meal == null ? null : set_meal.trim();
    }

    /**
     *   价格
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     *   价格
     * @param price the value for 
     *
     * @MLTH_generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     *   库存
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getStock() {
        return stock;
    }

    /**
     *   库存
     * @param stock the value for 
     *
     * @MLTH_generated
     */
    public void setStock(Long stock) {
        this.stock = stock;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", color=").append(color);
        sb.append(", color_url=").append(color_url);
        sb.append(", standard=").append(standard);
        sb.append(", data_flag=").append(data_flag);
        sb.append(", model=").append(model);
        sb.append(", product_id=").append(product_id);
        sb.append(", set_meal=").append(set_meal);
        sb.append(", price=").append(price);
        sb.append(", stock=").append(stock);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}