package com.mfangsoft.zhuangjialong.integration.newproduct.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * table t_biz_brand_product
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseBrandProductEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   标题
     * column product_title
     *
     * @MLTH_generated
     */
    private String product_title;

    /**
     *   排序
     * column product_sort
     *
     * @MLTH_generated
     */
    private Integer product_sort;

    /**
     *   计价单位
     * column product_unit
     *
     * @MLTH_generated
     */
    private String product_unit;

    /**
     * column build_brand_id
     *
     * @MLTH_generated
     */
    private Long build_brand_id;

    /**
     *   是否新品
     * column isnew
     *
     * @MLTH_generated
     */
    private Integer isnew;

    /**
     *   新品时间
     * column new_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date new_time;

    /**
     *   合伙人ID
     * column partner_id
     *
     * @MLTH_generated
     */
    private Long partner_id;

    /**
     *   1:一口价，2 定金
     * column sales_model
     *
     * @MLTH_generated
     */
    private Integer sales_model;

    /**
     *   百分比
     * column percent
     *
     * @MLTH_generated
     */
    private Double percent;

    /**
     *   1:上架，2：下架
     * column state
     *
     * @MLTH_generated
     */
    private Integer state=1;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    private Date create_time;

    /**
     *   企业ID
     * column enterprise_id
     *
     * @MLTH_generated
     */
    private Long enterprise_id;

    /**
     *   品牌ID
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     * column class_id
     *
     * @MLTH_generated
     */
    private Long class_id;

    /**
     * column tmpflag
     *
     * @MLTH_generated
     */
    private String tmpflag;
    
    private Integer sell_type;
    
    private String sell_url;

    /**
     *   产品详情
     * column description
     *
     * @MLTH_generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_brand_product
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   标题
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getProduct_title() {
        return product_title;
    }

    /**
     *   标题
     * @param product_title the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_title(String product_title) {
        this.product_title = product_title == null ? null : product_title.trim();
    }

    /**
     *   排序
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getProduct_sort() {
        return product_sort;
    }

    /**
     *   排序
     * @param product_sort the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_sort(Integer product_sort) {
        this.product_sort = product_sort;
    }

    /**
     *   计价单位
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getProduct_unit() {
        return product_unit;
    }

    /**
     *   计价单位
     * @param product_unit the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_unit(String product_unit) {
        this.product_unit = product_unit == null ? null : product_unit.trim();
    }

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBuild_brand_id() {
        return build_brand_id;
    }

    /**
     * @param build_brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBuild_brand_id(Long build_brand_id) {
        this.build_brand_id = build_brand_id;
    }

    /**
     *   是否新品
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getIsnew() {
        return isnew;
    }

    /**
     *   是否新品
     * @param isnew the value for 
     *
     * @MLTH_generated
     */
    public void setIsnew(Integer isnew) {
        this.isnew = isnew;
    }

    /**
     *   新品时间
     * @return the value of DATE
     *
     * @MLTH_generated
     */
    public Date getNew_time() {
        return new_time;
    }

    /**
     *   新品时间
     * @param new_time the value for 
     *
     * @MLTH_generated
     */
    public void setNew_time(Date new_time) {
        this.new_time = new_time;
    }

    /**
     *   合伙人ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getPartner_id() {
        return partner_id;
    }

    /**
     *   合伙人ID
     * @param partner_id the value for 
     *
     * @MLTH_generated
     */
    public void setPartner_id(Long partner_id) {
        this.partner_id = partner_id;
    }

    /**
     *   1:一口价，2 定金
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSales_model() {
        return sales_model;
    }

    /**
     *   1:一口价，2 定金
     * @param sales_model the value for 
     *
     * @MLTH_generated
     */
    public void setSales_model(Integer sales_model) {
        this.sales_model = sales_model;
    }

    /**
     *   百分比
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getPercent() {
        return percent;
    }

    /**
     *   百分比
     * @param percent the value for 
     *
     * @MLTH_generated
     */
    public void setPercent(Double percent) {
        this.percent = percent;
    }

    /**
     *   1:上架，2：下架
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
    	if(this.state.intValue()==0){
    		
    		return 1;
    	}else{
    		
    		 return state;
    	}
    	
       
    }

    /**
     *   1:上架，2：下架
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   企业ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getEnterprise_id() {
        return enterprise_id;
    }

    /**
     *   企业ID
     * @param enterprise_id the value for 
     *
     * @MLTH_generated
     */
    public void setEnterprise_id(Long enterprise_id) {
        this.enterprise_id = enterprise_id;
    }

    /**
     *   品牌ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌ID
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getClass_id() {
        return class_id;
    }

    /**
     * @param class_id the value for 
     *
     * @MLTH_generated
     */
    public void setClass_id(Long class_id) {
        this.class_id = class_id;
    }

    /**
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getTmpflag() {
        return tmpflag;
    }

    /**
     * @param tmpflag the value for 
     *
     * @MLTH_generated
     */
    public void setTmpflag(String tmpflag) {
        this.tmpflag = tmpflag == null ? null : tmpflag.trim();
    }

    /**
     *   产品详情
     * @return the value of LONGVARCHAR
     *
     * @MLTH_generated
     */
    public String getDescription() {
        return description;
    }

    /**
     *   产品详情
     * @param description the value for 
     *
     * @MLTH_generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public Integer getSell_type() {
		return sell_type;
	}

	public void setSell_type(Integer sell_type) {
		this.sell_type = sell_type;
	}

	public String getSell_url() {
		return sell_url;
	}

	public void setSell_url(String sell_url) {
		this.sell_url = sell_url;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", product_title=").append(product_title);
        sb.append(", product_sort=").append(product_sort);
        sb.append(", product_unit=").append(product_unit);
        sb.append(", build_brand_id=").append(build_brand_id);
        sb.append(", isnew=").append(isnew);
        sb.append(", new_time=").append(new_time);
        sb.append(", partner_id=").append(partner_id);
        sb.append(", sales_model=").append(sales_model);
        sb.append(", percent=").append(percent);
        sb.append(", state=").append(state);
        sb.append(", create_time=").append(create_time);
        sb.append(", enterprise_id=").append(enterprise_id);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", class_id=").append(class_id);
        sb.append(", tmpflag=").append(tmpflag);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}