package com.mfangsoft.zhuangjialong.integration.newproduct.model;

import java.io.Serializable;

/**
 * table t_biz_class_attr
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseClassAttrEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   是否多选（1：可多选，2不可多选）
     * column ismultiple
     *
     * @MLTH_generated
     */
    private Integer ismultiple;

    /**
     *   属性名称
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     *   是否可枚举（1：可枚举，2不可枚举）
     * column isenum
     *
     * @MLTH_generated
     */
    private Integer isenum;

    /**
     *   品类id
     * column class_id
     *
     * @MLTH_generated
     */
    private Long class_id;

    /**
     *   是否级联（1：级联，2非级联）
     * column iscascading
     *
     * @MLTH_generated
     */
    private Integer iscascading;

    /**
     *   是否可填写（1：可填写，2非可填写）
     * column iswrite
     *
     * @MLTH_generated
     */
    private Integer iswrite;

    /**
     *   级联属性id 默认-1
     * column cascading_attr_id
     *
     * @MLTH_generated
     */
    private Long cascading_attr_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_class_attr
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   是否多选（1：可多选，2不可多选）
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getIsmultiple() {
        return ismultiple;
    }

    /**
     *   是否多选（1：可多选，2不可多选）
     * @param ismultiple the value for 
     *
     * @MLTH_generated
     */
    public void setIsmultiple(Integer ismultiple) {
        this.ismultiple = ismultiple;
    }

    /**
     *   属性名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   属性名称
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *   是否可枚举（1：可枚举，2不可枚举）
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getIsenum() {
        return isenum;
    }

    /**
     *   是否可枚举（1：可枚举，2不可枚举）
     * @param isenum the value for 
     *
     * @MLTH_generated
     */
    public void setIsenum(Integer isenum) {
        this.isenum = isenum;
    }

    /**
     *   品类id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getClass_id() {
        return class_id;
    }

    /**
     *   品类id
     * @param class_id the value for 
     *
     * @MLTH_generated
     */
    public void setClass_id(Long class_id) {
        this.class_id = class_id;
    }

    /**
     *   是否级联（1：级联，2非级联）
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getIscascading() {
        return iscascading;
    }

    /**
     *   是否级联（1：级联，2非级联）
     * @param iscascading the value for 
     *
     * @MLTH_generated
     */
    public void setIscascading(Integer iscascading) {
        this.iscascading = iscascading;
    }

    /**
     *   是否可填写（1：可填写，2非可填写）
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getIswrite() {
        return iswrite;
    }

    /**
     *   是否可填写（1：可填写，2非可填写）
     * @param iswrite the value for 
     *
     * @MLTH_generated
     */
    public void setIswrite(Integer iswrite) {
        this.iswrite = iswrite;
    }

    /**
     *   级联属性id 默认-1
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCascading_attr_id() {
        return cascading_attr_id;
    }

    /**
     *   级联属性id 默认-1
     * @param cascading_attr_id the value for 
     *
     * @MLTH_generated
     */
    public void setCascading_attr_id(Long cascading_attr_id) {
        this.cascading_attr_id = cascading_attr_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ismultiple=").append(ismultiple);
        sb.append(", name=").append(name);
        sb.append(", isenum=").append(isenum);
        sb.append(", class_id=").append(class_id);
        sb.append(", iscascading=").append(iscascading);
        sb.append(", iswrite=").append(iswrite);
        sb.append(", cascading_attr_id=").append(cascading_attr_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}