package com.mfangsoft.zhuangjialong.integration.excelexp.model;

import java.io.Serializable;

/**
 * table t_biz_exp_excel
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseExpExcleEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     * column module_code
     *
     * @MLTH_generated
     */
    private String module_code;

    /**
     * column module_name
     *
     * @MLTH_generated
     */
    private String module_name;

    /**
     * column template_name
     *
     * @MLTH_generated
     */
    private String template_name;

    /**
     * column export_class
     *
     * @MLTH_generated
     */
    private String export_class;

    /**
     * column is_user_type
     *
     * @MLTH_generated
     */
    private Boolean is_user_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_exp_excel
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getModule_code() {
        return module_code;
    }

    /**
     * @param module_code the value for 
     *
     * @MLTH_generated
     */
    public void setModule_code(String module_code) {
        this.module_code = module_code == null ? null : module_code.trim();
    }

    /**
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getModule_name() {
        return module_name;
    }

    /**
     * @param module_name the value for 
     *
     * @MLTH_generated
     */
    public void setModule_name(String module_name) {
        this.module_name = module_name == null ? null : module_name.trim();
    }

    /**
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getTemplate_name() {
        return template_name;
    }

    /**
     * @param template_name the value for 
     *
     * @MLTH_generated
     */
    public void setTemplate_name(String template_name) {
        this.template_name = template_name == null ? null : template_name.trim();
    }

    /**
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getExport_class() {
        return export_class;
    }

    /**
     * @param export_class the value for 
     *
     * @MLTH_generated
     */
    public void setExport_class(String export_class) {
        this.export_class = export_class == null ? null : export_class.trim();
    }

    /**
     * @return the value of BIT
     *
     * @MLTH_generated
     */
    public Boolean getIs_user_type() {
        return is_user_type;
    }

    /**
     * @param is_user_type the value for 
     *
     * @MLTH_generated
     */
    public void setIs_user_type(Boolean is_user_type) {
        this.is_user_type = is_user_type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", module_code=").append(module_code);
        sb.append(", module_name=").append(module_name);
        sb.append(", template_name=").append(template_name);
        sb.append(", export_class=").append(export_class);
        sb.append(", is_user_type=").append(is_user_type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}