package com.mfangsoft.zhuangjialong.app.newproductcore.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 *   VIEW
 * table v_product_new_core
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class NewProductCoreModel implements Serializable {
    /**
     * column product_id
     *
     * @MLTH_generated
     */
    private Long product_id;

    /**
     *   图片url
     * column imgurl
     *
     * @MLTH_generated
     */
    private String imgurl;

    /**
     * column sales_num
     *
     * @MLTH_generated
     */
    private Long sales_num;

    /**
     *   标题
     * column product_name
     *
     * @MLTH_generated
     */
    private String product_name;

    /**
     *   品牌id
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     *   名称
     * column brand_name
     *
     * @MLTH_generated
     */
    private String brand_name;

    /**
     *   热线电话
     * column hot_line
     *
     * @MLTH_generated
     */
    private String hot_line;

    /**
     *   企业ID
     * column enterprise_id
     *
     * @MLTH_generated
     */
    private Long enterprise_id;

    /**
     *   品牌url
     * column brand_imgurl
     *
     * @MLTH_generated
     */
    private String brand_imgurl;

    /**
     * column class_id
     *
     * @MLTH_generated
     */
    private Long class_id;

    /**
     *   品类名称
     * column class_name
     *
     * @MLTH_generated
     */
    private String class_name;

    /**
     *   合伙人ID
     * column citypartner_id
     *
     * @MLTH_generated
     */
    private Long citypartner_id;

    /**
     *   ID 数组
     * column region_code
     *
     * @MLTH_generated
     */
    private String region_code;

    /**
     *   1:上架，2：下架
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date create_time;

    /**
     *   排序
     * column sort
     *
     * @MLTH_generated
     */
    private Integer sort;

    /**
     *   新品时间
     * column new_time
     *
     * @MLTH_generated
     */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date new_time;

    /**
     *   是否新品
     * column isnew
     *
     * @MLTH_generated
     */
    private Integer isnew;

    /**
     *   计价单位
     * column unit
     *
     * @MLTH_generated
     */
    private String unit;

    /**
     *   1:一口价，2 定金
     * column sales_model
     *
     * @MLTH_generated
     */
    private Integer sales_model;

    /**
     *   百分比
     * column percent
     *
     * @MLTH_generated
     */
    private Double percent;

    /**
     *   价格
     * column min_price
     *
     * @MLTH_generated
     */
    private Double min_price;

    /**
     *   价格
     * column max_price
     *
     * @MLTH_generated
     */
    private Double max_price;

    /**
     *   规格
     * column standard
     *
     * @MLTH_generated
     */
    private String standard;

    /**
     * column min_promotion_price
     *
     * @MLTH_generated
     */
    private Double min_promotion_price;

    /**
     *   产品详情
     * column description
     *
     * @MLTH_generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_product_new_core
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getProduct_id() {
        return product_id;
    }

    /**
     * @param product_id the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    /**
     *   图片url
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     *   图片url
     * @param imgurl the value for 
     *
     * @MLTH_generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSales_num() {
        return sales_num;
    }

    /**
     * @param sales_num the value for 
     *
     * @MLTH_generated
     */
    public void setSales_num(Long sales_num) {
        this.sales_num = sales_num;
    }

    /**
     *   标题
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getProduct_name() {
        return product_name;
    }

    /**
     *   标题
     * @param product_name the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_name(String product_name) {
        this.product_name = product_name == null ? null : product_name.trim();
    }

    /**
     *   品牌id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌id
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     *   名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getBrand_name() {
        return brand_name;
    }

    /**
     *   名称
     * @param brand_name the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_name(String brand_name) {
        this.brand_name = brand_name == null ? null : brand_name.trim();
    }

    /**
     *   热线电话
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getHot_line() {
        return hot_line;
    }

    /**
     *   热线电话
     * @param hot_line the value for 
     *
     * @MLTH_generated
     */
    public void setHot_line(String hot_line) {
        this.hot_line = hot_line == null ? null : hot_line.trim();
    }

    /**
     *   企业ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getEnterprise_id() {
        return enterprise_id;
    }

    /**
     *   企业ID
     * @param enterprise_id the value for 
     *
     * @MLTH_generated
     */
    public void setEnterprise_id(Long enterprise_id) {
        this.enterprise_id = enterprise_id;
    }

    /**
     *   品牌url
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getBrand_imgurl() {
        return brand_imgurl;
    }

    /**
     *   品牌url
     * @param brand_imgurl the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_imgurl(String brand_imgurl) {
        this.brand_imgurl = brand_imgurl == null ? null : brand_imgurl.trim();
    }

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getClass_id() {
        return class_id;
    }

    /**
     * @param class_id the value for 
     *
     * @MLTH_generated
     */
    public void setClass_id(Long class_id) {
        this.class_id = class_id;
    }

    /**
     *   品类名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getClass_name() {
        return class_name;
    }

    /**
     *   品类名称
     * @param class_name the value for 
     *
     * @MLTH_generated
     */
    public void setClass_name(String class_name) {
        this.class_name = class_name == null ? null : class_name.trim();
    }

    /**
     *   合伙人ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCitypartner_id() {
        return citypartner_id;
    }

    /**
     *   合伙人ID
     * @param citypartner_id the value for 
     *
     * @MLTH_generated
     */
    public void setCitypartner_id(Long citypartner_id) {
        this.citypartner_id = citypartner_id;
    }

    /**
     *   ID 数组
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getRegion_code() {
        return region_code;
    }

    /**
     *   ID 数组
     * @param region_code the value for 
     *
     * @MLTH_generated
     */
    public void setRegion_code(String region_code) {
        this.region_code = region_code == null ? null : region_code.trim();
    }

    /**
     *   1:上架，2：下架
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   1:上架，2：下架
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   排序
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     *   排序
     * @param sort the value for 
     *
     * @MLTH_generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     *   新品时间
     * @return the value of DATE
     *
     * @MLTH_generated
     */
    public Date getNew_time() {
        return new_time;
    }

    /**
     *   新品时间
     * @param new_time the value for 
     *
     * @MLTH_generated
     */
    public void setNew_time(Date new_time) {
        this.new_time = new_time;
    }

    /**
     *   是否新品
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getIsnew() {
        return isnew;
    }

    /**
     *   是否新品
     * @param isnew the value for 
     *
     * @MLTH_generated
     */
    public void setIsnew(Integer isnew) {
        this.isnew = isnew;
    }

    /**
     *   计价单位
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     *   计价单位
     * @param unit the value for 
     *
     * @MLTH_generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     *   1:一口价，2 定金
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSales_model() {
        return sales_model;
    }

    /**
     *   1:一口价，2 定金
     * @param sales_model the value for 
     *
     * @MLTH_generated
     */
    public void setSales_model(Integer sales_model) {
        this.sales_model = sales_model;
    }

    /**
     *   百分比
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getPercent() {
        return percent;
    }

    /**
     *   百分比
     * @param percent the value for 
     *
     * @MLTH_generated
     */
    public void setPercent(Double percent) {
        this.percent = percent;
    }

    /**
     *   价格
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getMin_price() {
        return min_price;
    }

    /**
     *   价格
     * @param min_price the value for 
     *
     * @MLTH_generated
     */
    public void setMin_price(Double min_price) {
        this.min_price = min_price;
    }

    /**
     *   价格
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getMax_price() {
        return max_price;
    }

    /**
     *   价格
     * @param max_price the value for 
     *
     * @MLTH_generated
     */
    public void setMax_price(Double max_price) {
        this.max_price = max_price;
    }

    /**
     *   规格
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getStandard() {
        return standard;
    }

    /**
     *   规格
     * @param standard the value for 
     *
     * @MLTH_generated
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getMin_promotion_price() {
        return min_promotion_price;
    }

    /**
     * @param min_promotion_price the value for 
     *
     * @MLTH_generated
     */
    public void setMin_promotion_price(Double min_promotion_price) {
        this.min_promotion_price = min_promotion_price;
    }

    /**
     *   产品详情
     * @return the value of LONGVARCHAR
     *
     * @MLTH_generated
     */
    public String getDescription() {
        return description;
    }

    /**
     *   产品详情
     * @param description the value for 
     *
     * @MLTH_generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", product_id=").append(product_id);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", sales_num=").append(sales_num);
        sb.append(", product_name=").append(product_name);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", brand_name=").append(brand_name);
        sb.append(", hot_line=").append(hot_line);
        sb.append(", enterprise_id=").append(enterprise_id);
        sb.append(", brand_imgurl=").append(brand_imgurl);
        sb.append(", class_id=").append(class_id);
        sb.append(", class_name=").append(class_name);
        sb.append(", citypartner_id=").append(citypartner_id);
        sb.append(", region_code=").append(region_code);
        sb.append(", state=").append(state);
        sb.append(", create_time=").append(create_time);
        sb.append(", sort=").append(sort);
        sb.append(", new_time=").append(new_time);
        sb.append(", isnew=").append(isnew);
        sb.append(", unit=").append(unit);
        sb.append(", sales_model=").append(sales_model);
        sb.append(", percent=").append(percent);
        sb.append(", min_price=").append(min_price);
        sb.append(", max_price=").append(max_price);
        sb.append(", standard=").append(standard);
        sb.append(", min_promotion_price=").append(min_promotion_price);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}