package com.mfangsoft.zhuangjialong.app.sendflow.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   流量批次回调信息表
 * table t_biz_flow_back
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class FlowBackEntity implements Serializable {
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   批次号
     * column batch_no
     *
     * @MLTH_generated
     */
    private String batch_no;

    /**
     *   成功条数
     * column success_count
     *
     * @MLTH_generated
     */
    private Integer success_count;

    /**
     *   失败条数
     * column faill_count
     *
     * @MLTH_generated
     */
    private Integer faill_count;

    /**
     *   回调失败状态码
     * column code
     *
     * @MLTH_generated
     */
    private String code;

    /**
     *   回调失败信息
     * column msg
     *
     * @MLTH_generated
     */
    private String msg;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    private Date create_time;

    /**
     *   手机号
     * column mobile
     *
     * @MLTH_generated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_flow_back
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   批次号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getBatch_no() {
        return batch_no;
    }

    /**
     *   批次号
     * @param batch_no the value for 
     *
     * @MLTH_generated
     */
    public void setBatch_no(String batch_no) {
        this.batch_no = batch_no == null ? null : batch_no.trim();
    }

    /**
     *   成功条数
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSuccess_count() {
        return success_count;
    }

    /**
     *   成功条数
     * @param success_count the value for 
     *
     * @MLTH_generated
     */
    public void setSuccess_count(Integer success_count) {
        this.success_count = success_count;
    }

    /**
     *   失败条数
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getFaill_count() {
        return faill_count;
    }

    /**
     *   失败条数
     * @param faill_count the value for 
     *
     * @MLTH_generated
     */
    public void setFaill_count(Integer faill_count) {
        this.faill_count = faill_count;
    }

    /**
     *   回调失败状态码
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getCode() {
        return code;
    }

    /**
     *   回调失败状态码
     * @param code the value for 
     *
     * @MLTH_generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     *   回调失败信息
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     *   回调失败信息
     * @param msg the value for 
     *
     * @MLTH_generated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   手机号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     *   手机号
     * @param mobile the value for 
     *
     * @MLTH_generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", batch_no=").append(batch_no);
        sb.append(", success_count=").append(success_count);
        sb.append(", faill_count=").append(faill_count);
        sb.append(", code=").append(code);
        sb.append(", msg=").append(msg);
        sb.append(", create_time=").append(create_time);
        sb.append(", mobile=").append(mobile);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}