package com.mfangsoft.zhuangjialong.app.appointment.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   预约信息表
 * table t_biz_appointment_info
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class AppointmentInfoEntity implements Serializable {
    /**
     *   主键id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   品牌ID
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     *   店铺ID
     * column shop_id
     *
     * @MLTH_generated
     */
    private Long shop_id;

    /**
     *   品类ID
     * column class_id
     *
     * @MLTH_generated
     */
    private Long class_id;

    /**
     *   预约ID
     * column appointment_id
     *
     * @MLTH_generated
     */
    private Long appointment_id;

    /**
     *   预约时间
     * column start_time
     *
     * @MLTH_generated
     */
    
    @JsonFormat(pattern="yyyy-MM-dd HH:mm",timezone="GMT+8")
    private Date start_time;

    /**
     *   结束时间
     * column end_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm",timezone="GMT+8")
    private Date end_time;

    /**
     *   1:预约已提交2:预约已确认
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     *   服务导购
     * column server_id
     *
     * @MLTH_generated
     */
    private Long server_id;

    /**
     *   预约需求
     * column needs
     *
     * @MLTH_generated
     */
    private String needs;

    /**
     *   最低价格
     * column min_price
     *
     * @MLTH_generated
     */
    private Double min_price;

    /**
     *   最高价格
     * column max_price
     *
     * @MLTH_generated
     */
    private Double max_price;

    /**
     *   预约风格ID
     * column style_id
     *
     * @MLTH_generated
     */
    private Long style_id;

    /**
     *   预约空间ID
     * column space_id
     *
     * @MLTH_generated
     */
    private Long space_id;

    /**
     *   处理信息
     * column deal_info
     *
     * @MLTH_generated
     */
    private String deal_info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_appointment_info
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   品牌ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌ID
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     *   店铺ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getShop_id() {
        return shop_id;
    }

    /**
     *   店铺ID
     * @param shop_id the value for 
     *
     * @MLTH_generated
     */
    public void setShop_id(Long shop_id) {
        this.shop_id = shop_id;
    }

    /**
     *   品类ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getClass_id() {
        return class_id;
    }

    /**
     *   品类ID
     * @param class_id the value for 
     *
     * @MLTH_generated
     */
    public void setClass_id(Long class_id) {
        this.class_id = class_id;
    }

    /**
     *   预约ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getAppointment_id() {
        return appointment_id;
    }

    /**
     *   预约ID
     * @param appointment_id the value for 
     *
     * @MLTH_generated
     */
    public void setAppointment_id(Long appointment_id) {
        this.appointment_id = appointment_id;
    }

    /**
     *   预约时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getStart_time() {
        return start_time;
    }

    /**
     *   预约时间
     * @param start_time the value for 
     *
     * @MLTH_generated
     */
    public void setStart_time(Date start_time) {
        this.start_time = start_time;
    }

    /**
     *   结束时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     *   结束时间
     * @param end_time the value for 
     *
     * @MLTH_generated
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     *   1:预约已提交2:预约已确认
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   1:预约已提交2:预约已确认
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *   服务导购
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getServer_id() {
        return server_id;
    }

    /**
     *   服务导购
     * @param server_id the value for 
     *
     * @MLTH_generated
     */
    public void setServer_id(Long server_id) {
        this.server_id = server_id;
    }

    /**
     *   预约需求
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getNeeds() {
        return needs;
    }

    /**
     *   预约需求
     * @param needs the value for 
     *
     * @MLTH_generated
     */
    public void setNeeds(String needs) {
        this.needs = needs == null ? null : needs.trim();
    }

    /**
     *   最低价格
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getMin_price() {
        return min_price;
    }

    /**
     *   最低价格
     * @param min_price the value for 
     *
     * @MLTH_generated
     */
    public void setMin_price(Double min_price) {
        this.min_price = min_price;
    }

    /**
     *   最高价格
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getMax_price() {
        return max_price;
    }

    /**
     *   最高价格
     * @param max_price the value for 
     *
     * @MLTH_generated
     */
    public void setMax_price(Double max_price) {
        this.max_price = max_price;
    }

    /**
     *   预约风格ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getStyle_id() {
        return style_id;
    }

    /**
     *   预约风格ID
     * @param style_id the value for 
     *
     * @MLTH_generated
     */
    public void setStyle_id(Long style_id) {
        this.style_id = style_id;
    }

    /**
     *   预约空间ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSpace_id() {
        return space_id;
    }

    /**
     *   预约空间ID
     * @param space_id the value for 
     *
     * @MLTH_generated
     */
    public void setSpace_id(Long space_id) {
        this.space_id = space_id;
    }

    /**
     *   处理信息
     * @return the value of LONGVARCHAR
     *
     * @MLTH_generated
     */
    public String getDeal_info() {
        return deal_info;
    }

    /**
     *   处理信息
     * @param deal_info the value for 
     *
     * @MLTH_generated
     */
    public void setDeal_info(String deal_info) {
        this.deal_info = deal_info == null ? null : deal_info.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", shop_id=").append(shop_id);
        sb.append(", class_id=").append(class_id);
        sb.append(", appointment_id=").append(appointment_id);
        sb.append(", start_time=").append(start_time);
        sb.append(", end_time=").append(end_time);
        sb.append(", state=").append(state);
        sb.append(", server_id=").append(server_id);
        sb.append(", needs=").append(needs);
        sb.append(", min_price=").append(min_price);
        sb.append(", max_price=").append(max_price);
        sb.append(", style_id=").append(style_id);
        sb.append(", space_id=").append(space_id);
        sb.append(", deal_info=").append(deal_info);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}