package com.mfangsoft.zhuangjialong.app.appointment.model;

import java.io.Serializable;
import java.util.Date;

/**
 *   预约表
 * table t_biz_appointment
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseAppointment implements Serializable {
    /**
     *   主键id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   消费者用户ID
     * column customer_id
     *
     * @MLTH_generated
     */
    private Long customer_id;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    private Date create_time;

    /**
     *   预约地址ID
     * column address_id
     *
     * @MLTH_generated
     */
    private Long address_id;

    /**
     *   预约地址
     * column address_details
     *
     * @MLTH_generated
     */
    private String address_details;

    /**
     *   预约人名称
     * column receiver_name
     *
     * @MLTH_generated
     */
    private String receiver_name;

    /**
     *   预约人联系电话
     * column phone_num
     *
     * @MLTH_generated
     */
    private String phone_num;

    /**
     *   区域编码
     * column region_code
     *
     * @MLTH_generated
     */
    private String region_code;

    /**
     *   是否浏览过
     * column seen_state
     *
     * @MLTH_generated
     */
    private Integer seen_state;

    /**
     *   户型图
     * column door_model_img
     *
     * @MLTH_generated
     */
    private String door_model_img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_appointment
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   消费者用户ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCustomer_id() {
        return customer_id;
    }

    /**
     *   消费者用户ID
     * @param customer_id the value for 
     *
     * @MLTH_generated
     */
    public void setCustomer_id(Long customer_id) {
        this.customer_id = customer_id;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   预约地址ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getAddress_id() {
        return address_id;
    }

    /**
     *   预约地址ID
     * @param address_id the value for 
     *
     * @MLTH_generated
     */
    public void setAddress_id(Long address_id) {
        this.address_id = address_id;
    }

    /**
     *   预约地址
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getAddress_details() {
        return address_details;
    }

    /**
     *   预约地址
     * @param address_details the value for 
     *
     * @MLTH_generated
     */
    public void setAddress_details(String address_details) {
        this.address_details = address_details == null ? null : address_details.trim();
    }

    /**
     *   预约人名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getReceiver_name() {
        return receiver_name;
    }

    /**
     *   预约人名称
     * @param receiver_name the value for 
     *
     * @MLTH_generated
     */
    public void setReceiver_name(String receiver_name) {
        this.receiver_name = receiver_name == null ? null : receiver_name.trim();
    }

    /**
     *   预约人联系电话
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPhone_num() {
        return phone_num;
    }

    /**
     *   预约人联系电话
     * @param phone_num the value for 
     *
     * @MLTH_generated
     */
    public void setPhone_num(String phone_num) {
        this.phone_num = phone_num == null ? null : phone_num.trim();
    }

    /**
     *   区域编码
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getRegion_code() {
        return region_code;
    }

    /**
     *   区域编码
     * @param region_code the value for 
     *
     * @MLTH_generated
     */
    public void setRegion_code(String region_code) {
        this.region_code = region_code == null ? null : region_code.trim();
    }

    /**
     *   是否浏览过
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSeen_state() {
        return seen_state;
    }

    /**
     *   是否浏览过
     * @param seen_state the value for 
     *
     * @MLTH_generated
     */
    public void setSeen_state(Integer seen_state) {
        this.seen_state = seen_state;
    }

    /**
     *   户型图
     * @return the value of LONGVARCHAR
     *
     * @MLTH_generated
     */
    public String getDoor_model_img() {
        return door_model_img;
    }

    /**
     *   户型图
     * @param door_model_img the value for 
     *
     * @MLTH_generated
     */
    public void setDoor_model_img(String door_model_img) {
        this.door_model_img = door_model_img == null ? null : door_model_img.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", customer_id=").append(customer_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", address_id=").append(address_id);
        sb.append(", address_details=").append(address_details);
        sb.append(", receiver_name=").append(receiver_name);
        sb.append(", phone_num=").append(phone_num);
        sb.append(", region_code=").append(region_code);
        sb.append(", seen_state=").append(seen_state);
        sb.append(", door_model_img=").append(door_model_img);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}