package com.mfangsoft.zhuangjialong.integration.promotion.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   活动产品表
 * table t_biz_promotion_seckill_product
 *
 * @MLTH_generated do_not_delete_during_merge
 */

@JsonInclude(value=Include.NON_NULL)
public class PromotionSeckillProductEntity implements Serializable {
    /**
     *   主键id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   活动id
     * column promotion_id
     *
     * @MLTH_generated
     */
    private Long promotion_id;

    /**
     *   秒杀时间段id
     * column time_id
     *
     * @MLTH_generated
     */
    private Long time_id;

    /**
     *   品牌id
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     *   产品id
     * column product_id
     *
     * @MLTH_generated
     */
    private Long product_id;

    private String title;
    /**
     *   秒杀价格
     * column price
     *
     * @MLTH_generated
     */
    private Double price;

    private Integer person_product_num;
    /**
     *   产品数量限制
     * column limit_num
     *
     * @MLTH_generated
     */
    private Integer limit_num;

    /**
     *   该时间段该产品已卖数量
     * column sell_num
     *
     * @MLTH_generated
     */
    private Integer sell_num;

    /**
     *   状态  0未通过审核  1通过审核
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;
    
    /**
     *   更新时间
     * column update_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date update_time;

    private String info;
    
    private Integer note_count;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_promotion_seckill_product
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   活动id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getPromotion_id() {
        return promotion_id;
    }

    /**
     *   活动id
     * @param promotion_id the value for 
     *
     * @MLTH_generated
     */
    public void setPromotion_id(Long promotion_id) {
        this.promotion_id = promotion_id;
    }

    /**
     *   秒杀时间段id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getTime_id() {
        return time_id;
    }

    /**
     *   秒杀时间段id
     * @param time_id the value for 
     *
     * @MLTH_generated
     */
    public void setTime_id(Long time_id) {
        this.time_id = time_id;
    }

    /**
     *   品牌id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌id
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     *   产品id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getProduct_id() {
        return product_id;
    }

    /**
     *   产品id
     * @param product_id the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    /**
     *   秒杀价格
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     *   秒杀价格
     * @param price the value for 
     *
     * @MLTH_generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     *   产品数量限制
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getLimit_num() {
        return limit_num;
    }

    /**
     *   产品数量限制
     * @param limit_num the value for 
     *
     * @MLTH_generated
     */
    public void setLimit_num(Integer limit_num) {
        this.limit_num = limit_num;
    }

    /**
     *   该时间段该产品已卖数量
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSell_num() {
        return sell_num;
    }

    /**
     *   该时间段该产品已卖数量
     * @param sell_num the value for 
     *
     * @MLTH_generated
     */
    public void setSell_num(Integer sell_num) {
        this.sell_num = sell_num;
    }

    /**
     *   状态  0未通过审核  1通过审核
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   状态  0未通过审核  1通过审核
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getPerson_product_num() {
		return person_product_num;
	}

	public void setPerson_product_num(Integer person_product_num) {
		this.person_product_num = person_product_num;
	}

	public Integer getNote_count() {
		return note_count;
	}

	public void setNote_count(Integer note_count) {
		this.note_count = note_count;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", promotion_id=").append(promotion_id);
        sb.append(", time_id=").append(time_id);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", product_id=").append(product_id);
        sb.append(", price=").append(price);
        sb.append(", limit_num=").append(limit_num);
        sb.append(", sell_num=").append(sell_num);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}