package com.mfangsoft.zhuangjialong.integration.promotion.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   活动表
 * table t_biz_promotion
 *
 * @MLTH_generated do_not_delete_during_merge
 */

@JsonInclude(value=Include.NON_NULL)
public class PromotionEntity implements Serializable {
	
	private List<PromotionSeckillTimeEntity> timeEntity;
	private String customer_region_code;
	private String class_name;
	private String principal;
	private Integer brand_id_count;
	private Integer has_registered_flag;
	private String brand_ids;
	
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   活动标题
     * column title
     *
     * @MLTH_generated
     */
    private String title;

    /**
     *  0秒杀 1 满额减 2 满额折 3满量折扣
     * column type
     *
     * @MLTH_generated
     */
    private Integer type;

    /**
     *   创建人
     * column creater
     *
     * @MLTH_generated
     */
    private Long creater;

    /**
     *   0 平台商 1：合伙人 2：品牌
     * column creater_type
     *
     * @MLTH_generated
     */
    private Integer creater_type;

    /**
     *   创建日期
     * column create_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date create_time;

    /**
     *   更新时间
     * column update_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date update_time;

    /**
     *   参加截止时间
     * column limit_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date limit_time;

    /**
     *   活动开始时间
     * column start_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date start_time;

    /**
     *   活动结束时间
     * column end_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date end_time;

    /**
     *   活动状态 0未上线 1 上线
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     *   活动产品数量,秒杀:每品牌提交商品总数
     * column promotion_product_num
     *
     * @MLTH_generated
     */
    private Integer promotion_product_num;

    /**
     *   没人限购数量
     * column person_product_num
     *
     * @MLTH_generated
     */
    private Integer person_product_num;

    /**
     *   品牌ID
     * column brand_id
     *
     * @MLTH_generated
     */
    private String brand_id;

    /**
     *   品类ID
     * column class_id
     *
     * @MLTH_generated
     */
    private String class_id;

    /**
     *   合伙人ID
     * column partner_id
     *
     * @MLTH_generated
     */
    private String partner_id;

    /**
     *   区域ID 数组
     * column region_code
     *
     * @MLTH_generated
     */
    private String region_code;

    /**
     *   图片
     * column imgurl1
     *
     * @MLTH_generated
     */
    private String imgurl1;

    /**
     *   图片
     * column imgurl2
     *
     * @MLTH_generated
     */
    private String imgurl2;

    /**
     *   图片
     * column imgurl3
     *
     * @MLTH_generated
     */
    private String imgurl3;

    /**
     *   预留位置
     * column var1
     *
     * @MLTH_generated
     */
    private Integer var1;

    /**
     *   预留位置
     * column var2
     *
     * @MLTH_generated
     */
    private Integer var2;

    /**
     *   预留位置
     * column var3
     *
     * @MLTH_generated
     */
    private String var3;

    /**
     *   预留位置
     * column var4
     *
     * @MLTH_generated
     */
    private String var4;

    /**
     *   活动内容
     * column content
     *
     * @MLTH_generated
     */
    private String content;
    
    private Boolean use_coupons_flag;
    
    private Boolean use_redbag_flag;
    
    private Boolean use_zhekou_flag;
    
    private Integer isAllProduct;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_promotion
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   活动标题
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getTitle() {
        return title;
    }

    /**
     *   活动标题
     * @param title the value for 
     *
     * @MLTH_generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     *   0秒杀 1 满减
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getType() {
        return type;
    }

    /**
     *   0秒杀 1 满减
     * @param type the value for 
     *
     * @MLTH_generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     *   创建人
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCreater() {
        return creater;
    }

    /**
     *   创建人
     * @param creater the value for 
     *
     * @MLTH_generated
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     *   0 平台商 1：合伙人 2：品牌
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getCreater_type() {
        return creater_type;
    }

    /**
     *   0 平台商 1：合伙人 2：品牌
     * @param creater_type the value for 
     *
     * @MLTH_generated
     */
    public void setCreater_type(Integer creater_type) {
        this.creater_type = creater_type;
    }

    /**
     *   创建日期
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建日期
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   更新时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     *   更新时间
     * @param update_time the value for 
     *
     * @MLTH_generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     *   参加截止时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getLimit_time() {
        return limit_time;
    }

    /**
     *   参加截止时间
     * @param limit_time the value for 
     *
     * @MLTH_generated
     */
    public void setLimit_time(Date limit_time) {
        this.limit_time = limit_time;
    }

    /**
     *   活动开始时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getStart_time() {
        return start_time;
    }

    /**
     *   活动开始时间
     * @param start_time the value for 
     *
     * @MLTH_generated
     */
    public void setStart_time(Date start_time) {
        this.start_time = start_time;
    }

    /**
     *   活动结束时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     *   活动结束时间
     * @param end_time the value for 
     *
     * @MLTH_generated
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     *   活动状态 0未上线 1 上线
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   活动状态 0未上线 1 上线
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *   活动产品数量,秒杀:每品牌提交商品总数
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getPromotion_product_num() {
        return promotion_product_num;
    }

    /**
     *   活动产品数量,秒杀:每品牌提交商品总数
     * @param promotion_product_num the value for 
     *
     * @MLTH_generated
     */
    public void setPromotion_product_num(Integer promotion_product_num) {
        this.promotion_product_num = promotion_product_num;
    }

    /**
     *   没人限购数量
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getPerson_product_num() {
        return person_product_num;
    }

    /**
     *   没人限购数量
     * @param person_product_num the value for 
     *
     * @MLTH_generated
     */
    public void setPerson_product_num(Integer person_product_num) {
        this.person_product_num = person_product_num;
    }

    /**
     *   品牌ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public String getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌ID
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(String brand_id) {
        this.brand_id = brand_id;
    }

    /**
     *   品类ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */

    /**
     *   区域ID 数组
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getRegion_code() {
        return region_code;
    }

    public String getClass_id() {
		return class_id;
	}

	public void setClass_id(String class_id) {
		this.class_id = class_id;
	}

	public String getPartner_id() {
		return partner_id;
	}

	public void setPartner_id(String partner_id) {
		this.partner_id = partner_id;
	}

	/**
     *   区域ID 数组
     * @param region_code the value for 
     *
     * @MLTH_generated
     */
    public void setRegion_code(String region_code) {
        this.region_code = region_code == null ? null : region_code.trim();
    }

    /**
     *   图片
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImgurl1() {
        return imgurl1;
    }

    /**
     *   图片
     * @param imgurl1 the value for 
     *
     * @MLTH_generated
     */
    public void setImgurl1(String imgurl1) {
        this.imgurl1 = imgurl1 == null ? null : imgurl1.trim();
    }

    /**
     *   图片
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImgurl2() {
        return imgurl2;
    }

    /**
     *   图片
     * @param imgurl2 the value for 
     *
     * @MLTH_generated
     */
    public void setImgurl2(String imgurl2) {
        this.imgurl2 = imgurl2 == null ? null : imgurl2.trim();
    }

    /**
     *   图片
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImgurl3() {
        return imgurl3;
    }

    /**
     *   图片
     * @param imgurl3 the value for 
     *
     * @MLTH_generated
     */
    public void setImgurl3(String imgurl3) {
        this.imgurl3 = imgurl3 == null ? null : imgurl3.trim();
    }

    /**
     *   预留位置
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getVar1() {
        return var1;
    }

    /**
     *   预留位置
     * @param var1 the value for 
     *
     * @MLTH_generated
     */
    public void setVar1(Integer var1) {
        this.var1 = var1;
    }

    /**
     *   预留位置
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getVar2() {
        return var2;
    }

    /**
     *   预留位置
     * @param var2 the value for 
     *
     * @MLTH_generated
     */
    public void setVar2(Integer var2) {
        this.var2 = var2;
    }

    /**
     *   预留位置
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getVar3() {
        return var3;
    }

    /**
     *   预留位置
     * @param var3 the value for 
     *
     * @MLTH_generated
     */
    public void setVar3(String var3) {
        this.var3 = var3 == null ? null : var3.trim();
    }

    /**
     *   预留位置
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getVar4() {
        return var4;
    }

    /**
     *   预留位置
     * @param var4 the value for 
     *
     * @MLTH_generated
     */
    public void setVar4(String var4) {
        this.var4 = var4 == null ? null : var4.trim();
    }

    /**
     *   活动内容
     * @return the value of LONGVARCHAR
     *
     * @MLTH_generated
     */
    public String getContent() {
        return content;
    }

    /**
     *   活动内容
     * @param content the value for 
     *
     * @MLTH_generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	public List<PromotionSeckillTimeEntity> getTimeEntity() {
		return timeEntity;
	}

	public void setTimeEntity(List<PromotionSeckillTimeEntity> timeEntity) {
		this.timeEntity = timeEntity;
	}

	public String getCustomer_region_code() {
		return customer_region_code;
	}

	public void setCustomer_region_code(String customer_region_code) {
		this.customer_region_code = customer_region_code;
	}

	public String getClass_name() {
		return class_name;
	}

	public void setClass_name(String class_name) {
		this.class_name = class_name;
	}

	public String getPrincipal() {
		return principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	public Integer getBrand_id_count() {
		return brand_id_count;
	}

	public void setBrand_id_count(Integer brand_id_count) {
		this.brand_id_count = brand_id_count;
	}

	public Integer getHas_registered_flag() {
		return has_registered_flag;
	}

	public void setHas_registered_flag(Integer has_registered_flag) {
		this.has_registered_flag = has_registered_flag;
	}

	public String getBrand_ids() {
		return brand_ids;
	}

	public void setBrand_ids(String brand_ids) {
		this.brand_ids = brand_ids;
	}

	public Boolean getUse_coupons_flag() {
		return use_coupons_flag;
	}

	public void setUse_coupons_flag(Boolean use_coupons_flag) {
		this.use_coupons_flag = use_coupons_flag;
	}

	public Boolean getUse_redbag_flag() {
		return use_redbag_flag;
	}

	public void setUse_redbag_flag(Boolean use_redbag_flag) {
		this.use_redbag_flag = use_redbag_flag;
	}

	public Boolean getUse_zhekou_flag() {
		return use_zhekou_flag;
	}

	public void setUse_zhekou_flag(Boolean use_zhekou_flag) {
		this.use_zhekou_flag = use_zhekou_flag;
	}

	public Integer getIsAllProduct() {
		return isAllProduct;
	}

	public void setIsAllProduct(Integer isAllProduct) {
		this.isAllProduct = isAllProduct;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", type=").append(type);
        sb.append(", creater=").append(creater);
        sb.append(", creater_type=").append(creater_type);
        sb.append(", create_time=").append(create_time);
        sb.append(", update_time=").append(update_time);
        sb.append(", limit_time=").append(limit_time);
        sb.append(", start_time=").append(start_time);
        sb.append(", end_time=").append(end_time);
        sb.append(", state=").append(state);
        sb.append(", promotion_product_num=").append(promotion_product_num);
        sb.append(", person_product_num=").append(person_product_num);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", class_id=").append(class_id);
        sb.append(", partner_id=").append(partner_id);
        sb.append(", region_code=").append(region_code);
        sb.append(", imgurl1=").append(imgurl1);
        sb.append(", imgurl2=").append(imgurl2);
        sb.append(", imgurl3=").append(imgurl3);
        sb.append(", var1=").append(var1);
        sb.append(", var2=").append(var2);
        sb.append(", var3=").append(var3);
        sb.append(", var4=").append(var4);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}