package com.mfangsoft.zhuangjialong.integration.promotion.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_biz_promotion_zhekou
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class PromotionZhekouEntity implements Serializable {
    /**
     *   id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   类型 1统一折扣
     * column type
     *
     * @MLTH_generated
     */
    private Integer type;
    
    private String content;

    /**
     *   起止时间
     * column start_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date start_time;

    /**
     *   结束时间
     * column end_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date end_time;

    /**
     *   品牌id
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     *   折扣力度
     * column discount
     *
     * @MLTH_generated
     */
    private Double discount;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    private Date create_time;

    /**
     *   更新时间
     * column update_time
     *
     * @MLTH_generated
     */
    private Date update_time;

    /**
     *   是否使用优惠券
     * column use_coupons_flag
     *
     * @MLTH_generated
     */
    private Boolean use_coupons_flag;

    /**
     *   是否使用红包
     * column use_redbag_flag
     *
     * @MLTH_generated
     */
    private Boolean use_redbag_flag;

    /**
     *   是否使用折扣券
     * column use_zhekou_flag
     *
     * @MLTH_generated
     */
    private Boolean use_zhekou_flag;

    /**
     *   名字
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    private Integer state;
    
    private Integer isAllProduct;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_promotion_zhekou
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   类型 1统一折扣
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getType() {
        return type;
    }

    /**
     *   类型 1统一折扣
     * @param type the value for 
     *
     * @MLTH_generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     *   起止时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getStart_time() {
        return start_time;
    }

    /**
     *   起止时间
     * @param start_time the value for 
     *
     * @MLTH_generated
     */
    public void setStart_time(Date start_time) {
        this.start_time = start_time;
    }

    /**
     *   结束时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     *   结束时间
     * @param end_time the value for 
     *
     * @MLTH_generated
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     *   品牌id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌id
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     *   折扣力度
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     *   折扣力度
     * @param discount the value for 
     *
     * @MLTH_generated
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   更新时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     *   更新时间
     * @param update_time the value for 
     *
     * @MLTH_generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     *   是否使用优惠券
     * @return the value of BIT
     *
     * @MLTH_generated
     */
    public Boolean getUse_coupons_flag() {
        return use_coupons_flag;
    }

    /**
     *   是否使用优惠券
     * @param use_coupons_flag the value for 
     *
     * @MLTH_generated
     */
    public void setUse_coupons_flag(Boolean use_coupons_flag) {
        this.use_coupons_flag = use_coupons_flag;
    }

    /**
     *   是否使用红包
     * @return the value of BIT
     *
     * @MLTH_generated
     */
    public Boolean getUse_redbag_flag() {
        return use_redbag_flag;
    }

    /**
     *   是否使用红包
     * @param use_redbag_flag the value for 
     *
     * @MLTH_generated
     */
    public void setUse_redbag_flag(Boolean use_redbag_flag) {
        this.use_redbag_flag = use_redbag_flag;
    }

    /**
     *   是否使用折扣券
     * @return the value of BIT
     *
     * @MLTH_generated
     */
    public Boolean getUse_zhekou_flag() {
        return use_zhekou_flag;
    }

    /**
     *   是否使用折扣券
     * @param use_zhekou_flag the value for 
     *
     * @MLTH_generated
     */
    public void setUse_zhekou_flag(Boolean use_zhekou_flag) {
        this.use_zhekou_flag = use_zhekou_flag;
    }

    /**
     *   名字
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   名字
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Integer getIsAllProduct() {
		return isAllProduct;
	}

	public void setIsAllProduct(Integer isAllProduct) {
		this.isAllProduct = isAllProduct;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", start_time=").append(start_time);
        sb.append(", end_time=").append(end_time);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", discount=").append(discount);
        sb.append(", create_time=").append(create_time);
        sb.append(", update_time=").append(update_time);
        sb.append(", use_coupons_flag=").append(use_coupons_flag);
        sb.append(", use_redbag_flag=").append(use_redbag_flag);
        sb.append(", use_zhekou_flag=").append(use_zhekou_flag);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}