package com.mfangsoft.zhuangjialong.integration.promotion.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_biz_promotion_step_product
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class PromotionStepProductEntity implements Serializable {
    /**
     *   id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   活动id
     * column promotion_id
     *
     * @MLTH_generated
     */
    private Long promotion_id;

    /**
     *   产品id
     * column product_id
     *
     * @MLTH_generated
     */
    private Long product_id;

    /**
     *   品牌id
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     *   时间记录
     * column note_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date note_time;

    /**
     *   状态 0未审核 1通过审核 2 审核未通过 3 申请下架 4 下架 5申请取消
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    private String title;
    
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_promotion_step_product
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   活动id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getPromotion_id() {
        return promotion_id;
    }

    /**
     *   活动id
     * @param promotion_id the value for 
     *
     * @MLTH_generated
     */
    public void setPromotion_id(Long promotion_id) {
        this.promotion_id = promotion_id;
    }

    /**
     *   产品id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getProduct_id() {
        return product_id;
    }

    /**
     *   产品id
     * @param product_id the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    /**
     *   品牌id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌id
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     *   时间记录
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getNote_time() {
        return note_time;
    }

    /**
     *   时间记录
     * @param note_time the value for 
     *
     * @MLTH_generated
     */
    public void setNote_time(Date note_time) {
        this.note_time = note_time;
    }

    /**
     *   状态 0未审核 1通过审核 2 审核未通过 3 申请下架 4 下架 5申请取消
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   状态 0未审核 1通过审核 2 审核未通过 3 申请下架 4 下架 5申请取消
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", promotion_id=").append(promotion_id);
        sb.append(", product_id=").append(product_id);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", note_time=").append(note_time);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}