package com.mfangsoft.zhuangjialong.integration.promotion.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_biz_promotion_step_condition
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class PromotionStepConditionEntity implements Serializable {
    /**
     *   id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   活动id
     * column promotion_id
     *
     * @MLTH_generated
     */
    private Long promotion_id;

    /**
     *   阶梯值1
     * column value1
     *
     * @MLTH_generated
     */
    private Integer value1;

    /**
     *   阶梯值1
     * column value2
     *
     * @MLTH_generated
     */
    private Integer value2;

    /**
     *   优惠力度
     * column discount
     *
     * @MLTH_generated
     */
    private Double discount;

    /**
     *   时间记录值
     * column note_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date note_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_promotion_step_condition
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   活动id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getPromotion_id() {
        return promotion_id;
    }

    /**
     *   活动id
     * @param promotion_id the value for 
     *
     * @MLTH_generated
     */
    public void setPromotion_id(Long promotion_id) {
        this.promotion_id = promotion_id;
    }

    /**
     *   阶梯值1
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getValue1() {
        return value1;
    }

    /**
     *   阶梯值1
     * @param value1 the value for 
     *
     * @MLTH_generated
     */
    public void setValue1(Integer value1) {
        this.value1 = value1;
    }

    /**
     *   阶梯值1
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getValue2() {
        return value2;
    }

    /**
     *   阶梯值1
     * @param value2 the value for 
     *
     * @MLTH_generated
     */
    public void setValue2(Integer value2) {
        this.value2 = value2;
    }

    /**
     *   优惠力度
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     *   优惠力度
     * @param discount the value for 
     *
     * @MLTH_generated
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     *   时间记录值
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getNote_time() {
        return note_time;
    }

    /**
     *   时间记录值
     * @param note_time the value for 
     *
     * @MLTH_generated
     */
    public void setNote_time(Date note_time) {
        this.note_time = note_time;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", promotion_id=").append(promotion_id);
        sb.append(", value1=").append(value1);
        sb.append(", value2=").append(value2);
        sb.append(", discount=").append(discount);
        sb.append(", note_time=").append(note_time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}