package com.mfangsoft.zhuangjialong.integration.promotion.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.mfangsoft.zhuangjialong.app.product.model.Product;

/**
 * table t_biz_promotion_seckill_time
 *
 * @MLTH_generated do_not_delete_during_merge
 */

@JsonInclude(value=Include.NON_NULL)
public class PromotionSeckillTimeEntity implements Serializable {
	private List<PromotionSeckillProductEntity> product;
	private Boolean iscurrent;
	private Integer brand_id_count;
	private Integer has_registered_flag;
	private Date now_time;
	
	

	/**
	 * @return the now_time
	 */
	public Date getNow_time() {
		return now_time;
	}

	/**
	 * @param now_time the now_time to set
	 */
	public void setNow_time(Date now_time) {
		this.now_time = now_time;
	}

	/**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   活动id
     * column pid
     *
     * @MLTH_generated
     */
    private Long pid;

    /**
     *   秒杀段开始时间
     * column pstart_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="HH:mm",timezone="GMT+8")
    private Date pstart_time;

    private String pstart_time_str;
    /**
     *   秒杀段结束时间
     * column pend_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="HH:mm",timezone="GMT+8")
    private Date pend_time;

    private String pend_time_str;
    
    private Integer promotion_brand_num;
    
    private String brand_id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_promotion_seckill_time
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    public Integer getBrand_id_count() {
		return brand_id_count;
	}

	public void setBrand_id_count(Integer brand_id_count) {
		this.brand_id_count = brand_id_count;
	}

	public Integer getPromotion_brand_num() {
		return promotion_brand_num;
	}

	public void setPromotion_brand_num(Integer promotion_brand_num) {
		this.promotion_brand_num = promotion_brand_num;
	}

	public String getBrand_id() {
		return brand_id;
	}

	public void setBrand_id(String brand_id) {
		this.brand_id = brand_id;
	}

	public List<PromotionSeckillProductEntity> getProduct() {
		return product;
	}

	public void setProduct(List<PromotionSeckillProductEntity> product) {
		this.product = product;
	}

	public Boolean getIscurrent() {
		return iscurrent;
	}

	public void setIscurrent(Boolean iscurrent) {
		this.iscurrent = iscurrent;
	}

	public String getPstart_time_str() {
		return pstart_time_str;
	}

	public void setPstart_time_str(String pstart_time_str) {
		this.pstart_time_str = pstart_time_str;
	}

	public String getPend_time_str() {
		return pend_time_str;
	}

	public void setPend_time_str(String pend_time_str) {
		this.pend_time_str = pend_time_str;
	}

	/**
     *   主键
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   活动id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     *   活动id
     * @param pid the value for 
     *
     * @MLTH_generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     *   秒杀段开始时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getPstart_time() {
        return pstart_time;
    }

    /**
     *   秒杀段开始时间
     * @param pstart_time the value for 
     *
     * @MLTH_generated
     */
    public void setPstart_time(Date pstart_time) {
        this.pstart_time = pstart_time;
    }

    /**
     *   秒杀段结束时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getPend_time() {
        return pend_time;
    }

    /**
     *   秒杀段结束时间
     * @param pend_time the value for 
     *
     * @MLTH_generated
     */
    public void setPend_time(Date pend_time) {
        this.pend_time = pend_time;
    }

    public Integer getHas_registered_flag() {
		return has_registered_flag;
	}

	public void setHas_registered_flag(Integer has_registered_flag) {
		this.has_registered_flag = has_registered_flag;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pid=").append(pid);
        sb.append(", pstart_time=").append(pstart_time);
        sb.append(", pend_time=").append(pend_time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}