package com.mfangsoft.zhuangjialong.integration.promotion.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.mfangsoft.zhuangjialong.app.brand.model.Brand;

/**
 * table t_biz_unionpromotion
 *
 * @MLTH_generated do_not_delete_during_merge
 */

/**
* @description：
* @author：Jianghua.Tang 
* @date：2016年7月22日
* 
*/
@JsonInclude(value=Include.NON_NULL)
public class UnionPromotion implements Serializable {
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   促销标题
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date create_time;
    
    
    /*
     * 倒计时
     */
    private Long cash_time;
 
	/**
	 * @return the cash_time
	 */
	public Long getCash_time() {
		return cash_time;
	}

	/**
	 * @param cash_time the cash_time to set
	 */
	public void setCash_time(Long cash_time) {
		this.cash_time = cash_time;
	}
	/**
     *   开始时间
     * column start_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date start_time;

    /**
     *   结束时间
     * column end_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date end_time;
    /**
     *   报名截止时间
     * column apply_end_time
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date apply_end_time;
   /**
     *   活动规则
     * column rule
     *
     * @MLTH_generated
     */
    private String rule;

    /**
     *   参与品牌
     * column brand_ids
     *
     * @MLTH_generated
     */
    private String brand_ids;

    /**
     *   创建人(城市合伙人)
     * column partner_id
     *
     * @MLTH_generated
     */
    private Long partner_id;

    /**
     *   修改时间
     * column update_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date update_time;

    /**
     *   活动状态（0过期1进行中））
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;
    /**
     *   上下架状态（0:下架;1:上架））
     * column state
     *
     * @MLTH_generated
     */
    private Integer onOffFlag;
    /**
     *   折扣
     * column discount
     *
     * @MLTH_generated
     */
    private Double discount;

    /**
     *   现金券面额
     * column cash_value
     *
     * @MLTH_generated
     */
    private Double cash_value;

    /**
     *   现金券价格
     * column price
     *
     * @MLTH_generated
     */
    private Double price;

    /**
     *   现金券标题
     * column title
     *
     * @MLTH_generated
     */
    private String title;

    /**
     *   现金券详情
     * column details
     *
     * @MLTH_generated
     */
    private String details;

    /**
     *   联盟促销图
     * column images
     *
     * @MLTH_generated
     */
    private String images;

    /**
     *   联盟促销封面图
     * column image
     *
     * @MLTH_generated
     */
    private String image;
   
    private Integer count;

    /**
     *   产品id
     * column product_id
     *
     * @MLTH_generated
     */
    private Long product_id;
    private Integer total_flag;
    /**
     * 现金券促销价
     */
    private Double cash_prom_price;
    /**
     * 现金券促销开始时间
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date cash_start_time;
    /**
     * 现金券促销结束时间
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date cash_end_time;
    /**
     * 现金券促销数
     */
    private Integer cash_prom_num;
    /**
     * 现金券已促销数
     */
    private Integer cash_sell_num;
    /**
     * 现金券是否促销标识(0:否;1:是)
     */
    private Integer cash_promotion_flag;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_unionpromotion
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Long getProduct_id() {
		return product_id;
	}

	public void setProduct_id(Long product_id) {
		this.product_id = product_id;
	}

	/**
     *   主键
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }
    private List<Brand> brands;
    
    /**
	 * @return the brands
	 */
	public List<Brand> getBrands() {
		return brands;
	}

	/**
	 * @param brands the brands to set
	 */
	public void setBrands(List<Brand> brands) {
		this.brands = brands;
	}
	
	
	private String totalflag;
	
	public String getTotalflag() {
		return totalflag;
	}

	public void setTotalflag(String totalflag) {
		this.totalflag = totalflag;
	}
	public List<UnionProduct> unionProducts;

	public List<UnionProduct> getUnionProducts() {
		return unionProducts;
	}

	public void setUnionProducts(List<UnionProduct> unionProducts) {
		this.unionProducts = unionProducts;
	}

	/**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   促销标题
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   促销标题
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   开始时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getStart_time() {
        return start_time;
    }

    /**
     *   开始时间
     * @param start_time the value for 
     *
     * @MLTH_generated
     */
    public void setStart_time(Date start_time) {
        this.start_time = start_time;
    }
    /**
     * 报名截止时间
     * @return
     */
    public Date getApply_end_time() {
		return apply_end_time;
	}

	public void setApply_end_time(Date apply_end_time) {
		this.apply_end_time = apply_end_time;
	}
    /**
     *   结束时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     *   结束时间
     * @param end_time the value for 
     *
     * @MLTH_generated
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     *   活动规则
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getRule() {
        return rule;
    }

    /**
     *   活动规则
     * @param rule the value for 
     *
     * @MLTH_generated
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     *   参与品牌
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getBrand_ids() {
        return brand_ids;
    }

    /**
     *   参与品牌
     * @param brand_ids the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_ids(String brand_ids) {
        this.brand_ids = brand_ids == null ? null : brand_ids.trim();
    }

    /**
     *   创建人(城市合伙人)
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getPartner_id() {
        return partner_id;
    }

    /**
     *   创建人(城市合伙人)
     * @param partner_id the value for 
     *
     * @MLTH_generated
     */
    public void setPartner_id(Long partner_id) {
        this.partner_id = partner_id;
    }

    /**
     *   修改时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     *   修改时间
     * @param update_time the value for 
     *
     * @MLTH_generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     *   活动状态（0过期1进行中））
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   活动状态（0过期1进行中））
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *   折扣
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     *   折扣
     * @param discount the value for 
     *
     * @MLTH_generated
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     *   现金券面额
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getCash_value() {
        return cash_value;
    }

    /**
     *   现金券面额
     * @param cash_value the value for 
     *
     * @MLTH_generated
     */
    public void setCash_value(Double cash_value) {
        this.cash_value = cash_value;
    }

    /**
     *   现金券价格
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     *   现金券价格
     * @param price the value for 
     *
     * @MLTH_generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     *   现金券标题
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getTitle() {
        return title;
    }

    /**
     *   现金券标题
     * @param title the value for 
     *
     * @MLTH_generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     *   现金券详情
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getDetails() {
        return details;
    }

    /**
     *   现金券详情
     * @param details the value for 
     *
     * @MLTH_generated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     *   联盟促销图
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImages() {
        return images;
    }

    /**
     *   联盟促销图
     * @param images the value for 
     *
     * @MLTH_generated
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     *   联盟促销封面图
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImage() {
        return image;
    }

    /**
     *   联盟促销封面图
     * @param image the value for 
     *
     * @MLTH_generated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", create_time=").append(create_time);
        sb.append(", start_time=").append(start_time);
        sb.append(", end_time=").append(end_time);
        sb.append(", rule=").append(rule);
        sb.append(", brand_ids=").append(brand_ids);
        sb.append(", partner_id=").append(partner_id);
        sb.append(", update_time=").append(update_time);
        sb.append(", state=").append(state);
        sb.append(", discount=").append(discount);
        sb.append(", cash_value=").append(cash_value);
        sb.append(", price=").append(price);
        sb.append(", title=").append(title);
        sb.append(", details=").append(details);
        sb.append(", images=").append(images);
        sb.append(", image=").append(image);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
    
    private String[] topImages;

	/**
	 * @return the topImages
	 */
	public String[] getTopImages() {
		return topImages;
	}

	/**
	 * @param topImages the topImages to set
	 */
	public void setTopImages(String[] topImages) {
		this.topImages = topImages;
	}
    
    private Integer sales_num;

	/**
	 * @return the sales_num
	 */
	public Integer getSales_num() {
		return sales_num;
	}

	/**
	 * @param sales_num the sales_num to set
	 */
	public void setSales_num(Integer sales_num) {
		this.sales_num = sales_num;
	}
    
	private String [] detail;

	/**
	 * @return the detail
	 */
	public String[] getDetail() {
		return detail;
	}

	/**
	 * @param detail the detail to set
	 */
	public void setDetail(String[] detail) {
		this.detail = detail;
	}
	
	private Boolean cash_state;

	
	
	private Integer cstate;

	
	
	private Integer ca_state;

	/**
	 * @return the cash_state
	 */
	public Boolean getCash_state() {
		return cash_state;
	}

	/**
	 * @param cash_state the cash_state to set
	 */
	public void setCash_state(Boolean cash_state) {
		this.cash_state = cash_state;
	}

	/**
	 * @return the cstate
	 */
	public Integer getCstate() {
		return cstate;
	}

	/**
	 * @param cstate the cstate to set
	 */
	public void setCstate(Integer cstate) {
		this.cstate = cstate;
	}

	/**
	 * @return the ca_state
	 */
	public Integer getCa_state() {
		return ca_state;
	}

	/**
	 * @param ca_state the ca_state to set
	 */
	public void setCa_state(Integer ca_state) {
		this.ca_state = ca_state;
	}

	private String info;

	/**
	 * @return the info
	 */
	public String getInfo() {
		return info;
	}

	/**
	 * @param info the info to set
	 */
	public void setInfo(String info) {
		this.info = info;
	}

	public Integer getTotal_flag() {
		return total_flag;
	}

	public void setTotal_flag(Integer total_flag) {
		this.total_flag = total_flag;
	}

	public Integer getOnOffFlag() {
		return onOffFlag;
	}

	public void setOnOffFlag(Integer onOffFlag) {
		this.onOffFlag = onOffFlag;
	}
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
   private Date buy_time;

/**
 * @return the buy_time
 */
public Date getBuy_time() {
	return buy_time;
}

/**
 * @param buy_time the buy_time to set
 */
public void setBuy_time(Date buy_time) {
	this.buy_time = buy_time;
}

public Double getCash_prom_price() {
	return cash_prom_price;
}

public void setCash_prom_price(Double cash_prom_price) {
	this.cash_prom_price = cash_prom_price;
}

public Date getCash_start_time() {
	return cash_start_time;
}

public void setCash_start_time(Date cash_start_time) {
	this.cash_start_time = cash_start_time;
}

public Date getCash_end_time() {
	return cash_end_time;
}

public void setCash_end_time(Date cash_end_time) {
	this.cash_end_time = cash_end_time;
}

public Integer getCash_prom_num() {
	return cash_prom_num;
}

public void setCash_prom_num(Integer cash_prom_num) {
	this.cash_prom_num = cash_prom_num;
}

public Integer getCash_sell_num() {
	return cash_sell_num;
}

public void setCash_sell_num(Integer cash_sell_num) {
	this.cash_sell_num = cash_sell_num;
}

public Integer getCash_promotion_flag() {
	return cash_promotion_flag;
}

public void setCash_promotion_flag(Integer cash_promotion_flag) {
	this.cash_promotion_flag = cash_promotion_flag;
}
	
   public boolean check(){
	   
	   if(discount != null && start_time.getTime() < System.currentTimeMillis() && end_time.getTime() > System.currentTimeMillis() && onOffFlag.equals(1) ){
		   return true;
	   }
	   return false;
   }
   
	
}