package com.mfangsoft.zhuangjialong.integration.promotion.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_biz_unionpro_product
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class UnionProduct implements Serializable {
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   联盟活动id
     * column promotion_id
     *
     * @MLTH_generated
     */
    private Integer promotion_id;

    /**
     *   品牌id
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     *   产品id
     * column product_id
     *
     * @MLTH_generated
     */
    private Long product_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_unionpro_product
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   联盟活动id
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getPromotion_id() {
        return promotion_id;
    }

    /**
     *   联盟活动id
     * @param promotion_id the value for 
     *
     * @MLTH_generated
     */
    public void setPromotion_id(Integer promotion_id) {
        this.promotion_id = promotion_id;
    }

    /**
     *   品牌id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌id
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     *   产品id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getProduct_id() {
        return product_id;
    }

    /**
     *   产品id
     * @param product_id the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", promotion_id=").append(promotion_id);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", product_id=").append(product_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}