package com.mfangsoft.zhuangjialong.integration.promotion.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_biz_cash_customer
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class UnionCustomer implements Serializable {
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   联盟活动id
     * column promotion_id
     *
     * @MLTH_generated
     */
    private Integer promotion_id;

    /**
     *   消费者id
     * column customer_id
     *
     * @MLTH_generated
     */
    private Long customer_id;

    /**
     *   使用状态（0已使用1未使用）
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date create_time;

    /**
     *   使用时间
     * column use_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date use_time;
    
    private String order_code;

    private String product_order_code;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_cash_customer
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   联盟活动id
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getPromotion_id() {
        return promotion_id;
    }

    /**
     *   联盟活动id
     * @param promotion_id the value for 
     *
     * @MLTH_generated
     */
    public void setPromotion_id(Integer promotion_id) {
        this.promotion_id = promotion_id;
    }

    /**
     *   消费者id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCustomer_id() {
        return customer_id;
    }

    /**
     *   消费者id
     * @param customer_id the value for 
     *
     * @MLTH_generated
     */
    public void setCustomer_id(Long customer_id) {
        this.customer_id = customer_id;
    }

    /**
     *   使用状态（0已使用1未使用）
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   使用状态（0已使用1未使用）
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   使用时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getUse_time() {
        return use_time;
    }

    /**
     *   使用时间
     * @param use_time the value for 
     *
     * @MLTH_generated
     */
    public void setUse_time(Date use_time) {
        this.use_time = use_time;
    }

    public String getOrder_code() {
		return order_code;
	}

	public void setOrder_code(String order_code) {
		this.order_code = order_code;
	}

	public String getProduct_order_code() {
		return product_order_code;
	}

	public void setProduct_order_code(String product_order_code) {
		this.product_order_code = product_order_code;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", promotion_id=").append(promotion_id);
        sb.append(", customer_id=").append(customer_id);
        sb.append(", state=").append(state);
        sb.append(", create_time=").append(create_time);
        sb.append(", use_time=").append(use_time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}