package com.mfangsoft.zhuangjialong.integration.enterprise.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_biz_enterprise_two
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class BaseEnterpriseTwoEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   名称
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     *   一级分类
     * column one_id
     *
     * @MLTH_generated
     */
    private Long one_id;

    /**
     *   图片地址
     * column img_url
     *
     * @MLTH_generated
     */
    private String img_url;

    /**
     *   图片宽度
     * column width
     *
     * @MLTH_generated
     */
    private Integer width;

    /**
     *   图片高度
     * column height
     *
     * @MLTH_generated
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_enterprise_two
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   名称
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *   一级分类
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getOne_id() {
        return one_id;
    }

    /**
     *   一级分类
     * @param one_id the value for 
     *
     * @MLTH_generated
     */
    public void setOne_id(Long one_id) {
        this.one_id = one_id;
    }

    /**
     *   图片地址
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImg_url() {
        return img_url;
    }

    /**
     *   图片地址
     * @param img_url the value for 
     *
     * @MLTH_generated
     */
    public void setImg_url(String img_url) {
        this.img_url = img_url == null ? null : img_url.trim();
    }

    /**
     *   图片宽度
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     *   图片宽度
     * @param width the value for 
     *
     * @MLTH_generated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     *   图片高度
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     *   图片高度
     * @param height the value for 
     *
     * @MLTH_generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", one_id=").append(one_id);
        sb.append(", img_url=").append(img_url);
        sb.append(", width=").append(width);
        sb.append(", height=").append(height);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}