package com.mfangsoft.zhuangjialong.integration.enterprise.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   品类表
 * table t_biz_build_class
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class BuildClassEntity implements Serializable {
    /**
     *   品类id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   品类名称
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     *   基础属性表
     * column base_table
     *
     * @MLTH_generated
     */
    private String base_table;

    /**
     *   销售属性表
     * column sales_table
     *
     * @MLTH_generated
     */
    private String sales_table;

    /**
     *   建材id
     * column build_Id
     *
     * @MLTH_generated
     */
    private Long build_Id;

    /**
     *   品类图片
     * column imgurl
     *
     * @MLTH_generated
     */
    private String imgurl;

    /**
     *   排序号
     * column sort
     *
     * @MLTH_generated
     */
    private Long sort;

    private String appshow_imgurl;
    
    private String rgb;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_build_class
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   品类id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   品类id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   品类名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   品类名称
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *   基础属性表
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getBase_table() {
        return base_table;
    }

    /**
     *   基础属性表
     * @param base_table the value for 
     *
     * @MLTH_generated
     */
    public void setBase_table(String base_table) {
        this.base_table = base_table == null ? null : base_table.trim();
    }

    /**
     *   销售属性表
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getSales_table() {
        return sales_table;
    }

    /**
     *   销售属性表
     * @param sales_table the value for 
     *
     * @MLTH_generated
     */
    public void setSales_table(String sales_table) {
        this.sales_table = sales_table == null ? null : sales_table.trim();
    }

    /**
     *   建材id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBuild_Id() {
        return build_Id;
    }

    /**
     *   建材id
     * @param build_Id the value for 
     *
     * @MLTH_generated
     */
    public void setBuild_Id(Long build_Id) {
        this.build_Id = build_Id;
    }

    /**
     *   品类图片
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     *   品类图片
     * @param imgurl the value for 
     *
     * @MLTH_generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     *   排序号
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSort() {
        return sort;
    }

    /**
     *   排序号
     * @param sort the value for 
     *
     * @MLTH_generated
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    public String getAppshow_imgurl() {
		return appshow_imgurl;
	}

	public void setAppshow_imgurl(String appshow_imgurl) {
		this.appshow_imgurl = appshow_imgurl;
	}

	public String getRgb() {
		return rgb;
	}

	public void setRgb(String rgb) {
		this.rgb = rgb;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", base_table=").append(base_table);
        sb.append(", sales_table=").append(sales_table);
        sb.append(", build_Id=").append(build_Id);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", sort=").append(sort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}