package com.mfangsoft.zhuangjialong.integration.enterprise.model;

import java.io.Serializable;

/**
 *   品类企业
 * table t_biz_build_enterprise
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BuildEnterpriseEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   品类id
     * column class_id
     *
     * @MLTH_generated
     */
    private Long class_id;

    /**
     *   名称
     * column name
     *
     * @MLTH_generated
     */
    private String name;
    
    
    private String imgurl;

    public String getImgurl() {
		return imgurl;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_build_enterprise
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   品类id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getClass_id() {
        return class_id;
    }

    private BuildClassEntity buildClassEntity;
    
    public BuildClassEntity getBuildClassEntity() {
		return buildClassEntity;
	}

	public void setBuildClassEntity(BuildClassEntity buildClassEntity) {
		this.buildClassEntity = buildClassEntity;
	}

	/**
     *   品类id
     * @param class_id the value for 
     *
     * @MLTH_generated
     */
    public void setClass_id(Long class_id) {
        this.class_id = class_id;
    }

    /**
     *   名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   名称
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", class_id=").append(class_id);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}