package com.mfangsoft.zhuangjialong.integration.enterprise.model;

import java.io.Serializable;

/**
 *   建材表
 * table t_biz_build_materials
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BuildMaterialsEntity implements Serializable {
    /**
     *   建材id
     * column ID
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   建材名称
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_build_materials
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   建材id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   建材id
     * @param ID the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   建材名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   建材名称
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ID=").append(id);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}