package com.mfangsoft.zhuangjialong.integration.enterprise.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * table t_biz_enterprise_one
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class EnterpriseOneEntity implements Serializable {
	
	
	public final   static  Integer ENTERPRISE_CASE=2;
	
	
	public final   static  Integer ENTERPRISE_HONOR=3;
	
	
	public final   static  Integer ENTERPRISE_STYLE=4;
	
	
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   名称
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     *   2：工程案例；3：品牌荣誉；4：店面风采
     * column type
     *
     * @MLTH_generated
     */
    private Integer type;

    /**
     * column enterprise_id
     *
     * @MLTH_generated
     */
    private Long enterprise_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_enterprise_one
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   名称
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *   2：工程案例；3：品牌荣誉；4：店面风采
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getType() {
        return type;
    }

    /**
     *   2：工程案例；3：品牌荣誉；4：店面风采
     * @param type the value for 
     *
     * @MLTH_generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getEnterprise_id() {
        return enterprise_id;
    }

    /**
     * @param enterprise_id the value for 
     *
     * @MLTH_generated
     */
    public void setEnterprise_id(Long enterprise_id) {
        this.enterprise_id = enterprise_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", enterprise_id=").append(enterprise_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}