package com.mfangsoft.zhuangjialong.integration.enterprise.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.mfangsoft.zhuangjialong.integration.bank.model.BankEntity;
import com.mfangsoft.zhuangjialong.integration.commerce.model.CommerceEntity;
import com.mfangsoft.zhuangjialong.integration.user.model.UserEntity;

/**
 *   企业信息表
 * table t_biz_enterprise
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class EnterpriseEntity implements Serializable {
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   负责人
     * column principal
     *
     * @MLTH_generated
     */
    private String principal;

    /**
     *   联系方式
     * column phone_num
     *
     * @MLTH_generated
     */
    private String phone_num;

    /**
     *   品类ID
     * column class_id
     *
     * @MLTH_generated
     */
    private Long class_id;

    /**
     *   工商信息ID
     * column commerce_id
     *
     * @MLTH_generated
     */
    private Long commerce_id;

    /**
     *   图片URL
     * column imgurl
     *
     * @MLTH_generated
     */
    private String imgurl;

    /**
     *   银行账户信息ID
     * column bank_info_id
     *
     * @MLTH_generated
     */
    private Long bank_info_id;

    /**
     *   录入时间
     * column create_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date create_time;

    /**
     *   录入人
     * column creater
     *
     * @MLTH_generated
     */
    private Long creater;

    /**
     *   修改时间
     * column update_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date update_time;

    /**
     *   修改人
     * column updater
     *
     * @MLTH_generated
     */
    private Long updater;

    /**
     *   账号ID
     * column sys_user_id
     *
     * @MLTH_generated
     */
    private Long sys_user_id;

    /**
     *   企业名称
     * column enterprise_name
     *
     * @MLTH_generated
     */
    private String enterprise_name;

    /**
     *   品牌名称
     * column brand_name
     *
     * @MLTH_generated
     */
    private String brand_name;
    /**
     * 联系地址
     */
    private String addr;
    
    /**
     * 分类企业
     */
    private Long  build_enterpise;
    
    private BuildEnterpriseEntity buildEnterpriseEntity;
    
    
    
    public BuildEnterpriseEntity getBuildEnterpriseEntity() {
		return buildEnterpriseEntity;
	}

	public void setBuildEnterpriseEntity(BuildEnterpriseEntity buildEnterpriseEntity) {
		this.buildEnterpriseEntity = buildEnterpriseEntity;
	}

	private String class_name;
    
    public String getClass_name() {
		return class_name;
	}

	public void setClass_name(String class_name) {
		this.class_name = class_name;
	}

	public Long getBuild_enterpise() {
		return build_enterpise;
	}

	public void setBuild_enterpise(Long build_enterpise) {
		this.build_enterpise = build_enterpise;
	}

	private BuildClassEntity buildClassEntity;
    
    
    public BuildClassEntity getBuildClassEntity() {
		return buildClassEntity;
	}

	public void setBuildClassEntity(BuildClassEntity buildClassEntity) {
		this.buildClassEntity = buildClassEntity;
	}

	public String getAddr() {
		return addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	private BankEntity bankEntity;
    
    public BankEntity getBankEntity() {
		return bankEntity;
	}

	public void setBankEntity(BankEntity bankEntity) {
		this.bankEntity = bankEntity;
	}

	public CommerceEntity getCommerceEntity() {
		return commerceEntity;
	}

	public void setCommerceEntity(CommerceEntity commerceEntity) {
		this.commerceEntity = commerceEntity;
	}

	private CommerceEntity commerceEntity;
    
    
    private UserEntity userEntity;

    public UserEntity getUserEntity() {
		return userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_enterprise
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   负责人
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     *   负责人
     * @param principal the value for 
     *
     * @MLTH_generated
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     *   联系方式
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPhone_num() {
        return phone_num;
    }

    /**
     *   联系方式
     * @param phone_num the value for 
     *
     * @MLTH_generated
     */
    public void setPhone_num(String phone_num) {
        this.phone_num = phone_num == null ? null : phone_num.trim();
    }

    /**
     *   品类ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getClass_id() {
        return class_id;
    }

    /**
     *   品类ID
     * @param class_id the value for 
     *
     * @MLTH_generated
     */
    public void setClass_id(Long class_id) {
        this.class_id = class_id;
    }

    /**
     *   工商信息ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCommerce_id() {
        return commerce_id;
    }

    /**
     *   工商信息ID
     * @param commerce_id the value for 
     *
     * @MLTH_generated
     */
    public void setCommerce_id(Long commerce_id) {
        this.commerce_id = commerce_id;
    }

    /**
     *   图片URL
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     *   图片URL
     * @param imgurl the value for 
     *
     * @MLTH_generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     *   银行账户信息ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBank_info_id() {
        return bank_info_id;
    }

    /**
     *   银行账户信息ID
     * @param bank_info_id the value for 
     *
     * @MLTH_generated
     */
    public void setBank_info_id(Long bank_info_id) {
        this.bank_info_id = bank_info_id;
    }

    /**
     *   录入时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   录入时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   录入人
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public Long getCreater() {
        return creater;
    }

    /**
     *   录入人
     * @param creater the value for 
     *
     * @MLTH_generated
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     *   修改时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     *   修改时间
     * @param update_time the value for 
     *
     * @MLTH_generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     *   修改人
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     *   修改人
     * @param updater the value for 
     *
     * @MLTH_generated
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     *   账号ID
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSys_user_id() {
        return sys_user_id;
    }

    /**
     *   账号ID
     * @param sys_user_id the value for 
     *
     * @MLTH_generated
     */
    public void setSys_user_id(Long sys_user_id) {
        this.sys_user_id = sys_user_id;
    }

    /**
     *   企业名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getEnterprise_name() {
        return enterprise_name;
    }

    /**
     *   企业名称
     * @param enterprise_name the value for 
     *
     * @MLTH_generated
     */
    public void setEnterprise_name(String enterprise_name) {
        this.enterprise_name = enterprise_name == null ? null : enterprise_name.trim();
    }

    /**
     *   品牌名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getBrand_name() {
        return brand_name;
    }

    /**
     *   品牌名称
     * @param brand_name the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_name(String brand_name) {
        this.brand_name = brand_name == null ? null : brand_name.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", principal=").append(principal);
        sb.append(", phone_num=").append(phone_num);
        sb.append(", class_id=").append(class_id);
        sb.append(", commerce_id=").append(commerce_id);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", bank_info_id=").append(bank_info_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", creater=").append(creater);
        sb.append(", update_time=").append(update_time);
        sb.append(", updater=").append(updater);
        sb.append(", sys_user_id=").append(sys_user_id);
        sb.append(", enterprise_name=").append(enterprise_name);
        sb.append(", brand_name=").append(brand_name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}