package com.mfangsoft.zhuangjialong.integration.enterprise.model;

import java.io.Serializable;

/**
 *   企业信息介绍
 * table t_biz_enterprise_info
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class EnterpriseInfoEntity implements Serializable {
	
	
	public final static Integer  ENTERPRISE_PROFILES=0;
	
	public final static Integer  ENTERPRISE_DEVELOPMENT=1;
	
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   0：公司简介；1：发展历程；2：工程案例；3：品牌荣誉；4：店面风采
     * column type
     *
     * @MLTH_generated
     */
    private Integer type;

    /**
     *   企业id
     * column enterprise_id
     *
     * @MLTH_generated
     */
    private Long enterprise_id;

    /**
     *   html5图文
     * column enterprise_html
     *
     * @MLTH_generated
     */
    private String enterprise_html;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_enterprise_info
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   0：公司简介；1：发展历程；2：工程案例；3：品牌荣誉；4：店面风采
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getType() {
        return type;
    }

    /**
     *   0：公司简介；1：发展历程；2：工程案例；3：品牌荣誉；4：店面风采
     * @param type the value for 
     *
     * @MLTH_generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     *   企业id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getEnterprise_id() {
        return enterprise_id;
    }

    /**
     *   企业id
     * @param enterprise_id the value for 
     *
     * @MLTH_generated
     */
    public void setEnterprise_id(Long enterprise_id) {
        this.enterprise_id = enterprise_id;
    }

    /**
     *   html5图文
     * @return the value of LONGVARCHAR
     *
     * @MLTH_generated
     */
    public String getEnterprise_html() {
        return enterprise_html;
    }

    /**
     *   html5图文
     * @param enterprise_html the value for 
     *
     * @MLTH_generated
     */
    public void setEnterprise_html(String enterprise_html) {
        this.enterprise_html = enterprise_html == null ? null : enterprise_html.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", enterprise_id=").append(enterprise_id);
        sb.append(", enterprise_html=").append(enterprise_html);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}