package com.mfangsoft.zhuangjialong.integration.department.model;

import java.io.Serializable;

/**
 *   组织架构表
 * table t_sys_department
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class DepartmentEntity implements Serializable {
	
	 
	
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   组织名称
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     *   组织父节点
     * column parent_id
     *
     * @MLTH_generated
     */
    private Long parent_id;

    /**
     *   是否是岗位
     * column is_position
     *
     * @MLTH_generated
     */
    private Integer is_position;
    
    
    private Long role_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_department
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    public Long getRole_id() {
		return role_id;
	}

	public void setRole_id(Long role_id) {
		this.role_id = role_id;
	}

	/**
     *   主键
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   组织名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   组织名称
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *   组织父节点
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getParent_id() {
        return parent_id;
    }

    /**
     *   组织父节点
     * @param parent_id the value for 
     *
     * @MLTH_generated
     */
    public void setParent_id(Long parent_id) {
        this.parent_id = parent_id;
    }

    /**
     *   是否是岗位
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getIs_position() {
        return is_position;
    }

    /**
     *   是否是岗位
     * @param is_position the value for 
     *
     * @MLTH_generated
     */
    public void setIs_position(Integer is_position) {
        this.is_position = is_position;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", parent_id=").append(parent_id);
        sb.append(", is_position=").append(is_position);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}