package com.mfangsoft.zhuangjialong.app.mapservice.model;

import java.io.Serializable;
import java.util.Date;

/**
 *   消费者求助表
 * table t_biz_askhelp
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseAskhelpEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   用户类型(1:买家端2：卖家端)
     * column user_type
     *
     * @MLTH_generated
     */
    private Integer user_type;

    /**
     *   消费者id
     * column user_id
     *
     * @MLTH_generated
     */
    private Long user_id;

    /**
     *   求助问题
     * column title
     *
     * @MLTH_generated
     */
    private String title;

    /**
     *   求助详情(最多200字)
     * column content
     *
     * @MLTH_generated
     */
    private String content;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    private Date create_time;

    /**
     *   区域编码
     * column region_code
     *
     * @MLTH_generated
     */
    private String region_code;

    /**
     *   位置
     * column lbs
     *
     * @MLTH_generated
     */
    private String lbs;

    /**
     *   修改时间
     * column update_time
     *
     * @MLTH_generated
     */
    private Date update_time;

    /**
     *   状态(1:有效2:无效)
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_askhelp
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   用户类型(1:买家端2：卖家端)
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getUser_type() {
        return user_type;
    }

    /**
     *   用户类型(1:买家端2：卖家端)
     * @param user_type the value for 
     *
     * @MLTH_generated
     */
    public void setUser_type(Integer user_type) {
        this.user_type = user_type;
    }

    /**
     *   消费者id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     *   消费者id
     * @param user_id the value for 
     *
     * @MLTH_generated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     *   求助问题
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getTitle() {
        return title;
    }

    /**
     *   求助问题
     * @param title the value for 
     *
     * @MLTH_generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     *   求助详情(最多200字)
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getContent() {
        return content;
    }

    /**
     *   求助详情(最多200字)
     * @param content the value for 
     *
     * @MLTH_generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   区域编码
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getRegion_code() {
        return region_code;
    }

    /**
     *   区域编码
     * @param region_code the value for 
     *
     * @MLTH_generated
     */
    public void setRegion_code(String region_code) {
        this.region_code = region_code == null ? null : region_code.trim();
    }

    /**
     *   位置
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getLbs() {
        return lbs;
    }

    /**
     *   位置
     * @param lbs the value for 
     *
     * @MLTH_generated
     */
    public void setLbs(String lbs) {
        this.lbs = lbs == null ? null : lbs.trim();
    }

    /**
     *   修改时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     *   修改时间
     * @param update_time the value for 
     *
     * @MLTH_generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     *   状态(1:有效2:无效)
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   状态(1:有效2:无效)
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", user_type=").append(user_type);
        sb.append(", user_id=").append(user_id);
        sb.append(", title=").append(title);
        sb.append(", content=").append(content);
        sb.append(", create_time=").append(create_time);
        sb.append(", region_code=").append(region_code);
        sb.append(", lbs=").append(lbs);
        sb.append(", update_time=").append(update_time);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}