package com.mfangsoft.zhuangjialong.integration.question.model;

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   问题类型表
 * table t_biz_question_type
 *
 * @MLTH_generated do_not_delete_during_merge
 */

@JsonInclude(value=Include.NON_NULL)
public class QuestionTypeEntity implements Serializable {
    /**
     *   主键id
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   问题类型
     * column question_type
     *
     * @MLTH_generated
     */
    private String question_type;

    /**
     *   问题链接
     * column url
     *
     * @MLTH_generated
     */
    private String url;
    
    private Integer type;
    
    public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	private List<QuestionEntity> questions;
    

    /**
	 * @return the questions
	 */
	public List<QuestionEntity> getQuestions() {
		return questions;
	}

	/**
	 * @param questions the questions to set
	 */
	public void setQuestions(List<QuestionEntity> questions) {
		this.questions = questions;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_question_type
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键id
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     *   主键id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   问题类型
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getQuestion_type() {
        return question_type;
    }

    /**
     *   问题类型
     * @param question_type the value for 
     *
     * @MLTH_generated
     */
    public void setQuestion_type(String question_type) {
        this.question_type = question_type == null ? null : question_type.trim();
    }

    /**
     *   问题链接
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getUrl() {
        return url;
    }

    /**
     *   问题链接
     * @param url the value for 
     *
     * @MLTH_generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", question_type=").append(question_type);
        sb.append(", url=").append(url);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}