package com.mfangsoft.zhuangjialong.app.article.model;

import java.io.Serializable;
import java.util.Date;

/**
 *   文章点赞表
 * table t_biz_article_likes
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseArticleLikesEntity implements Serializable {
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   文章id
     * column article_id
     *
     * @MLTH_generated
     */
    private Long article_id;

    /**
     *   消费者id
     * column customer_id
     *
     * @MLTH_generated
     */
    private Long customer_id;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    private Date create_time;

    /**
     *   专辑id
     * column album_id
     *
     * @MLTH_generated
     */
    private Long album_id;

    /**
     *   状态(0:踩1:点赞)
     * column state
     *
     * @MLTH_generated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_article_likes
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   文章id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getArticle_id() {
        return article_id;
    }

    /**
     *   文章id
     * @param article_id the value for 
     *
     * @MLTH_generated
     */
    public void setArticle_id(Long article_id) {
        this.article_id = article_id;
    }

    /**
     *   消费者id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCustomer_id() {
        return customer_id;
    }

    /**
     *   消费者id
     * @param customer_id the value for 
     *
     * @MLTH_generated
     */
    public void setCustomer_id(Long customer_id) {
        this.customer_id = customer_id;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   专辑id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getAlbum_id() {
        return album_id;
    }

    /**
     *   专辑id
     * @param album_id the value for 
     *
     * @MLTH_generated
     */
    public void setAlbum_id(Long album_id) {
        this.album_id = album_id;
    }

    /**
     *   状态(0:踩1:点赞)
     * @return the value of TINYINT
     *
     * @MLTH_generated
     */
    public Byte getState() {
        return state;
    }

    /**
     *   状态(0:踩1:点赞)
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", article_id=").append(article_id);
        sb.append(", customer_id=").append(customer_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", album_id=").append(album_id);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}