package com.mfangsoft.zhuangjialong.app.article.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   首页文章栏目表
 * table t_biz_main_article_column
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class BaseMainArticleColumnEntity implements Serializable {
    /**
     *   主键id
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   图片url
     * column img_url
     *
     * @MLTH_generated
     */
    private String img_url;

    /**
     *   跳转类型
     * column link_type
     *
     * @MLTH_generated
     */
    private Integer link_type;

    /**
     *   参数
     * column data_param
     *
     * @MLTH_generated
     */
    private Long data_param;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date create_time;

    /**
     *   排序
     * column sort
     *
     * @MLTH_generated
     */
    private Integer sort;

    /**
     *   状态
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_main_article_column
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键id
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     *   主键id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   图片url
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImg_url() {
        return img_url;
    }

    /**
     *   图片url
     * @param img_url the value for 
     *
     * @MLTH_generated
     */
    public void setImg_url(String img_url) {
        this.img_url = img_url == null ? null : img_url.trim();
    }

    /**
     *   跳转类型
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getLink_type() {
        return link_type;
    }

    /**
     *   跳转类型
     * @param link_type the value for 
     *
     * @MLTH_generated
     */
    public void setLink_type(Integer link_type) {
        this.link_type = link_type;
    }

    /**
     *   参数
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getData_param() {
        return data_param;
    }

    /**
     *   参数
     * @param data_param the value for 
     *
     * @MLTH_generated
     */
    public void setData_param(Long data_param) {
        this.data_param = data_param;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   排序
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     *   排序
     * @param sort the value for 
     *
     * @MLTH_generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     *   状态
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   状态
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", img_url=").append(img_url);
        sb.append(", link_type=").append(link_type);
        sb.append(", data_param=").append(data_param);
        sb.append(", create_time=").append(create_time);
        sb.append(", sort=").append(sort);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
    
    private Long album_id;//专辑id

	/**
	 * @return the album_id
	 */
	public Long getAlbum_id() {
		return album_id;
	}

	/**
	 * @param album_id the album_id to set
	 */
	public void setAlbum_id(Long album_id) {
		this.album_id = album_id;
	}
    
    
    
}