package com.mfangsoft.zhuangjialong.app.article.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   文章评论表
 * table t_biz_article_evaluation
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class BaseArticleEvaluationEntity implements Serializable {
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   消费者id
     * column customer_id
     *
     * @MLTH_generated
     */
    private Long customer_id;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date create_time;

    /**
     *   评价内容(最多140)
     * column content
     *
     * @MLTH_generated
     */
    private String content;

    /**
     *   文章id
     * column article_id
     *
     * @MLTH_generated
     */
    private Integer article_id;

    /**
     *   专辑id
     * column album_id
     *
     * @MLTH_generated
     */
    private Long album_id;

    /**
     *   状态（true:正常显示false:违规屏蔽）
     * column state
     *
     * @MLTH_generated
     */
    private Byte state;

    /**
     *   被赞次数
     * column like_num
     *
     * @MLTH_generated
     */
    private Integer like_num;

    /**
     *   父消费者id
     * column parent_cus_id
     *
     * @MLTH_generated
     */
    private Long parent_cus_id;

    /**
     *   父id
     * column parent_id
     *
     * @MLTH_generated
     */
    private Integer parent_id;

    /**
     *   楼主评论id(楼主为0)
     * column main_id
     *
     * @MLTH_generated
     */
    private Integer main_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_article_evaluation
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   消费者id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCustomer_id() {
        return customer_id;
    }

    /**
     *   消费者id
     * @param customer_id the value for 
     *
     * @MLTH_generated
     */
    public void setCustomer_id(Long customer_id) {
        this.customer_id = customer_id;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   评价内容(最多140)
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getContent() {
        return content;
    }

    /**
     *   评价内容(最多140)
     * @param content the value for 
     *
     * @MLTH_generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     *   文章id
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getArticle_id() {
        return article_id;
    }

    /**
     *   文章id
     * @param article_id the value for 
     *
     * @MLTH_generated
     */
    public void setArticle_id(Integer article_id) {
        this.article_id = article_id;
    }

    /**
     *   专辑id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getAlbum_id() {
        return album_id;
    }

    /**
     *   专辑id
     * @param album_id the value for 
     *
     * @MLTH_generated
     */
    public void setAlbum_id(Long album_id) {
        this.album_id = album_id;
    }

    /**
     *   状态（true:正常显示false:违规屏蔽）
     * @return the value of TINYINT
     *
     * @MLTH_generated
     */
    public Byte getState() {
        return state;
    }

    /**
     *   状态（true:正常显示false:违规屏蔽）
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     *   被赞次数
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getLike_num() {
        return like_num;
    }

    /**
     *   被赞次数
     * @param like_num the value for 
     *
     * @MLTH_generated
     */
    public void setLike_num(Integer like_num) {
        this.like_num = like_num;
    }

    /**
     *   父消费者id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getParent_cus_id() {
        return parent_cus_id;
    }

    /**
     *   父消费者id
     * @param parent_cus_id the value for 
     *
     * @MLTH_generated
     */
    public void setParent_cus_id(Long parent_cus_id) {
        this.parent_cus_id = parent_cus_id;
    }

    /**
     *   父id
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getParent_id() {
        return parent_id;
    }

    /**
     *   父id
     * @param parent_id the value for 
     *
     * @MLTH_generated
     */
    public void setParent_id(Integer parent_id) {
        this.parent_id = parent_id;
    }

    /**
     *   楼主评论id(楼主为0)
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getMain_id() {
        return main_id;
    }

    /**
     *   楼主评论id(楼主为0)
     * @param main_id the value for 
     *
     * @MLTH_generated
     */
    public void setMain_id(Integer main_id) {
        this.main_id = main_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", customer_id=").append(customer_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", content=").append(content);
        sb.append(", article_id=").append(article_id);
        sb.append(", album_id=").append(album_id);
        sb.append(", state=").append(state);
        sb.append(", like_num=").append(like_num);
        sb.append(", parent_cus_id=").append(parent_cus_id);
        sb.append(", parent_id=").append(parent_id);
        sb.append(", main_id=").append(main_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}