package com.mfangsoft.zhuangjialong.app.main.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   全景案例表
 * table t_biz_case
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class CaseEntity implements Serializable {
    /**
     *   案例id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   案例url
     * column link_url
     *
     * @MLTH_generated
     */
    private String link_url;

    /**
     *   案例类型（1：案例，2案例资源）
     * column type
     *
     * @MLTH_generated
     */
    private Integer type;

    /**
     *   案例资源url
     * column case_resource_url
     *
     * @MLTH_generated
     */
    private String case_resource_url;

    /**
     *   案例名称
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     *   案例标题
     * column title
     *
     * @MLTH_generated
     */
    private String title;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date create_time;

    /**
     *   列表图片
     * column list_img
     *
     * @MLTH_generated
     */
    private String list_img;

    /**
     *   全景图片
     * column panoramic_img
     *
     * @MLTH_generated
     */
    private String panoramic_img;

    /**
     *   1:开启,2:关闭
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     *   合伙人
     * column partner_ids
     *
     * @MLTH_generated
     */
    private String partner_ids;
    
    /**
     *   合伙人
     * column partner_ids
     *
     * @MLTH_generated
     */
    private String partner_names;

    public String getPartner_names() {
		return partner_names;
	}

	public void setPartner_names(String partner_names) {
		this.partner_names = partner_names;
	}

	/**
     *   案例描述
     * column description
     *
     * @MLTH_generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_case
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   案例id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   案例id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   案例url
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getLink_url() {
        return link_url;
    }

    /**
     *   案例url
     * @param link_url the value for 
     *
     * @MLTH_generated
     */
    public void setLink_url(String link_url) {
        this.link_url = link_url == null ? null : link_url.trim();
    }

    /**
     *   案例类型（1：案例，2案例资源）
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getType() {
        return type;
    }

    /**
     *   案例类型（1：案例，2案例资源）
     * @param type the value for 
     *
     * @MLTH_generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     *   案例资源url
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getCase_resource_url() {
        return case_resource_url;
    }

    /**
     *   案例资源url
     * @param case_resource_url the value for 
     *
     * @MLTH_generated
     */
    public void setCase_resource_url(String case_resource_url) {
        this.case_resource_url = case_resource_url == null ? null : case_resource_url.trim();
    }

    /**
     *   案例名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   案例名称
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *   案例标题
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getTitle() {
        return title;
    }

    /**
     *   案例标题
     * @param title the value for 
     *
     * @MLTH_generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   列表图片
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getList_img() {
        return list_img;
    }

    /**
     *   列表图片
     * @param list_img the value for 
     *
     * @MLTH_generated
     */
    public void setList_img(String list_img) {
        this.list_img = list_img == null ? null : list_img.trim();
    }

    /**
     *   全景图片
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPanoramic_img() {
        return panoramic_img;
    }

    /**
     *   全景图片
     * @param panoramic_img the value for 
     *
     * @MLTH_generated
     */
    public void setPanoramic_img(String panoramic_img) {
        this.panoramic_img = panoramic_img == null ? null : panoramic_img.trim();
    }

    /**
     *   1:开启,2:关闭
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   1:开启,2:关闭
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *   合伙人
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPartner_ids() {
        return partner_ids;
    }

    /**
     *   合伙人
     * @param partner_ids the value for 
     *
     * @MLTH_generated
     */
    public void setPartner_ids(String partner_ids) {
        this.partner_ids = partner_ids == null ? null : partner_ids.trim();
    }

    /**
     *   案例描述
     * @return the value of LONGVARCHAR
     *
     * @MLTH_generated
     */
    public String getDescription() {
        return description;
    }

    /**
     *   案例描述
     * @param description the value for 
     *
     * @MLTH_generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", link_url=").append(link_url);
        sb.append(", type=").append(type);
        sb.append(", case_resource_url=").append(case_resource_url);
        sb.append(", name=").append(name);
        sb.append(", title=").append(title);
        sb.append(", create_time=").append(create_time);
        sb.append(", list_img=").append(list_img);
        sb.append(", panoramic_img=").append(panoramic_img);
        sb.append(", state=").append(state);
        sb.append(", partner_ids=").append(partner_ids);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}