package com.mfangsoft.zhuangjialong.app.main.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   首页栏目图、头条图、案例首页图
 * table t_biz_column_img
 *
 * @MLTH_generated do_not_delete_during_merge
 */

@JsonInclude(value=Include.NON_NULL)
public class ColumnImg implements Serializable {
	
	public final static Integer  COLUMN_IMG_TYPE=1;
	
	
	public final static Integer  TAG_IMG_TYPE=2;
	
	public final static Integer  TOP_IMG_TYPE=3;
	
	
	public final static Integer  CASE_IMG_TYPE=4;
	 
	
	
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   图片url
     * column imgurl
     *
     * @MLTH_generated
     */
    private String imgurl;

    /**
     *   1:栏目，2：标签，3：龙头条，4：案例图
     * column img_type
     *
     * @MLTH_generated
     */
    private Integer img_type;

    /**
     *   栏目/标签名称
     * column column_name
     *
     * @MLTH_generated
     */
    private String column_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_column_img
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   图片url
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     *   图片url
     * @param imgurl the value for 
     *
     * @MLTH_generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     *   1:栏目，2：标签，3：龙头条，4：案例图
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getImg_type() {
        return img_type;
    }

    /**
     *   1:栏目，2：标签，3：龙头条，4：案例图
     * @param img_type the value for 
     *
     * @MLTH_generated
     */
    public void setImg_type(Integer img_type) {
        this.img_type = img_type;
    }

    /**
     *   栏目/标签名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getColumn_name() {
        return column_name;
    }

    /**
     *   栏目/标签名称
     * @param column_name the value for 
     *
     * @MLTH_generated
     */
    public void setColumn_name(String column_name) {
        this.column_name = column_name == null ? null : column_name.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", img_type=").append(img_type);
        sb.append(", column_name=").append(column_name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
    
    private String select_url;
    private String selected_url;

	/**
	 * @return the select_url
	 */
	public String getSelect_url() {
		return select_url;
	}

	/**
	 * @param select_url the select_url to set
	 */
	public void setSelect_url(String select_url) {
		this.select_url = select_url;
	}

	/**
	 * @return the selected_url
	 */
	public String getSelected_url() {
		return selected_url;
	}

	/**
	 * @param selected_url the selected_url to set
	 */
	public void setSelected_url(String selected_url) {
		this.selected_url = selected_url;
	}
    
    private Integer link_type;//跳转类型

	/**
	 * @return the link_type
	 */
	public Integer getLink_type() {
		return link_type;
	}

	/**
	 * @param link_type the link_type to set
	 */
	public void setLink_type(Integer link_type) {
		this.link_type = link_type;
	}
    
    
    
}