package com.mfangsoft.zhuangjialong.app.main.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   主页轮播图表
 * table t_biz_mainbanner
 *
 * @MLTH_generated do_not_delete_during_merge
 */

@JsonInclude(value=Include.NON_NULL)
public class MainBannerEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   图片URL
     * column image_url
     *
     * @MLTH_generated
     */
    private String image_url;

    /**
     *   参数
     * column data_param
     *
     * @MLTH_generated
     */
    private String data_param;

    /**
     *   链接地址
     * column image_link
     *
     * @MLTH_generated
     */
    private String image_link;

    /**
     *   链接类型
     * column link_type
     *
     * @MLTH_generated
     */
    private Integer link_type;

    /**
     *   排序号
     * column sort
     *
     * @MLTH_generated
     */
    private Long sort;
    /**
     * 后台账号id
     * column  user_id
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_mainbanner
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   图片URL
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImage_url() {
        return image_url;
    }

    /**
     *   图片URL
     * @param image_url the value for 
     *
     * @MLTH_generated
     */
    public void setImage_url(String image_url) {
        this.image_url = image_url == null ? null : image_url.trim();
    }

    /**
     *   参数
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getData_param() {
        return data_param;
    }

    /**
     *   参数
     * @param data_param the value for 
     *
     * @MLTH_generated
     */
    public void setData_param(String data_param) {
        this.data_param = data_param == null ? null : data_param.trim();
    }

    /**
     *   链接地址
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImage_link() {
        return image_link;
    }

    /**
     *   链接地址
     * @param image_link the value for 
     *
     * @MLTH_generated
     */
    public void setImage_link(String image_link) {
        this.image_link = image_link == null ? null : image_link.trim();
    }

    /**
     *   链接类型
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getLink_type() {
        return link_type;
    }

    /**
     *   链接类型
     * @param link_type the value for 
     *
     * @MLTH_generated
     */
    public void setLink_type(Integer link_type) {
        this.link_type = link_type;
    }

    /**
     *   排序号
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSort() {
        return sort;
    }

    /**
     *   排序号
     * @param sort the value for 
     *
     * @MLTH_generated
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", image_url=").append(image_url);
        sb.append(", data_param=").append(data_param);
        sb.append(", image_link=").append(image_link);
        sb.append(", link_type=").append(link_type);
        sb.append(", sort=").append(sort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

	public Long getUser_id() {
		return user_id;
	}

	public void setUser_id(Long user_id) {
		this.user_id = user_id;
	}
}