package com.mfangsoft.zhuangjialong.integration.brand.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   品牌下架申请表
 * table t_biz_brand_state_apply
 *
 * @MLTH_generated do_not_delete_during_merge
 */
@JsonInclude(value=Include.NON_NULL)
public class BaseBrandStateApplyEntity implements Serializable {
    /**
     *   逐渐
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   品牌id
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    private Date create_time;

    /**
     *   处理时间
     * column deal_time
     *
     * @MLTH_generated
     */
    private Date deal_time;

    /**
     *   申请用户
     * column user_id
     *
     * @MLTH_generated
     */
    private Long user_id;

    /**
     *   下架理由
     * column reason
     *
     * @MLTH_generated
     */
    private String reason;

    /**
     *   状态（0：已处理1：未处理）
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_brand_state_apply
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   逐渐
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     *   逐渐
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   品牌id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌id
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   处理时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getDeal_time() {
        return deal_time;
    }

    /**
     *   处理时间
     * @param deal_time the value for 
     *
     * @MLTH_generated
     */
    public void setDeal_time(Date deal_time) {
        this.deal_time = deal_time;
    }

    /**
     *   申请用户
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     *   申请用户
     * @param user_id the value for 
     *
     * @MLTH_generated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     *   下架理由
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getReason() {
        return reason;
    }

    /**
     *   下架理由
     * @param reason the value for 
     *
     * @MLTH_generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     *   状态（0：已处理1：未处理）
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   状态（0：已处理1：未处理）
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", deal_time=").append(deal_time);
        sb.append(", user_id=").append(user_id);
        sb.append(", reason=").append(reason);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}