package com.mfangsoft.zhuangjialong.integration.brand.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 *   品牌banner表
 * table t_biz_brand_banner
 *
 * @MLTH_generated do_not_delete_during_merge
 */

@JsonInclude(value=Include.NON_NULL)
public class BrandBannerEntity implements Serializable {
    /**
     *   主键id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   链接类型
     * column link_type
     *
     * @MLTH_generated
     */
    private Integer link_type;

    /**
     *   图片URL
     * column imgurl
     *
     * @MLTH_generated
     */
    private String imgurl;

    /**
     *   链接
     * column link
     *
     * @MLTH_generated
     */
    private String link;

    /**
     *   品牌id
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     *   参数
     * column data_param
     *
     * @MLTH_generated
     */
    private String data_param;

    /**
     *   排序号
     * column sort
     *
     * @MLTH_generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_brand_banner
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   链接类型
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getLink_type() {
        return link_type;
    }

    /**
     *   链接类型
     * @param link_type the value for 
     *
     * @MLTH_generated
     */
    public void setLink_type(Integer link_type) {
        this.link_type = link_type;
    }

    /**
     *   图片URL
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     *   图片URL
     * @param imgurl the value for 
     *
     * @MLTH_generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     *   链接
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getLink() {
        return link;
    }

    /**
     *   链接
     * @param link the value for 
     *
     * @MLTH_generated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     *   品牌id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌id
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     *   参数
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getData_param() {
        return data_param;
    }

    /**
     *   参数
     * @param data_param the value for 
     *
     * @MLTH_generated
     */
    public void setData_param(String data_param) {
        this.data_param = data_param == null ? null : data_param.trim();
    }

    /**
     *   排序号
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     *   排序号
     * @param sort the value for 
     *
     * @MLTH_generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", link_type=").append(link_type);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", link=").append(link);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", data_param=").append(data_param);
        sb.append(", sort=").append(sort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}