package com.mfangsoft.zhuangjialong.integration.brand.model;

import java.io.Serializable;

/**
 *   热门分类
 * table t_biz_hot_classify
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class HotClassifyEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     * column classify_name
     *
     * @MLTH_generated
     */
    private String classify_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_hot_classify
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    /**
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getClassify_name() {
        return classify_name;
    }

    /**
     * @param classify_name the value for 
     *
     * @MLTH_generated
     */
    public void setClassify_name(String classify_name) {
        this.classify_name = classify_name == null ? null : classify_name.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", classify_name=").append(classify_name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}