package com.mfangsoft.zhuangjialong.integration.brand.model;

import java.io.Serializable;

/**
 * table t_biz_hot_classify_product
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class HotClassifyProductEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     * column product_id
     *
     * @MLTH_generated
     */
    private Long product_id;

    /**
     * column hot_classify_id
     *
     * @MLTH_generated
     */
    private Long hot_classify_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_hot_classify_product
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getProduct_id() {
        return product_id;
    }

    /**
     * @param product_id the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getHot_classify_id() {
        return hot_classify_id;
    }

    /**
     * @param hot_classify_id the value for 
     *
     * @MLTH_generated
     */
    public void setHot_classify_id(Long hot_classify_id) {
        this.hot_classify_id = hot_classify_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", product_id=").append(product_id);
        sb.append(", hot_classify_id=").append(hot_classify_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}