package com.mfangsoft.zhuangjialong.integration.newcoupons.model;

import java.io.Serializable;

/**
 * table t_biz_scope_coupons
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseScopeCouponsEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   卷id
     * column coupons_id
     *
     * @MLTH_generated
     */
    private Long coupons_id;

    /**
     *   合伙人id
     * column partner_id
     *
     * @MLTH_generated
     */
    private Long partner_id;

    /**
     *   品牌id
     * column brand_id
     *
     * @MLTH_generated
     */
    private Long brand_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_scope_coupons
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   卷id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCoupons_id() {
        return coupons_id;
    }

    /**
     *   卷id
     * @param coupons_id the value for 
     *
     * @MLTH_generated
     */
    public void setCoupons_id(Long coupons_id) {
        this.coupons_id = coupons_id;
    }

    /**
     *   合伙人id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getPartner_id() {
        return partner_id;
    }

    /**
     *   合伙人id
     * @param partner_id the value for 
     *
     * @MLTH_generated
     */
    public void setPartner_id(Long partner_id) {
        this.partner_id = partner_id;
    }

    /**
     *   品牌id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getBrand_id() {
        return brand_id;
    }

    /**
     *   品牌id
     * @param brand_id the value for 
     *
     * @MLTH_generated
     */
    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", coupons_id=").append(coupons_id);
        sb.append(", partner_id=").append(partner_id);
        sb.append(", brand_id=").append(brand_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}