package com.mfangsoft.zhuangjialong.integration.newcoupons.model;

import java.io.Serializable;
import java.util.Date;

/**
 *   消费者劵表
 * table t_biz_customer_coupons
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseCustomerCouponsEntity implements Serializable {
    /**
     *   主键
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   店铺Id
     * column shop_id
     *
     * @MLTH_generated
     */
    private Long shop_id;

    /**
     *   兑换码
     * column convert_code
     *
     * @MLTH_generated
     */
    private String convert_code;

    /**
     *   是否线上
     * column isline
     *
     * @MLTH_generated
     */
    private Boolean isline;

    /**
     *   劵id
     * column coupons_id
     *
     * @MLTH_generated
     */
    private Long coupons_id;

    /**
     *   消费者id
     * column customer_id
     *
     * @MLTH_generated
     */
    private Long customer_id;

    /**
     *   是否使用 0：未使用，1：使用
     * column isused
     *
     * @MLTH_generated
     */
    private Boolean isused;

    /**
     *   领取时间
     * column create_time
     *
     * @MLTH_generated
     */
    private Date create_time;

    /**
     *   使用时间
     * column use_time
     *
     * @MLTH_generated
     */
    private Date use_time;
    
    private String order_code;

    private String   product_order_code;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_customer_coupons
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   店铺Id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getShop_id() {
        return shop_id;
    }

    /**
     *   店铺Id
     * @param shop_id the value for 
     *
     * @MLTH_generated
     */
    public void setShop_id(Long shop_id) {
        this.shop_id = shop_id;
    }

    /**
     *   兑换码
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getConvert_code() {
        return convert_code;
    }

    /**
     *   兑换码
     * @param convert_code the value for 
     *
     * @MLTH_generated
     */
    public void setConvert_code(String convert_code) {
        this.convert_code = convert_code == null ? null : convert_code.trim();
    }

    /**
     *   是否线上
     * @return the value of BIT
     *
     * @MLTH_generated
     */
    public Boolean getIsline() {
        return isline;
    }

    /**
     *   是否线上
     * @param isline the value for 
     *
     * @MLTH_generated
     */
    public void setIsline(Boolean isline) {
        this.isline = isline;
    }

    /**
     *   劵id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCoupons_id() {
        return coupons_id;
    }

    /**
     *   劵id
     * @param coupons_id the value for 
     *
     * @MLTH_generated
     */
    public void setCoupons_id(Long coupons_id) {
        this.coupons_id = coupons_id;
    }

    /**
     *   消费者id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getCustomer_id() {
        return customer_id;
    }

    /**
     *   消费者id
     * @param customer_id the value for 
     *
     * @MLTH_generated
     */
    public void setCustomer_id(Long customer_id) {
        this.customer_id = customer_id;
    }

    /**
     *   是否使用 0：未使用，1：使用
     * @return the value of BIT
     *
     * @MLTH_generated
     */
    public Boolean getIsused() {
        return isused;
    }

    /**
     *   是否使用 0：未使用，1：使用
     * @param isused the value for 
     *
     * @MLTH_generated
     */
    public void setIsused(Boolean isused) {
        this.isused = isused;
    }

    /**
     *   领取时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   领取时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   使用时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getUse_time() {
        return use_time;
    }

    /**
     *   使用时间
     * @param use_time the value for 
     *
     * @MLTH_generated
     */
    public void setUse_time(Date use_time) {
        this.use_time = use_time;
    }

    public String getOrder_code() {
		return order_code;
	}

	public void setOrder_code(String order_code) {
		this.order_code = order_code;
	}

	public String getProduct_order_code() {
		return product_order_code;
	}

	public void setProduct_order_code(String product_order_code) {
		this.product_order_code = product_order_code;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", shop_id=").append(shop_id);
        sb.append(", convert_code=").append(convert_code);
        sb.append(", isline=").append(isline);
        sb.append(", coupons_id=").append(coupons_id);
        sb.append(", customer_id=").append(customer_id);
        sb.append(", isused=").append(isused);
        sb.append(", create_time=").append(create_time);
        sb.append(", use_time=").append(use_time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}