package com.mfangsoft.zhuangjialong.integration.newcoupons.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 *   优惠券红包表
 * table t_biz_brand_coupons
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class BaseBrandCouponsEntity implements Serializable {
    /**
     *   红包优惠券id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   名称
     * column name
     *
     * @MLTH_generated
     */
    private String name;

    /**
     *   1：平台，2：品牌
     * column scope_type
     *
     * @MLTH_generated
     */
    private Integer scope_type;

    /**
     *   图片url
     * column imgurl
     *
     * @MLTH_generated
     */
    private String imgurl;

    /**
     *   优惠卷/红包价格
     * column coupons_price
     *
     * @MLTH_generated
     */
    private Double coupons_price;

    /**
     *   剩余个数
     * column surplus_count
     *
     * @MLTH_generated
     */
    private Integer surplus_count;

    /**
     *   总个数
     * column total_count
     *
     * @MLTH_generated
     */
    private Integer total_count;

    /**
     *   门槛
     * column step_value
     *
     * @MLTH_generated
     */
    private Double step_value;

    /**
     *   卷类型1：红包 2：优惠卷
     * column type
     *
     * @MLTH_generated
     */
    private Integer type;

    /**
     *   开始时间
     * column start_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date start_time;

    /**
     *   结束时间
     * column end_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date end_time;

    /**
     *   1:启用，2停用
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     *   面额
     * column value
     *
     * @MLTH_generated
     */
    private Double value;

    /**
     *   创建人id
     * column user_id
     *
     * @MLTH_generated
     */
    private Long user_id;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    private Date create_time;

    /**
     *   每人限领
     * column limit_count
     *
     * @MLTH_generated
     */
    private Integer limit_count;

    private Integer random_count;
    
    private String details;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_brand_coupons
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   红包优惠券id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   红包优惠券id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   名称
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getName() {
        return name;
    }

    /**
     *   名称
     * @param name the value for 
     *
     * @MLTH_generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *   1：平台，2：品牌
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getScope_type() {
        return scope_type;
    }

    /**
     *   1：平台，2：品牌
     * @param scope_type the value for 
     *
     * @MLTH_generated
     */
    public void setScope_type(Integer scope_type) {
        this.scope_type = scope_type;
    }

    /**
     *   图片url
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     *   图片url
     * @param imgurl the value for 
     *
     * @MLTH_generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     *   优惠卷/红包价格
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getCoupons_price() {
        return coupons_price;
    }

    /**
     *   优惠卷/红包价格
     * @param coupons_price the value for 
     *
     * @MLTH_generated
     */
    public void setCoupons_price(Double coupons_price) {
        this.coupons_price = coupons_price;
    }

    /**
     *   剩余个数
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getSurplus_count() {
        return surplus_count;
    }

    /**
     *   剩余个数
     * @param surplus_count the value for 
     *
     * @MLTH_generated
     */
    public void setSurplus_count(Integer surplus_count) {
        this.surplus_count = surplus_count;
    }

    /**
     *   总个数
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getTotal_count() {
        return total_count;
    }

    /**
     *   总个数
     * @param total_count the value for 
     *
     * @MLTH_generated
     */
    public void setTotal_count(Integer total_count) {
        this.total_count = total_count;
    }

    /**
     *   门槛
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getStep_value() {
        return step_value;
    }

    /**
     *   门槛
     * @param step_value the value for 
     *
     * @MLTH_generated
     */
    public void setStep_value(Double step_value) {
        this.step_value = step_value;
    }

    /**
     *   卷类型1：红包 2：优惠卷
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getType() {
        return type;
    }

    /**
     *   卷类型1：红包 2：优惠卷
     * @param type the value for 
     *
     * @MLTH_generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     *   开始时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getStart_time() {
        return start_time;
    }

    /**
     *   开始时间
     * @param start_time the value for 
     *
     * @MLTH_generated
     */
    public void setStart_time(Date start_time) {
        this.start_time = start_time;
    }

    /**
     *   结束时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     *   结束时间
     * @param end_time the value for 
     *
     * @MLTH_generated
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     *   1:启用，2停用
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   1:启用，2停用
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *   面额
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getValue() {
        return value;
    }

    /**
     *   面额
     * @param value the value for 
     *
     * @MLTH_generated
     */
    public void setValue(Double value) {
        this.value = value;
    }

    /**
     *   创建人id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     *   创建人id
     * @param user_id the value for 
     *
     * @MLTH_generated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   每人限领
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getLimit_count() {
        return limit_count;
    }

    /**
     *   每人限领
     * @param limit_count the value for 
     *
     * @MLTH_generated
     */
    public void setLimit_count(Integer limit_count) {
        this.limit_count = limit_count;
    }

    public Integer getRandom_count() {
		return random_count;
	}

	public void setRandom_count(Integer random_count) {
		this.random_count = random_count;
	}

	public String getDetails() {
		return details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	@Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", scope_type=").append(scope_type);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", coupons_price=").append(coupons_price);
        sb.append(", surplus_count=").append(surplus_count);
        sb.append(", total_count=").append(total_count);
        sb.append(", step_value=").append(step_value);
        sb.append(", type=").append(type);
        sb.append(", start_time=").append(start_time);
        sb.append(", end_time=").append(end_time);
        sb.append(", state=").append(state);
        sb.append(", value=").append(value);
        sb.append(", user_id=").append(user_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", limit_count=").append(limit_count);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}