package com.mfangsoft.zhuangjialong.app.salesnum.model;

import java.io.Serializable;

/**
 *   产品销量表
 * table t_biz_sales_num
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class SalesNumEntity implements Serializable {
    /**
     *   主键id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   产品id
     * column product_id
     *
     * @MLTH_generated
     */
    private Long product_id;

    /**
     *   销量
     * column sales_num
     *
     * @MLTH_generated
     */
    private Long sales_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_sales_num
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   主键id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   产品id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getProduct_id() {
        return product_id;
    }

    /**
     *   产品id
     * @param product_id the value for 
     *
     * @MLTH_generated
     */
    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    /**
     *   销量
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getSales_num() {
        return sales_num;
    }

    /**
     *   销量
     * @param sales_num the value for 
     *
     * @MLTH_generated
     */
    public void setSales_num(Long sales_num) {
        this.sales_num = sales_num;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", product_id=").append(product_id);
        sb.append(", sales_num=").append(sales_num);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}