package com.mfangsoft.zhuangjialong.integration.commerce.model;

import java.io.Serializable;

/**
 *   工商信息
 * table t_biz_commerce
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class CommerceEntity implements Serializable {
    /**
     *   id
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   营业执照号
     * column biz_num
     *
     * @MLTH_generated
     */
    private String biz_num;

    /**
     *   营业执照图URL
     * column biz_url
     *
     * @MLTH_generated
     */
    private String biz_url;

    /**
     *   开户许可证号
     * column open_acount
     *
     * @MLTH_generated
     */
    private String open_acount;

    /**
     *   开户许可证URL
     * column open_acount_url
     *
     * @MLTH_generated
     */
    private String open_acount_url;

    /**
     *   税务登记证号
     * column tax_num
     *
     * @MLTH_generated
     */
    private String tax_num;

    /**
     *   税务登记证URL
     * column tax_url
     *
     * @MLTH_generated
     */
    private String tax_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_commerce
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   id
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     *   id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   营业执照号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getBiz_num() {
        return biz_num;
    }

    /**
     *   营业执照号
     * @param biz_num the value for 
     *
     * @MLTH_generated
     */
    public void setBiz_num(String biz_num) {
        this.biz_num = biz_num == null ? null : biz_num.trim();
    }

    /**
     *   营业执照图URL
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getBiz_url() {
        return biz_url;
    }

    /**
     *   营业执照图URL
     * @param biz_url the value for 
     *
     * @MLTH_generated
     */
    public void setBiz_url(String biz_url) {
        this.biz_url = biz_url == null ? null : biz_url.trim();
    }

    /**
     *   开户许可证号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getOpen_acount() {
        return open_acount;
    }

    /**
     *   开户许可证号
     * @param open_acount the value for 
     *
     * @MLTH_generated
     */
    public void setOpen_acount(String open_acount) {
        this.open_acount = open_acount == null ? null : open_acount.trim();
    }

    /**
     *   开户许可证URL
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getOpen_acount_url() {
        return open_acount_url;
    }

    /**
     *   开户许可证URL
     * @param open_acount_url the value for 
     *
     * @MLTH_generated
     */
    public void setOpen_acount_url(String open_acount_url) {
        this.open_acount_url = open_acount_url == null ? null : open_acount_url.trim();
    }

    /**
     *   税务登记证号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getTax_num() {
        return tax_num;
    }

    /**
     *   税务登记证号
     * @param tax_num the value for 
     *
     * @MLTH_generated
     */
    public void setTax_num(String tax_num) {
        this.tax_num = tax_num == null ? null : tax_num.trim();
    }

    /**
     *   税务登记证URL
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getTax_url() {
        return tax_url;
    }

    /**
     *   税务登记证URL
     * @param tax_url the value for 
     *
     * @MLTH_generated
     */
    public void setTax_url(String tax_url) {
        this.tax_url = tax_url == null ? null : tax_url.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", biz_num=").append(biz_num);
        sb.append(", biz_url=").append(biz_url);
        sb.append(", open_acount=").append(open_acount);
        sb.append(", open_acount_url=").append(open_acount_url);
        sb.append(", tax_num=").append(tax_num);
        sb.append(", tax_url=").append(tax_url);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}