package com.mfangsoft.zhuangjialong.integration.prepayment.model;

import java.io.Serializable;

/**
 *   预付定金金额表
 * table t_biz_prepay_value
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class PrepayValue implements Serializable {
    /**
     *   主键id
     * column id
     *
     * @MLTH_generated
     */
    private Integer id;

    /**
     *   金额
     * column value
     *
     * @MLTH_generated
     */
    private Double value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_biz_prepay_value
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *   主键id
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getId() {
        return id;
    }

    /**
     *   主键id
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   金额
     * @return the value of DOUBLE
     *
     * @MLTH_generated
     */
    public Double getValue() {
        return value;
    }

    /**
     *   金额
     * @param value the value for 
     *
     * @MLTH_generated
     */
    public void setValue(Double value) {
        this.value = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", value=").append(value);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}