package com.mfangsoft.zhuangjialong.integration.user.model;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang3.StringUtils;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.mfangsoft.zhuangjialong.integration.department.model.DepartmentEntity;
import com.mfangsoft.zhuangjialong.integration.role.model.RoleEntity;
import com.mfangsoft.zhuangjialong.integration.role.model.UserRoleEntity;

/**
 *   用户表
 * table t_sys_user
 *
 * @MLTH_generated do_not_delete_during_merge
 */
public class UserEntity implements Serializable {
    /**
     * column id
     *
     * @MLTH_generated
     */
    private Long id;

    /**
     *   用户姓名
     * column user
     *
     * @MLTH_generated
     */
    private String user;

    /**
     *   用户登录账号
     * column account
     *
     * @MLTH_generated
     */
    private String account;

    /**
     *   MD5加密
     * column pwd
     *
     * @MLTH_generated
     */
    private String pwd;

    /**
     *   创建时间
     * column create_time
     *
     * @MLTH_generated
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date create_time;

    /**
     *   启用/停用
     * column state
     *
     * @MLTH_generated
     */
    private Integer state;

    /**
     *   1：平台商；2：企业；3：城市合伙人；4：品牌；5：实体店铺，0：后台用户
     * column user_type
     *
     * @MLTH_generated
     */
    
    private String phone_num;
    public String getPhone_num() {
		return phone_num;
	}

	public void setPhone_num(String phone_num) {
		this.phone_num = phone_num;
	}

	private Integer user_type;
	
	private String v_code;

    public String getV_code() {
		return v_code;
	}

	public void setV_code(String v_code) {
		this.v_code = v_code;
	}

	/**
     *   所属部门
     * column department_id
     *
     * @MLTH_generated
     */
    private Long department_id;

    /**
     *   所属岗位
     * column position_id
     *
     * @MLTH_generated
     */
    private Long position_id;
    
    
    private Integer is_seat;
    
    
    public Integer getIs_seat() {
		return is_seat;
	}

	public void setIs_seat(Integer is_seat) {
		this.is_seat = is_seat;
	}

	private UserRoleEntity role;
    
    private RoleEntity roleEntity;
    
    public RoleEntity getRoleEntity() {
		return roleEntity;
	}

	public void setRoleEntity(RoleEntity roleEntity) {
		this.roleEntity = roleEntity;
	}

	private  String department_name;
    
    
    private String position_name;
    
    
    private String role_name;
    
    private String enterprise_name;
    
    
    
    public String getEnterprise_name() {
		return enterprise_name;
	}

	public void setEnterprise_name(String enterprise_name) {
		this.enterprise_name = enterprise_name;
	}

	public String getDepartment_name() {
    	
    	if(this.department!=null){
    	
    	this.department_name =this.department.getName();
    	}
    	
		return department_name;
	}

	public String getPosition_name() {
		
		if(this.position!=null){
			this.position_name = this.position.getName();
		}
		return position_name;
	}

	public String getRole_name() {
		
		if(this.roleEntity!=null){
			this.role_name = this.roleEntity.getRole_name();
		}
		return role_name;
	}

	private DepartmentEntity department;
    
    private DepartmentEntity position;
    
    
    
    

	public DepartmentEntity getDepartment() {
		return department;
	}

	public void setDepartment(DepartmentEntity department) {
		this.department = department;
	}

	public DepartmentEntity getPosition() {
		return position;
	}

	public void setPosition(DepartmentEntity position) {
		this.position = position;
	}

	public UserRoleEntity getRole() {
		return role;
	}

	public void setRole(UserRoleEntity role) {
		this.role = role;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_user
     *
     * @MLTH_generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for 
     *
     * @MLTH_generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   用户姓名
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getUser() {
        return user;
    }

    /**
     *   用户姓名
     * @param user the value for 
     *
     * @MLTH_generated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     *   用户登录账号
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getAccount() {
    	
    	return this.account;
    }

    /**
     *   用户登录账号
     * @param account the value for 
     *
     * @MLTH_generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     *   MD5加密
     * @return the value of VARCHAR
     *
     * @MLTH_generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     *   MD5加密
     * @param pwd the value for 
     *
     * @MLTH_generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     *   创建时间
     * @return the value of TIMESTAMP
     *
     * @MLTH_generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     *   创建时间
     * @param create_time the value for 
     *
     * @MLTH_generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     *   启用/停用
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getState() {
        return state;
    }

    /**
     *   启用/停用
     * @param state the value for 
     *
     * @MLTH_generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     *   1：平台商；2：企业；3：城市合伙人；4：品牌；5：实体店铺，0：后台用户
     * @return the value of INTEGER
     *
     * @MLTH_generated
     */
    public Integer getUser_type() {
        return user_type;
    }

    /**
     *   1：平台商；2：企业；3：城市合伙人；4：品牌；5：实体店铺，0：后台用户
     * @param user_type the value for 
     *
     * @MLTH_generated
     */
    public void setUser_type(Integer user_type) {
        this.user_type = user_type;
    }

    /**
     *   所属部门
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getDepartment_id() {
        return department_id;
    }

    /**
     *   所属部门
     * @param department_id the value for 
     *
     * @MLTH_generated
     */
    public void setDepartment_id(Long department_id) {
        this.department_id = department_id;
    }

    /**
     *   所属岗位
     * @return the value of BIGINT
     *
     * @MLTH_generated
     */
    public Long getPosition_id() {
        return position_id;
    }

    /**
     *   所属岗位
     * @param position_id the value for 
     *
     * @MLTH_generated
     */
    public void setPosition_id(Long position_id) {
        this.position_id = position_id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", user=").append(user);
        sb.append(", account=").append(account);
        sb.append(", pwd=").append(pwd);
        sb.append(", create_time=").append(create_time);
        sb.append(", state=").append(state);
        sb.append(", user_type=").append(user_type);
        sb.append(", department_id=").append(department_id);
        sb.append(", position_id=").append(position_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}